flashinfer-ai/flashinfer

- src/tvm_wrapper.cu
This PR splits the TVM wrapper so that prefill and decode has their own wrapper function.
This prevents the runtime overhead of dispatching to prefill kernel or decode kernel.
> [Wrapper] Split prefill/decode wrapper

- include/flashinfer/decode.cuh
- include/flashinfer/wrapper.cuh
This PR applies the following changes to the KV cache split:
- removed the map structure for temporary array cache,
- changed cudaMallocAsync to cudaMalloc in the split work estimation, as we noticed that the asynchronous malloc takes huge amount of time on 4090.
- only apply KV cache split when batch size is no more than 2. This might be adjusted further based on more evaluation.
> [Decode] KV cache split pre-process update

- CMakeLists.txt
This PR updates the CMakeLists to properly get the TVM_HOME after TVM being removed from the 3rdparty.
> [CMake] Reading TVM_HOME from build args or environment

- include/flashinfer/mma.cuh
`stmatrix` output operand missing. Fix it by adding a ':'.
> [FIX] stmatrix asm output operand

- include/flashinfer/vec_dtypes.cuh
This prevents host-side warnings such as: `ignoring #pragma unroll` or `dereferencing type-punned pointer will break strict-aliasing rules`.
> Tweak `FLASHINFER_INLINE` into a device-only specifier

- include/flashinfer/mma.cuh
We mistakenly fill the same constant value in `frag_b` of mma rowsum function for both bf16 and fp16. However, we should use different values because 1's binary representation in bf16 & fp16 is not the same.
```python
>>> import torch
>>> x = torch.ones(2).half()
>>> x.view(dtype=torch.int32)
tensor([1006648320], dtype=torch.int32)
>>> x = torch.ones(2).bfloat16()
>>> x.view(dtype=torch.int32)
tensor([1065369472], dtype=torch.int32)
```
> [Bugfix] Fix the frag_b constant for mma rowsum of b16 input data type

- include/flashinfer/utils.cuh
Mistral uses 4 and current we only compile 1 and 8.
> Compile more GQA group sizes

- include/flashinfer/permuted_smem.cuh
- include/flashinfer/prefill.cuh
Rename `cell_t` to `b128_t` to make the type name more concise.
> [Refactor] Rename cell to b128

- include/flashinfer/prefill.cuh
Note that prefill kernel's synchronization overhead is larger than decode's. A naive linear model might not be optimal is finding the best chunk size. We should create an analytical cost model in the future.
> [Performance] Cooperative prefill parameter tweak

- python/setup.py
Otherwise, the packages cannot be built when running `pip install` without `-e`.
> Add find_packages in setup.py

- CMakeLists.txt
- cmake/config.cmake
Followup of #42 , we remove the default value of `FLASHINFER_CUDA_ARCHITECTURES`, now it must be specified by user (either by setting the value in `config.cmake` or calling `cmake` via `cmake .. -DFLASHINFER_CUDA_ARCHITECTURES=xx`). We also change behavior of `FLASHINFER_CUDA_ARCHITECTURES` is
1. if `FLASHINFER_CUDA_ARCHITECTURES` is defined, override `CMAKE_CUDA_ARCHITECTURES` with `FLASHINFER_CUDA_ARCHITECTURES`.
1. if the `FLASHINFER_CUDA_ARCHITECTURES` is not defined (e.g. externally), use `CMAKE_CUDA_ARCHITECTURES` (e.g. defined externally).
cc @MasterJH5574
> [Hotfix] Fix the behavior of `FLASHINFER_CUDA_ARCHITECTURES` flag in cmake

- include/flashinfer/cascade.cuh
- include/flashinfer/prefill.cuh
- include/flashinfer/utils.cuh
We found that cooperative kernel (merge states in the same kernel afte grid synchronization) actually limits kernel's performance when merging workload is relatively large (e.g. in GQA or append prefill kernels). This PR splits the cooperative kernel to two kernels for append prefill kernels.
> [Performance] Accelerate append prefill kernel

- include/flashinfer/prefill.cuh
#48 is buggy when `lse` is nullptr, we should always store LSE when `split_kv` is true because the merge kernel needs it, whatever `lse` is.
> [Bugfix] Store LSE when split_kv is activated

- include/flashinfer/cascade.cuh
- python/csrc/cascade.cu
- python/flashinfer/ops/__init__.py
This dimension could either be `seq_len` or `batch_size` but `seq_len` is the more usual use case.
> [Refactor] Change `batch_size` dimension to `seq_len` dimensions

- include/flashinfer/decode.cuh
The lse returned by `BatchDecodeWithPagedKVCacheKernel` is wrong if Paged-KV is splitted.
> [Bugfix] Fix the lse computation for batch decode kernel

- include/flashinfer/prefill.cuh
In our previous design `num_frags_z` is fixed to 2 which is not optimal for GPUs with large shared memory per SM.
> [Performance] Increase `num_frags_z` for GPUs with larger shared memory per SM

- include/flashinfer/cascade.cuh
- include/flashinfer/prefill.cuh
- python/csrc/cascade.cu
- python/flashinfer/ops/__init__.py
- src/bench_cascade.cu
- src/test_cascade.cu
Also, reorder the input dimension of `MergeStates` to be consistent with variable length version.
> [Feature] Support variable length merge states

- include/flashinfer/decode.cuh
- include/flashinfer/handler.cuh
- include/flashinfer/page.cuh
- include/flashinfer/prefill.cuh
- src/bench_batch_decode.cu
- src/bench_single_decode.cu
- src/test_batch_decode.cu
- src/test_single_decode.cu
- src/tvm_wrapper.cu
In our initial design we use CUDA cooperative kernels and grid synchronization feature for cross threadblock reduction. Although it's slightly faster for multi-head attention without grouping (GQA), we found there are two issues with this implementation:
1. The kernel scheduling for cross-threadblock merging (the code after `grid.sync`) is sub-optimal, the merging time would be the bottleneck when the number of chunks to merge is huge (e.g. in GQA).
2. Not all hardware has grid synchronization feature (only NVIDIA & AMD GPUs have such features AFAIK), which makes FlashInfer implementation hard to generalize to other GPUs such as Metal.
In this PR we stop using CUDA cooperative kernels features and using the combo two kernels (one for decode, another for merge) instead, it harms …
> [Refactor] Use two kernels instead of CUDA cooperative kernel for batch/single decode

- include/flashinfer/decode.cuh
- include/flashinfer/handler.cuh
- include/flashinfer/prefill.cuh
- include/flashinfer/rope.cuh
- include/flashinfer/utils.cuh
- src/bench_cascade.cu
- src/cpu_reference.h
Before this PR,  we directly abort the program for runtime errors which is not desired behavior for a header-only library. This PR converts all `abort()` call to C++ `std::runtime_error` exceptions, so that we can catch them in different applications that imports flashinfer header files.
> [Refactor] Use `std::runtime_error` instead of `abort()`

- include/flashinfer/decode.cuh
The fp8 decode kernel performance degrades because of the changes in previous commits https://github.com/flashinfer-ai/flashinfer/commit/2a3d6d038d3ee57904b150c0ad107556568c2c1f . This PR fixes the degradation.
> [Performance] Fix the fp8 decode kernel performance degradation issue

- include/flashinfer/handler.cuh
- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/flashinfer_ops.h
- python/flashinfer/ops/__init__.py
- python/tests/test_batch_decode_kernels.py
- python/tests/test_batch_prefill_kernels.py
- src/bench_batch_decode.cu
- src/bench_cascade.cu
- src/test_batch_decode.cu
- src/test_cascade.cu
- src/tvm_wrapper.cu
To avoid the overhead of allocating/destroy memory per step.
> [Performance] Using user-allocated workspace for batch decode/prefill handlers

- .github/workflows/release_wheel.yml
PyTorch wheels for py312 is not ready yet, we should follow PyTorch's version.
> [CI] Remove py3.12 from the matrix

- include/flashinfer/decode.cuh
- include/flashinfer/page.cuh
- include/flashinfer/prefill.cuh
- include/flashinfer/wrapper.cuh
- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- src/bench_batch_decode.cu
- src/test_batch_decode.cu
- src/test_batch_prefill.cu
- src/tvm_wrapper.cu
This PR adds q/k position information to batch prefill/decode kernels. More specifically, the kernel now accepts two additional arrays:
* `q_rope_position` with shape `(total_q_len,)`, denoting the in-sequence position of each position in the input q.
* `k_rope_pos_offset` with shape `(num_sequence,)`, denoting the start position of each sequence in k.
These two arrays helps on-the-fly calculate RoPE in multi-level cases.
Tests `test_batch_prefill` and `test_batch_decode` can pass. Performance is not validated yet. Per discussion with Zihao, this change is not very likely to incur significant perf regression.
> Support RoPE position info in batch prefill/decode kernels

- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/cascade.cu
- python/csrc/page.cu
- python/csrc/pytorch_extension_utils.h
- python/csrc/single_decode.cu
- python/csrc/single_prefill.cu
This PR makes PyTorch ops use the current Torch stream for kernel execution. This allows compatibility with Torch CUDA Graphs and allows the user to precisely set which stream to use in Python code using the canonical PyTorch API.
Note: I believe I have found all cases where the stream should be set, but I might have missed something.
> Use Torch's current stream for ops

- include/flashinfer/wrapper.cuh
- python/csrc/batch_prefill.cu
- python/csrc/cascade.cu
- python/csrc/flashinfer_decl.h
- python/csrc/page.cu
- python/csrc/pytorch_extension_utils.h
- python/flashinfer/__init__.py
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/page.py
- python/flashinfer/prefill.py
- python/flashinfer/utils.py
- python/setup.py
- python/tests/test_batch_decode_kernels.py
- python/tests/test_batch_prefill_kernels.py
- python/tests/test_shared_prefix_kernels.py
This PR fixes #113, which is because #69 changed the `BatchPrefillWithPagedKVCacheWrapperDispatched` signature, and   `flashinfer_decl.h` was not updated accordingly.
Also fixes some tiny format issues in #111.
> bugfix: fix the compilation issue of pip wheels

- .github/workflows/release_wheel.yml
- scripts/run-ci-build-wheel.sh
Previous package naming convention cannot be recognized by packaging tools:
```
setuptools.extern.packaging.version.InvalidVersion: Invalid version: '0.0.2+cu118+torch2.1.0'
```
> fix: version naming issue

- .github/workflows/release_wheel.yml
This reverts commit 01820330ce0db5f4fdfbad0908b87ff73c646e19.
Revert "ci: add an option of skipping build wheels (#122)"
This reverts commit 3e19ec3574cb921abfb764ec77a26daf08bd3ca3.
Revert "ci: run release if build wheel success or skipped (#123)"
> ci: revert #122 and #123

- src/tvm_wrapper.cu
In GPT-2, attention calculation requires an additional feature scale_attn_by_inverse_layer_idx. It provides a scaling factor per attention layer when calculating the attention score, before applying the softmax function.
This PR supports this additional parameter in tvm_wrapper.
See: https://github.com/apache/tvm/pull/16606
> Passing in attn_score_scaling_factor into tvm_wrapper

- .github/workflows/release_wheel.yml
According to #129 , we should release py38 wheels as well.
> ci: py38 wheels

- include/flashinfer/handler.cuh
- include/flashinfer/permuted_smem.cuh
- include/flashinfer/prefill.cuh
- include/flashinfer/utils.cuh
- include/flashinfer/wrapper.cuh
- python/csrc/batch_prefill.cu
- python/csrc/flashinfer_ops.h
- python/flashinfer/cascade.py
- python/flashinfer/prefill.py
- python/setup.py
- python/tests/test_batch_prefill_kernels.py
- python/tests/test_shared_prefix_kernels.py
- src/bench_batch_decode.cu
- src/bench_cascade.cu
- src/test_batch_decode.cu
- src/test_batch_prefill.cu
- src/test_cascade.cu
- src/test_single_prefill.cu
- src/tvm_wrapper.cu
As mentioned in #130 , the kernels for `head_dim=256` are not compiled by default, this PR expose these attention kernels to pip wheels and adds unittests/benchmarks for `head_dim=256`.
> feat: enable `head_dim=256` for attention kernels

- src/tvm_wrapper.cu
This PR unifies the naming convention of tvm wrapper symbols @MasterJH5574 .
> refactor: change tvm wrapper symbol names

- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/attention/wrapper.cuh
- python/csrc/flashinfer_decl.h
- python/csrc/flashinfer_ops.h
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- src/bench_single_decode.cu
- src/bench_single_prefill.cu
- src/tvm_wrapper.cu
Some of our attention APIs have this field and some don't, this PR add `sm_scale` field for all attention APIs to make them consistent.
> feat: adding `sm_scale` field for all attention APIs

- README.md
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/prefill.py
> doc: update the docstring related to alibi

- include/flashinfer/attention/decode.cuh
- python/csrc/batch_decode.cu
- python/csrc/pytorch_extension_utils.h
- python/csrc/single_decode.cu
- python/flashinfer/prefill.py
- python/flashinfer/utils.py
- python/setup.py
- python/tests/test_batch_decode_kernels.py
> feat: pytorch api of fp8 kv-cache

- cmake/modules/FindThrust.cmake
The latest thrust version corresponding to CUDA 12.4 is 200301 which is not divisible by 100.
Use predefined `THRUST_MINOR_VERSION`/ `THRUST_MAJOR_VERSION` instead.
> fix: fix FindThrust.cmake

- include/flashinfer/page.cuh
`__ldg` do not support pointer data types.
> bugfix: fix the behavior of `get_k/v_ptr` for `PageStorage::kPointers`

- python/setup.py
- scripts/run-ci-build-wheel.sh
Test Env:
```
Os/Container: Ubuntu 22.04
GCC/G++: 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 
Cpu: Zen3 9334 (2x)
Cpu cores/threads: Container limited to 80 instead of full 96
Ram: 2TB 
Disk: ZFS array
Torch: 2.2.0
Python 3.11.5 (miniconda)
Cuda: 12.4
```
This PR resolves two issues 1) compile linking failed on my env 2) reduce compile time by ~22%. I expect the diff to be larger if underlying io storage is slow spinners/ssd.
1. Resolve compilation compat in some envs causing final stage ld/linking errors: Ubuntu 22.04 gcc/g++ 11.4.  Most likely due to some strange reason the -std=c++17 flag is not propagated correctly? I am unsure why force setting -std=c++17 resolves issue when nvcc already defaults to -std=c++17. There should be no harm to foce this flag since nvcc already defaults to …
> 1. Reduce compile time by 22%+ 2. Fix compile linking error on Ubuntu 22.04 gcc/g++ 11.4 with Cuda 12.4

- .github/workflows/release_wheel.yml
- python/generate_batch_paged_prefill_inst.py
- python/setup.py
1. Do not generate prefill kernels for `page_size=8`
2. Build with `-Xfatbin=-compress-all` to reduce binary size.
Followup of #171 , @Qubitium  the cuda architectures to be compiled could be controlled by environment variable `TORCH_CUDA_ARCH_LIST`, so I removed the gencode/archs specified in compile args.
> ci: reduce binary size

- .github/workflows/release_wheel.yml
- include/flashinfer/utils.cuh
- python/setup.py
The release action [failed](https://github.com/flashinfer-ai/flashinfer/actions/runs/8227731974/job/22501369048) because [action-gh-release](https://github.com/softprops/action-gh-release) action do not support uploading multiple large files at a time: https://github.com/softprops/action-gh-release/issues/353
This PR changes the behavior of release job to upload artifacts in multiple batches.
Also, https://github.com/flashinfer-ai/flashinfer/pull/172 removes the instantiation of page prefill kernels for `page_size=8`, this PR fixes the behavior of `DISPATCH_PAGE_SIZE` by removing corresponding branches.
> bugfix: Fix release wheel script and remove uninstantiated branches in dispatch

- include/flashinfer/mma.cuh
> feat: mma rowsum for fp8

- include/flashinfer/mma.cuh
- python/csrc/pytorch_extension_utils.h
as title. change build error to runtime error to allow build pass for different architecture, following cutlass's approach.
> [fix] change build error to runtime error to allow build pass with older architecture.

- CMakeLists.txt
- include/flashinfer/mma.cuh
This PR adds the `-fPIC` option to prefill/decode kernels for packaging.
> [CMake] Add positional independent code (PIC) option to kernels

- include/flashinfer/pos_enc.cuh
When I was using flashinfer, I encountered that the heads of some models were not powers of 2. I refer to **flashinfer/python/tests/alibi_reference.py**,  modifies this part of the C++ code.
> feat:support any num_heads for get_alibi_slope

- CMakeLists.txt
- cmake/utils/Utils.cmake
- include/flashinfer/utils.cuh
This PR makes the generation options configurable. Also fixes a bug of cmake option to allow list values.
Finally, add an option to minimize compiled binaries when some options are turned off at compile time.
> [CMAKE] Make generation option configuration

- include/flashinfer/sampling.cuh
Add a new API `ParallelTopPSamplingFromProb`, which enables sampling from the same distribution multiple times, and allowing user to specify batch-specific `top_p`.
cc @MasterJH5574
> sampling: support parallel top-p sampling

- .github/workflows/release_wheel.yml
Release pytorch 2.3 version in next release.
> ci: add pytorch 2.3 to matrix

- include/flashinfer/sampling.cuh
In #225  we use `BLOCK_SCAN_WARP_SCANS` to make sure prefix sum result is monotonic, however, we found there are still cases that InclusiveSum with `BLOCK_SCAN_WARP_SCANS` algorithm still do not return monotonic output.
In this PR, we fix the behavior in another way: apply prefix sum on a pair `(value, greater_than_0)` instead of only `value`, and write `i` to output only when `value[i] > u && value[i - 1] <= u` and `prob[i] > 0`. If there are multiple `i` that satisfy this condition (because of the floating point numerical issues), we select the smallest `i`.
> bugfix: fix the potential issue of sampling kernels

- python/MANIFEST.in
The wheel building script fails because MANIFEST.in doesn't include `generate_dispatch_inc.py`, this PR fix the issue.
> bugfix: fix MANIFEST.in

- python/setup.py
We already created lots of process and there is no need to use multi-threading to accelerate compilation.
> ci: remove multi-threading in nvcc compile flags

- python/csrc/pytorch_extension_utils.h
- python/generate_dispatch_inc.py
There are some mistakes in our macro definitions which results in lots of warnings and potential bugs.
> fix: fix macro to suppress compilation warning

- .github/workflows/release_wheel.yml
Run it on self-hosted runner because default github runner do not have enough disk space.
Fix the python scripts that updates wheel index so that it can mkdir when directory not exists.
> ci: update release wheel yaml

- src/utils.h
We forgot to break in case statements in #235
> bugfix: Fix dispatcher in src directory

- python/setup.py
This fixes a compilation error caused by a `-Wno-switch-bool` flagged being passed to `nvcc` instead of `gcc`. Fixes #243.
> Move -Wno-switch-bool argument to cxx from nvcc

- CMakeLists.txt
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/utils.cuh
- src/test_batch_prefill.cu
This merge request supports versatile gqa size for batch prefill kernels. Group size 5, 6, 7, will be padded to group size 8 when loading q from global memory to shared memory, the padded groups will be discarded when writing o to global memory.
> support versatile gqa size for batch prefill

- CMakeLists.txt
Followup of #251 , keep `TVM_HOME` for a while for backward compatibility.
> cmake: backward compatibility for TVM_HOME

- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
Previously we bind a factory method as the init function for C++ Class in Pybind, which is returned by value instead of reference. The destructive function of handlers in #253 will be triggered twice, and it leads to segmentation faults.
This PR bypass the factory method and initializes the C++ classes directly.
> bugfix: fix pybind class bindings

- docs/api/python/decode.rst
- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/utils.cuh
- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/flashinfer/__init__.py
- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- python/setup.py
- python/tests/test_batch_decode_kernels.py
As requested in #187 , this PR adds initial support of `CUDAGraph` compatibility of flashinfer batch decode attention kernels. This PR is the first step towards full CUDAGraph support and we will implement CUDAGraph compatible prefill operators in later PRs.
We add another wrapper `CUDAGraphBatchDecodeWithPagedKVCacheWrapper`, and user need to pre-allocation page data structure buffers to initialize this wrapper class. Once initiated, these buffers are pinned on GPUs in the life cycle of the wrapper class.
The behavior of `CUDAGraphBatchDecodeWithPagedKVCacheWrapper` is a little bit different from `BatchDecodeWithPagedKVCacheWrapper`'s: we will only run a fixed set of kernels in CUDAGraph mode, no matter what the input shape is (the original implementation will dispatch to different …
> perf: initial cuda graph support

- include/flashinfer/sampling.cuh
The cub version in cuda 118 is too old to use `SubtractLeft`, use old `FlagHeads` api instead.
> bugfix: use `FlagHeads` instead of `SubtractLeft` for cuda 118

- include/flashinfer/attention/prefill.cuh
Followup of #266, add guard to mask array access.
> bugfix: avoid potential illegal memory access

- .gitmodules
We use [mscclpp](https://github.com/microsoft/mscclpp) for custom distributed kernels.
> 3rdparty: add mscclpp dependency

- docs/tutorials/kv_layout.rst
- python/flashinfer/prefill.py
Followup of #266 , this pr adds some docstring and diagrams for 2D ragged tensor mask layout.
> doc: update documentation for mask layout

- include/flashinfer/fastdiv.cuh
- src/test_fastdiv.cu
Use explicit unsigned conversion to suppress compilation warnings of fastdiv, followup of #278 .
> misc: suppress compilation warning of fastdiv

- include/flashinfer/attention/handler.cuh
- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/tests/test_batch_decode_kernels.py
The `indptr` array length should be a upper-bound of `batch_size + 1` in cuda graph mode.
> bugfix: fix cudagraph-compatible prefill/decode apis

- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/single_decode.cu
- python/csrc/single_prefill.cu
Right now, we require q and kv tensors to have the same dtype, but that is not enforced, which can lead to cryptic memory errors in case of a misconfiguration. This PR adds a check to ensure that we prevent mismatched dtypes.
> Add dtype checks for q-kv tensors

- include/flashinfer/attention/handler.cuh
In our handlers, we return `void**` for `aligned_alloc` function calls and it will be convered to `void*`, it will not cause correctness issues but we should fix the behavior: just return `void*`.
> bugfix: fix the data type of aligned_alloc in handlers

- CMakeLists.txt
As a result of typo, it appeared two variables: `DECODE_F8_DTYPES` and `DECODE_FP8_DTYPES` in CMakeLists.txt. But it should be the same. This commit fixes this discrepancy and rename `DECODE_F8_DTYPES` -> `DECODE_FP8_DTYPES`.
> cmake: fix DECODE_F8_DTYPES and DECODE_FP8_DTYPES discrepancy

- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/handler.cuh
- include/flashinfer/decode_attention_decl.cuh
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- python/generate_batch_paged_decode_inst.py
- python/tests/test_batch_decode_kernels.py
- python/tests/test_batch_prefill_kernels.py
- src/bench_batch_decode.cu
- src/flashinfer_ops.cuh
- src/test_batch_decode.cu
In this PR, we fixed the grid size of the kernels launched by a decode cuda graph wrapper:
* We always launch a kernel with fixed grid size (should be an upperbound of effective grid size)
* Early stop for threadblocks that is out of bound.
> bugfix: Fix the behavior of decode cuda graph wrapper

- cmake/config.cmake
We found that setting CUDA architecture to `native` may result in slow compilation, especially if there are GPU programs running. This PR adds some notes to the `config.cmake` file to encourage user to set the architecture to a specific value.
> misc: add some notes in `cmake.config`

- include/flashinfer/attention/handler.cuh
In #294 , we set `padded_batch_size_` to `num_kv_heads * batch_size`, which should be `batch_size`
> bugfix: fix wrong `padded_batch_size_`

- include/flashinfer/sampling.cuh
We declare multiple kernels inside the `sampling.cuh` and they use dynamic shared memory (with the same extern variable name) with different alignment requirements (e.g. some are alignof 4, some are alignof 64).
In this PR we use different names for extern variable that have different alignment requirements to suppress the warning.
> bugfix: suppress alignment warning of sampling kernels

- python/flashinfer/decode.py
- python/flashinfer/prefill.py
The logits cap was applied to pre-attention logits, not attention scores.
> doc: fix the description of logits cap in docstring

- CMakeLists.txt
- cmake/config.cmake
- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/decode_attention_decl.cuh
- include/flashinfer/fastdiv.cuh
- include/flashinfer/layout.cuh
- include/flashinfer/prefill_attention_decl.cuh
- include/flashinfer/utils.cuh
- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/pytorch_extension_utils.h
- python/csrc/single_decode.cu
- python/csrc/single_prefill.cu
- python/flashinfer/prefill.py
- python/generate_batch_padded_decode_inst.py
- python/generate_batch_paged_decode_inst.py
- python/generate_batch_paged_prefill_inst.py
- python/generate_batch_ragged_prefill_inst.py
- python/generate_dispatch_inc.py
- python/generate_single_decode_inst.py
- python/generate_single_prefill_inst.py
- python/setup.py
- src/cpu_reference.h
- src/flashinfer_ops.cuh
- src/test_batch_prefill.cu
#262 is out of sync with main, this PR rebased the code on main branch.
> rafactor: move `gqa_group_size` from template parameter to input arguments

- python/setup.py
Nvcc compilation profile has changed drastically now that `gqa_group_size` is an input arg and no longer a template parameter.
This PR improves compile time by ~20% on my dev machine. Result may vary due to diff env but I expect a net positive overall. 
Env: 13900K  PCores: 5.6GHz + ECores: 4.0GHz (Both are OCed). Total of 32 hw threads. 
TEST: use scripts/run-ci-build-wheel.sh and time compile to step(20) completion. 
```
env FLASHINFER_CI_PYTHON_VERSION=3.11 FLASHINFER_CI_TORCH_VERSION=2.3.1 FLASHINFER_CI_CUDA_VERSION=12.4 FLASHINFER_BUILD_VERSION=0.0.4 TORCH_CUDA_ARCH_LIST=“8.0;8.6;8.9"
```
```
nvcc_threads=8 41.01s to step20 MAX_JOBS=16 <-- current default
nvcc_threads=2 41.21s to step20 MAX_JOBS=16
nvcc_threads=1 50.97s to step20 MAX_JOBS=16
nvcc_threads=4 40.83s to step20 …
```
> Faster compile/ci

- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/prefill_attention_decl.cuh
- python/csrc/single_prefill.cu
- python/generate_single_prefill_inst.py
- src/bench_cascade.cu
- src/bench_single_decode.cu
- src/bench_single_prefill.cu
- src/flashinfer_ops.cuh
- src/test_cascade.cu
- src/test_single_prefill.cu
- src/tvm_wrapper.cu
We don't need to separate between `tmp_v`/`o` and `tmp_s`/`lse` in kernel arguments
> refactor: simplify kernel interface

- include/flashinfer/utils.cuh
- python/csrc/single_prefill.cu
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- python/tests/test_tensor_cores_decode.py
The tensor-cores accelerated GQA in our [blog post](https://flashinfer.ai/2024/02/02/introduce-flashinfer.html) was not enabled by default (user need to use Prefill kernels/wrappers for decode to get such acceleration).
In this PR we add an option `use_tensor_cores` to decode operators/wrappers, and user can select whether to use `tensor_cores` for acceleration depending on use cases.
Not that our prefill kernels are compiled for all possible group sizes (#301 ), but decode kernels are not. So if user wants to use general group size, it's encouraged to set `use_tensor_cores=True`.
> feat: add `use_tensor_cores` option to decode kernels to accelerate GQA

- scripts/run-ci-build-wheel.sh
We met the following error when running the building scripts:
```
File "/tmp/home/.local/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 28, in <module>
from pkg_resources import packaging  # type: ignore[attr-defined]
ImportError: cannot import name 'packaging' from 'pkg_resources' (/tmp/home/.local/lib/python3.10/site-packages/pkg_resources/__init__.py)
```
Let's follow [this](https://stackoverflow.com/questions/78604018/importerror-cannot-import-name-packaging-from-pkg-resources-when-trying-to) and see whether it works or not.
> ci: fix setuptools version

- .github/workflows/release_wheel.yml
To fix the error: https://github.com/flashinfer-ai/flashinfer/actions/runs/9594555333/job/26475097423
> ci: use python3 for release wheel workflow

- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/attention/warp_layout.cuh
- include/flashinfer/page.cuh
- include/flashinfer/prefill_attention_decl.cuh
- include/flashinfer/utils.cuh
- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/flashinfer/decode.py
- python/generate_batch_paged_prefill_inst.py
- python/generate_batch_ragged_prefill_inst.py
- python/literal_map.py
- python/tests/test_batch_prefill_kernels.py
- python/tests/test_tensor_cores_decode.py
- src/flashinfer_ops.cuh
- src/test_page.cu
Duplicate of #304 and #185, just rebased on main.
This PR can accelerate GQA, we will release v0.0.6 after this PR gets merged (ETA: tonight).
> perf: use 1x4 warp layout for small query length

- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/attention/warp_layout.cuh
- python/generate_batch_paged_prefill_inst.py
- python/generate_batch_ragged_prefill_inst.py
Disable #322 for v0.0.6 release because binary size is too large.
v0.0.6 will only include bugfix at the moment.
> fix: disable other warp layout because of large binary size

- include/flashinfer/attention/handler.cuh
when `128 / page == 0`, our binary search might run into division by zero issue.
> bugfix: fix the scheduler behavior of large batch size

- include/flashinfer/utils.cuh
For small query size setting, we might use large kv tile size.
> perf: more options for kv tile size

- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/logits_post_hook.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/decode_attention_decl.cuh
- include/flashinfer/prefill_attention_decl.cuh
- include/flashinfer/utils.cuh
- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/flashinfer_ops.h
- python/csrc/single_decode.cu
- python/csrc/single_prefill.cu
- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- python/generate_batch_padded_decode_inst.py
- python/generate_batch_paged_decode_inst.py
- python/generate_batch_paged_prefill_inst.py
- python/generate_batch_ragged_prefill_inst.py
- python/generate_single_decode_inst.py
- python/generate_single_prefill_inst.py
- python/literal_map.py
- python/tests/test_logits_cap.py
- src/flashinfer_ops.cuh
This PR supports customized logits soft cap values. Different models might use different logits soft cap values (e.g. Grok-1 uses 30 and Gemma-2 uses 50).
> feat: customize `logits_soft_cap` value

- CMakeLists.txt
This commit resolves a build-time error with the following message:
```
CMake Error at 3rdparty/flashinfer/CMakeLists.txt:313 (add_library):
No SOURCES given to target: prefill_kernels
```
This occurred after https://github.com/flashinfer-ai/flashinfer/pull/266, which replaces the `FLASHINFER_GEN_CASUALS` option with `FLASHINFER_GEN_MASK_MODES`. However, the definition of `flashinfer_option(FLASHINFER_GEN_CASUALS ... )` was not replaced.  As a result, loop over the empty `MASK_MODES` does not produce any kernels that should be compiled.
This commit updates the `flashinfer_option(FLASH_GEN_CASUALS ...)` line to instead define `FLASH_GEN_MASK_MODES`, using the same default value as `config.cmake`.
> [CMake][Bugfix] Set default value for FLASHINFER_GEN_MASK_MODES

- CHANGELOG.md
- include/flashinfer/attention/prefill.cuh
Also reduce binary size but limit the maximum number of registers for `x_frag` and `o_frag` to 200.
> ci: update CHANGELOG

- include/flashinfer/utils.cuh
- python/setup.py
Do not compile `NUM_FRAGS_Z=6` to reduce wheel size.
Also revert #341 as they don't make effect.
> ci: remove redundant `NUM_FRAGS_Z`

- include/flashinfer/mma.cuh
This doesn't change performance, just to make code simpler.
> refactor: use sink symbol instead of a placeholder register in row sum mma implementation

- include/flashinfer/attention/decode.cuh
logits soft cap should be applied before masking.
Thanks @LiuXiaoxuanPKU for spotting this bug.
> hotfix: fix the decode kernel with logits cap

- python/tests/test_batch_decode_kernels.py
- python/tests/test_batch_prefill_kernels.py
- python/tests/test_logits_cap.py
followup of #350 
add the case of `logits_soft_case=1.0` to correctness tests.
add batch decode/prefill tests.
> tests: add more unittests for logits cap

- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- src/test_batch_prefill.cu
The prefill kernels was buggy when some of the requests have empty kv-cache, this PR fixes the issue.
> bugfix: fix prefill/append kernel behavior for empty kv-cache.

- .github/workflows/release_please.yml
https://github.com/google-github-actions/release-please-action is deprecated, this PR replace it with the new action https://github.com/googleapis/release-please-action that is under maintenance.
> ci: update release please github action

- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/attention/warp_layout.cuh
- python/generate_batch_paged_prefill_inst.py
- python/generate_batch_ragged_prefill_inst.py
Changes:
1. Prefetch page indices (we have already done such optimization on decode kernels, but not on append/prefill kernels which was used in GQA).
2. Unlock 1x4 warp layout in https://github.com/flashinfer-ai/flashinfer/pull/322, we didn't enable this because the binary size is too large, we should further reduce some unnecessary template arguments.
3. Optimize `threadblock_sync_mdo_states` for efficient merging attention states of multiple warps in a threadblock. Our previous implementation assumes small shared memory size and interleaves shared memory reads/writes with computations, which is not as efficient as a bulk shared memory access.
After this PR, the GQA kernel execution time (on H100) for setting `batch_size=128, seq_len=1024, num_qo_heads=32, num_kv_heads=4, head_dim=128` …
> perf: accelerate gqa performance

- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/cascade.cu
- python/csrc/group_gemm.cu
- python/csrc/norm.cu
- python/csrc/page.cu
- python/csrc/quantization.cu
- python/csrc/sampling.cu
- python/csrc/single_decode.cu
- python/csrc/single_prefill.cu
This PR fixes #349  by using the default stream of input tensors' device instead of the default stream of default device (which might be different to input tensors' device). This PR also adds sanity check on input tensors device id (all input tensors must be on the same GPU).
> bugfix: check gpu id in PyTorch APIs and use input tensor's gpu default stream

- include/flashinfer/attention/handler.cuh
- python/tests/test_decode_prefill_lse.py
- python/tests/test_tensor_cores_decode.py
When some request has empty kv cache, the output of decode kernels doesn't align with prefill kernels. This PR fixes the issue.
Thanks @MasterJH5574 for reporting this bug.
> bugfix: fix decode kernels output for empty kv cache

- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
Small tweak to avoid unnecessary copying by combining `to` calls. Discovered during profiling.
> perf: Optimize tensor conversions in C++ code to avoid unnecessary copies

- include/flashinfer/attention/handler.cuh
The `begin_forward` function in decode attention wrappers sometimes triggers segfault, this PR fixes the issue.
> bugfix: fix the decode kernel segfault in cudagraph mode

- include/flashinfer/attention/cascade.cuh
- python/csrc/cascade.cu
- python/csrc/flashinfer_ops.h
- python/flashinfer/cascade.py
- python/tests/test_shared_prefix_kernels.py
This pushes down the conditional logic to the kernel, allowing for better CUDA graph support with variable sequence length. I didn't see much purpose in adding the `mask` parameter to the out of place merge state kernels.
> feat: Add mask to `merge_state_in_place`

- include/flashinfer/attention/cascade.cuh
- include/flashinfer/sampling.cuh
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/csrc/sampling.cu
- python/flashinfer/sampling.py
- python/tests/test_sampling.py
- python/tests/test_shared_prefix_kernels.py
Currently our sampling kernels only support either top-k or top-p sampling. However, these two sampling algorithms can be used together, this PR implements the sampling kernel that performs top-k and top-p sampling jointly.
> feat: Fused GPU sampling kernel for joint top-k & top-p sampling

- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/page.cuh
- src/cpu_reference.h
- src/test_batch_prefill.cu
In our previous design, k-cache and v-cache are coupled together as a `(num_pages, 2, page_size, num_heads, head_dim)` or a `(num_pages, 2, num_heads, page_size, head_dim)` tensor.
In this PR, we decouple the k-cache and v-cache storage to enable more flexible kv-cache storage. Note that the original coupled layout is still supported, but we also supports standalone k-cache and k-cache.
> refactor: decouple kv-cache storage

- include/flashinfer/attention/prefill.cuh
sm90+ can benefit from stmatrix in epilogue.
> perf: use stmatrix in epilogue for sm90+

- docs/api/python/cascade.rst
- docs/api/python/decode.rst
- docs/tutorials/kv_layout.rst
- include/flashinfer/page.cuh
- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/flashinfer_ops.h
- python/csrc/page.cu
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/page.py
- python/flashinfer/prefill.py
- python/flashinfer/sparse.py
- python/flashinfer/utils.py
- python/tests/test_batch_decode_kernels.py
- python/tests/test_batch_prefill_kernels.py
- python/tests/test_block_sparse.py
> feat: expose decoupled kv-cache to pytorch api

- include/flashinfer/attention/prefill.cuh
Related issue: https://github.com/vllm-project/vllm/issues/6395
> bugfix: Fix invalid kernel configuration for sm86

- include/flashinfer/sampling.cuh
As observed in #384 , we should use different variables for input and output for `FlagHeads` API in cu118.
> bugfix: fix sampling API's behavior on cu118

- src/bench_cascade.cu
- src/test_cascade.cu
Use c++17 style structure bindings instead of std::tie.
> refactor: use c++17 style structure bindings

- include/flashinfer/attention/cascade.cuh
- src/test_cascade.cu
When cudagraph is enabled, we will still call merge states kernels for short sequence length, which incurs some unnecessary overhead.
This PR accelerates merge states kernel when there is nothing to merge (`num_index_sets=1`).
We can actually write through to the target buffer for small sequence length, but I'm always lazy evaluated and I'll leave it for a future PR (if necessary).
> perf: slight optimization on merge states

- .github/workflows/release_wheel.yml
- Remove torch 2.1 (we will not support torch 2.1 from v0.1.2 on).
- Add pytorch 2.4
- Add cuda 12.4 (for torch 2.4+)
> ci: add torch 12.4 to the matrix configuration

- docs/api/python/rope.rst
- docs/index.rst
- include/flashinfer/pos_enc.cuh
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/csrc/rope.cu
- python/flashinfer/__init__.py
- python/flashinfer/rope.py
- python/setup.py
- python/tests/rope_reference.py
- python/tests/test_rope.py
- src/tvm_wrapper.cu
Reference implementation: https://github.com/meta-llama/llama-models/blob/709a61fd810157f75fbb314e7287089eec06d9c3/models/llama3_1/api/model.py#L41
This PR also expose the `BatchQKApplyRotaryInPlaceKernel` to pytorch APIs, previous they are only used in TVM wrappers.
> feat: add llama 3.1 style rope

- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/layout.cuh
- include/flashinfer/prefill_attention_decl.cuh
- python/csrc/batch_prefill.cu
- python/csrc/single_prefill.cu
- python/generate_batch_ragged_prefill_inst.py
- python/generate_single_prefill_inst.py
- python/tests/test_non_contiguous_prefill.py
- src/cpu_reference.h
- src/flashinfer_ops.cuh
This PR implements #311 , after this PR, we support packed qkv input without explictly convert make the input contiguous:
```python
packed_qkv = W_qkv(x) # (nnz, (num_qo_heads + 2 * num_kv_heads) * head_dim)
q = packed_qkv[..., : num_qo_heads * head_dim].reshape(-1, num_qo_heads, head_dim)
k = packed_qkv[..., num_qo_heads * head_dim: (num_qo_heads + num_kv_heads) * head_dim].reshape(-1, num_kv_heads, head_dim)
v = packed_qkv[..., (num_qo_heads + num_kv_heads) * head_dim:].reshape(-1, num_kv_heads, head_dim)
apply_rope_inplace(q, k, indptr, offsets)
ragged_prefill_wrapper.forward(q, k, v)
```
Before this PR, we need to make `q`/`k`/`v` contiguous before we launch the attention kernel, which incurs some overhead.
I observe slight (<1%) performance degration after this PR for non-packed …
> feat: support non-contiguous (packed) input for prefill kernels

- include/flashinfer/sampling.cuh
Related issue: https://github.com/sgl-project/sglang/issues/771
This PR fixes the usage of `FlagHeads` cub API in sampling kernels.
As [documented](https://nvidia.github.io/cccl/cub/api/classcub_1_1BlockDiscontinuity.html), the default FlagHeads api will always flag the first element, which is not expected when first element is not `true`.
> For thread0, item input[0] is always flagged.
This PR sets the `tile_predecessor_item` argument (to 0) which will be compared against input[0].
CUDA 12+ don't have this issue because we are using the new `SubtractLeft` API instead of  `FlagHeads`.
> bugfix: fix cu118 cub usage

- python/flashinfer/prefill.py
The computation of `fixed_batch_size` is not correct.
> bugfix: Fix cudagraph mode of BatchPrefillWithRaggedKVCacheWrapper

- include/flashinfer/allocator.h
- include/flashinfer/attention/handler.cuh
- include/flashinfer/group_gemm/wrapper.cuh
- python/csrc/batch_prefill.cu
This PR makes the following changes to the codebase:
1. make the allocators error information more informative, more specifically, we print the buffer name and requested buffer size in runtime errors for debugging.
2. add checks in prefill wrappers `begin_forward` functions to make sure `qo` and `kv` indptr array size matches.
These efforts are designed for avoiding issues such as #362 , which needs to be fixed on vllm side, but we should have more friendly debugging information for locating the potential bugs.
> misc: enhance allocator error info and add shape check for prefill begin forward functions

- include/flashinfer/sampling.cuh
- python/csrc/flashinfer_ops.h
- python/csrc/sampling.cu
- python/flashinfer/sampling.py
- src/bench_sampling.cu
- src/test_sampling.cu
- src/tvm_wrapper.cu
Our previous sampling kernels relies on cub's BlockScan, which is not deterministic as reported in https://github.com/NVIDIA/cub/issues/454.
This PR implements the deterministic BlockScan using Belloch scan algorithm, which is slower than cub but guarantees determinism.
> feat: deterministic sampling

- .github/workflows/release_wheel.yml
Per requested in https://github.com/sgl-project/sglang/issues/849, we should build python 3.12 wheels starting from the next version.
> ci/cd: add python 3.12

- include/flashinfer/norm.cuh
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/csrc/norm.cu
- python/flashinfer/__init__.py
- python/flashinfer/norm.py
- python/tests/test_norm.py
ref https://github.com/sgl-project/sglang/pull/907 cc @yzh119
> feat: support fused add rmsnorm

- include/flashinfer/sampling.cuh
1. use `sum_of_probs_gt_pivot` rather than `sum_of_probs_leq_pivot`
2. make sure pivot will not decrease during iterations.
> bugfix: Improve numerical stability of sampling kernels

- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/csrc/flashinfer_ops_decode.cu
- python/csrc/flashinfer_ops_decode.h
- python/csrc/flashinfer_ops_prefill.cu
- python/csrc/flashinfer_ops_prefill.h
- python/csrc/single_decode.cu
- python/csrc/single_prefill.cu
- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- python/setup.py
Breaks up the `_kernels` module into multiple modules to avoid issues caused by the file growing too large.
> refactor: Break up `_kernels` into multiple modules

- docs/api/python/sampling.rst
- include/flashinfer/sampling.cuh
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/csrc/sampling.cu
- python/flashinfer/sampling.py
- python/tests/test_sampling.py
This PR supports min_p sampling by adding `sampling.min_p_sampling_from_probs` API.
Ref: [Min P Sampling](https://arxiv.org/abs/2407.01082).
> sampling: support min_p sampling

- docs/api/python/sampling.rst
- include/flashinfer/sampling.cuh
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/csrc/sampling.cu
- python/flashinfer/__init__.py
- python/flashinfer/sampling.py
- python/tests/test_sampling.py
- src/bench_sampling.cu
- src/test_sampling.cu
- src/test_single_prefill.cu
1. implement the first top-k then top-p sampling to align with vllm and huggingface's behavior https://github.com/vllm-project/vllm/pull/7137#issuecomment-2275167700
2. add options of using a scalar/tensor for top-p/top-k thresholds for all sampling operators.
> feat: more sampling operator options

- include/flashinfer/activation.cuh
- python/csrc/activation.cu
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/flashinfer/__init__.py
- python/flashinfer/activation.py
- python/setup.py
- python/tests/test_activation.py
as titled
I implemented a simplified version based on FasterTransformers, and I am considering whether to use optimizations like [half2](https://github.com/NVIDIA/FasterTransformer/blob/main/src/fastertransformer/kernels/activation_kernels.cu), and whether to consider using CUTLASS's [LeftSiLUAndMul](https://github.com/NVIDIA/cutlass/blob/main/examples/45_dual_gemm/thread/left_silu_and_mul.h). Do you have any suggestions? Thanks. @yzh119
> feat: support fused silu mul

- include/flashinfer/vec_dtypes.cuh
`cvt.rn.f16x2.f8typex2` instructions are only available for sm90+, not 89+.
> hotfix: Only use hardware vector fp8 conversion instructions for sm90+

- include/flashinfer/activation.cuh
- python/csrc/activation.cu
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/flashinfer/__init__.py
- python/flashinfer/activation.py
- python/tests/test_activation.py
cc @yzh119 
```
pytest python/tests/test_activation.py
=================================================================== test session starts ===================================================================
platform linux -- Python 3.10.12, pytest-8.3.2, pluggy-1.5.0
rootdir: /flashinfer/python
plugins: anyio-4.2.0
collected 630 items
python/tests/test_activation.py ................................................................................................................... [ 18%]
................................................................................................................................................... [ 41%]
................................................................................................................................................... …
```
> feat: support fused gelu tanh mul

- .github/workflows/release_wheel.yml
- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- python/flashinfer/sparse.py
Move `partition_kv` flag from compile time to runtime.
This PR also fixes a minor issue that sparse module was broken in #428 .
> ci: further reduce binary size

- CMakeLists.txt
- cmake/config.cmake
- include/flashinfer/vec_dtypes.cuh
- src/test_fast_dequant.cu
hardware fp8->fp16 fast conversion instruction is not available for sm_80 & sm_89, which makes #420 slow for these architectures.
this pr uses marlin's fast fp8->fp16x4 conversion algorithm (copied from vllm project) to accelerate such cases.
Co-authored-by: Antoni Baum <antoni@anyscale.com>
Co-authored-by: Cody Yu <cody@anyscale.com>
> perf: faster fp8->fp16 dequantization for pre sm_90 arch

- include/flashinfer/attention/prefill.cuh
Thank @hnyls2002 for spotting this bug.
> bugfix: fix prefill kernels' lse result for empty kv-cache

- python/csrc/batch_prefill.cu
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/page.py
- python/flashinfer/prefill.py
Fix two small bugs:
1. “NHD” and "HND" used confusing
2. PagedPrefill use self._custom_mask_buf to judge whether is customized_mask, but uninitialized
Here is the code snippet to reproduce the 2nd bug:
```python
import torch
import flashinfer
device = torch.device("cuda:0")
num_heads = 32
num_qo_heads = num_heads
num_kv_heads = 32
head_dim = 128
page_size = 4
max_num_pages = 4
batch_size = 1
seq_len = 4
query = torch.randn(seq_len, num_heads, head_dim, dtype=torch.bfloat16, device=device)
packed_kv_cache = torch.randn(max_num_pages, 2, page_size, num_kv_heads, head_dim, dtype=torch.bfloat16, device=device)
ragged_key_cache = packed_kv_cache[:, 0].reshape(-1, num_kv_heads, head_dim)
ragged_value_cache = packed_kv_cache[:, 1].reshape(-1, num_kv_heads, head_dim)
attn_mask = torch.tensor([
[ …
```
> Fix PagedPrefill python api and some typos

- include/flashinfer/attention/handler.cuh
- python/csrc/activation.cu
- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/flashinfer_ops_decode.h
- python/csrc/flashinfer_ops_prefill.h
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- python/flashinfer/sparse.py
- python/setup.py
- src/bench_batch_decode.cu
- src/bench_batch_prefill.cu
- src/bench_cascade.cu
- src/flashinfer_ops.cuh
- src/test_batch_decode.cu
- src/test_batch_prefill.cu
- src/test_cascade.cu
- src/tvm_wrapper.cu
Before this PR, flashinfer coupled float and int buffers in a single workspace buffer, and different wrappers cannot share the same buffers.
This PR decouples float and int workspace buffer. The float workspace buffer (large) can be shared in multiple wrappers, and the int buffer (small) is unique for each wrapper.  This PR can save GPU memory when multiple wrappers are created (decode, prefill paged, prefill ragged) or cascade inference.
> feat: decouple float and int workspace buffer

- include/flashinfer/vec_dtypes.cuh
Followup of #439 , use `constexpr` in if conditions so that `BIAS_OFFSET` won't exceed 32 at compile time.
> bugfix: suppress warning #63-D: shift count is too large

- include/flashinfer/attention/prefill.cuh
cc @yzh119 @Ying1123 @Yard1 @comaniac
> fix: resolve cu121 compile wired issue

- include/flashinfer/mma.cuh
As reported by @esmeetu , the prefill/append attention kernel produce incorrect results on sm75. This PR fixes the issue.
We need another round of kernel configuration check before releasing the official sm75 wheel (e.g., the nthrs per block 1024 is too large for sm75, we should use smaller values such as 512/256), @zhyncs would you mind helping with this?
> bugfix: fix the prefill/append attention kernel accuracy issue on sm75

- include/flashinfer/sampling.cuh
- python/csrc/flashinfer_ops.h
- python/csrc/sampling.cu
- python/flashinfer/sampling.py
- python/tests/test_sampling.py
Add an option to check whether there are nan inputs.
This PR also removes all `eps` arguments in renorm kernels: previously we pre-set a eps constant to determine when to stop the binary search, however, this might not be accuracy when vocabulary size grows (e.g. >= 1e6 in llama3 where our eps might be set to 1e-5).
In this PR, we implement a loop variant which do not rely on any external eps, and it can help us address some of the issues such as https://github.com/vllm-project/vllm/pull/7137#issuecomment-2288371960 .
> misc: improve error handling of sampling kernels

- include/flashinfer/sampling.cuh
Remove unnecessary syncthreads.
Tests, compute sanitizer's memcheck and syncheck have passed.
> misc: less syncthreads in renorm kernels

- include/flashinfer/attention/cascade.cuh
As observed by @MasterJH5574 , there are cases where our `VariableLengthMergeStatesKernel` launches a lot of CTAs (>=10k) while most of the CTAs only work on small number of merges, this PR fixes the issue by using a persistent kernel.
There is still load imbalance issue, and I plan to resolve it inside scheduler. I'll leave it for later PRs.
> perf: use persistent kernel for merging attention states

- docs/api/python/cascade.rst
- docs/conf.py
- docs/tutorials/kv_layout.rst
- python/flashinfer/__init__.py
- python/flashinfer/cascade.py
- python/tests/test_shared_prefix_kernels.py
Our existing cascade inference APIs all assumes shared prefix kv-cache are standalone tensors which is not the case for real-world llm serving.
This PR adds a more general `MultiLevelCascadeAttentionWrapper` API which not only supports multi-level cascade inference, and the kv-cache of all levels are stored in the unified paged kv-cache, which can seamlessly integrate with existing LLM serving frameworks.
Tutorials, tests and examples are updated correspondingly.
The old `BatchDecodeWithSharedPrefixPagedKVCacheWrapper` and `BatchPrefillWithSharedPrefixPagedKVCacheWrapper` should be deprecated, starting from 0.2.0.
> feat: add `MultiLevelCascadeAttentionWrapper` API

- docs/api/python/cascade.rst
- docs/api/python/decode.rst
- docs/api/python/prefill.rst
- docs/api/python/sparse.rst
- docs/tutorials/kv_layout.rst
- python/flashinfer/prefill.py
- python/tests/test_batch_decode_kernels.py
- python/tests/test_batch_prefill_kernels.py
- python/tests/test_block_sparse.py
- python/tests/test_decode_fp8_calibration_scale.py
- python/tests/test_decode_prefill_lse.py
- python/tests/test_fp8_prefill.py
- python/tests/test_group_gemm.py
- python/tests/test_non_contiguous_prefill.py
- python/tests/test_shared_prefix_kernels.py
- python/tests/test_sliding_window.py
- python/tests/test_tensor_cores_decode.py
In the previous PR #466 we replace the old-style `begin_forward`/`end_forward`/`forward` APIs with the new `plan`/`run` APIs, but didn't update the unit tests accordingly (this is intentional because we want a commit that keeps unit tests that uses the old-style API to check backward compatibility).
This PR updates the unit tests with new APIs.
Some other changes:
- Remove old-style APIs from docstring.
- Fix some errors in docstring with new APIs.
> misc: use the new `plan`/`run` API for unittests

- .github/workflows/release_wheel.yml
- docs/installation.rst
- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/mma.cuh
- include/flashinfer/sampling.cuh
- include/flashinfer/utils.cuh
- python/csrc/pytorch_extension_utils.h
- python/setup.py
Some kernel configurations are not compatible with sm75, this pr fix these issues.
> bugfix: Fix sm75 kernel configuration

- include/flashinfer/attention/cascade.cuh
- include/flashinfer/norm.cuh
- include/flashinfer/utils.cuh
- include/flashinfer/vec_dtypes.cuh
For CUDA 11.8 and 12.1, functions such as `make_bfloat162` are not declared for `__CUDA_ARCH__ < 800`, and this PR fixes the issue.
> hotfix: Fix sm75 compilation issue for bf16 on cuda 11.8 & 12.1

- include/flashinfer/attention/prefill.cuh
- include/flashinfer/vec_dtypes.cuh
> hotfix: skip prefill kernels on sm75 for bf16

- include/flashinfer/norm.cuh
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/csrc/norm.cu
- python/flashinfer/__init__.py
- python/flashinfer/norm.py
- python/tests/test_norm.py
> feat: add gemma_rmsnorm and gemma_fused_add_rmsnorm

- include/flashinfer/bmm_fp8.cuh
torch 2.2 no member function `getCurrentCUDABlasLtHandle`
torch 2.3 and 2.4 works well
> fix: compatible with torch 2.2

- docs/api/python/sampling.rst
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/utils.cuh
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/csrc/sampling.cu
- python/flashinfer/__init__.py
- python/flashinfer/sampling.py
- python/tests/test_sampling.py
- `top_p_renorm_prob` -> `top_p_renorm_probs`
- `top_k_renorm_prob` -> `top_k_renorm_probs`
`top_p_renorm_prob` and `top_k_renorm_prob` are kept as alias for backward compatibility.
> misc: rename some functions

- python/flashinfer/cascade.py
Bugfix to #484, thanks @wzhao18 for spotting this error.
> bugfix: fix the python 3.8 type error

- python/flashinfer/gemm.py
- python/tests/test_bmm_fp8.py
fp8 scale per tensor
ref https://github.com/sgl-project/sglang/pull/1285
> fix: update bmm fp8 test

- include/flashinfer/group_gemm/wrapper.cuh
The current group-gemm configuration raises the following error on NVIDIA 3090 :
```shell
RuntimeError: cutlass group_gemm.initialize failed: Error Internal
``` 
Modify the stage of group-gemm to 4, reduce the size of dynamic smem, so that it can be called on GPUs like the 3090.
Additionally, I also did a simple comparison on the A800. Modifying the stage to 4 can still slightly improve the performance of group-gemm.
Refer to: https://github.com/NVIDIA/cutlass/blob/main/test/unit/gemm/device/gemm_grouped_sm80.cu
> feat: modify group-gemm stage number

- include/flashinfer/attention/decode.cuh
Hi, this is a minor fix, when bdz is greater than 1, there would be redundant store to gmem operations for some warps. We may also check 'if (tx == 0)' when storing lse value, but since bdx is 32 most of the time, I think that would be fine.
> fix: batch decode kernel redundant store output to gmem

- flashinfer-aot/setup.py
Previously non-sm90 cards incorrectly get compiled as sm90, due to the shallow copy of the compiler flags.
> fix: AOT compiler flags on non-sm90

- flashinfer-aot/generate_batch_paged_prefill_inst.py
- flashinfer-aot/generate_batch_ragged_prefill_inst.py
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/attention/scheduler.cuh
- include/flashinfer/utils.cuh
#518 adds 2x2 warp layout which cause some numerical error for query length between (16, 32].
This PR remove the 2x2 warp layout configuration. We might add it back after we figured out where the bug is.
cc @abcdabcd987
> bugfix: remove 2x2 warp layout introduced in #518

- include/flashinfer/attention/prefill_params.cuh
`get_mask_offset` was deprecated.
> misc: remove unused functions in prefill parameters

- docs/installation.rst
Now we support both AOT mode and JIT mode, which should be distinguished in documentation.
> doc: add documentation for installation in JIT/AOT mode

- include/flashinfer/page.cuh
- python/csrc/page.cu
We introduced a bug in #513 because we didn't consider non-contiguous kv-cache for page append operator, this PR fix the bug.
> bugfix: fix the stride bug in page append

- python/flashinfer/decode.py
- python/flashinfer/prefill.py
The FlashInfer kernel [here](https://github.com/flashinfer-ai/flashinfer/blob/main/python/flashinfer/jit/batch_prefill_templ.py#L52C15-L53) does:
```
qo_indptr = qo_indptr.to(torch::kCPU);
kv_indptr = kv_indptr.to(torch::kCPU);
```
which is a blocking device synchronization for the CPU worker. We would like to avoid this for certain optimizations.
Accordingly, this PR schedules the device transfer ahead of time in the python code before the kernel to avoid blocking the CPU worker.
> Prefetch device transfer for ptrs to CPU

- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- python/flashinfer/utils.py
The qkv data type in `run` function must match with the q/kv data type specified in `plan` functions, otherwise the plan function might produce wrong schedules.
> bugfix: check whether the qkv data type matches in plan and run functions

- include/flashinfer/attention/cascade.cuh
- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/prefill.cuh
- tests/test_jit_example.py
1. use `generate_module` function
2. fix the correctness issue with flashsigmoid (when `use_softmax` is `false`, use attention sum instead of merge states for attention composition).
> jit: simplify jit example

- python/flashinfer/decode.py
This PR fixes the following error:
```
File "/home/yuxianq/flashinfer/python/flashinfer/decode.py", line 616, in plan
self._cached_module = get_batch_decode_module(
File "/home/yuxianq/flashinfer/python/flashinfer/decode.py", line 114, in get_batch_decode_module
_batch_decode_modules[args] = compile_batch_decode_module(*args)
File "/home/yuxianq/flashinfer/python/flashinfer/decode.py", line 65, in compile_batch_decode_module
uri, path = gen_batch_decode_cu(*args),
ValueError: not enough values to unpack (expected 2, got 1)
```
> Fix the "not enough values to unpack" error.

- python/flashinfer/decode.py
- python/flashinfer/jit/attention.py
We recently changed the plan function signature and remove the `data_type` argument, which is not compatible with some old version.
This PR keeps the `data_type` (but mark it as deprecated in documentation) for backward compatibility.
Also fix a bug in `gen_single_decode_cu` function (return uri instead of filename).
> bugfix: backward compatibility

- python/flashinfer/decode.py
The arguments have wrong order.
> bugfix: fix jit compilation for single decode with tensor cores

- python/flashinfer/jit/__init__.py
Python 3.12 raises `SyntaxWarning` for invalid escape sequence like `"\d"`.
This PR: Use raw strings for the regex and also add a capture group.
```pycon
Python 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> cuda_arch_flags = '-gencode=arch=compute_90,code=compute_90'
>>> int(re.search("compute_\d+", cuda_arch_flags).group()[-2:])
<stdin>:1: SyntaxWarning: invalid escape sequence '\d'
90
>>> int(re.search(r"compute_(\d+)", cuda_arch_flags).group(1))
90
```
> fix SyntaxWarning

- python/flashinfer/norm.py
- python/flashinfer/utils.py
- tests/conftest.py
Add torch custom_op (aka, torch library, torch.compile) support for `norm.py`. It should be a no-op for PyTorch < 2.4.
Testing is done by `torch.compile` -- as we expect the custom_op marks can isolate out our kernels during torch.compile. To avoid changes to tests, I introduced some magic that replaces the kernels with a `torch.compile`-ed version. For example, to run with/without torch.compile:
```bash
FLASHINFER_TEST_TORCH_COMPILE=1 pytest -svx tests/test_norm.py
pytest -svx tests/test_norm.py
```
If this PR looks good, I'll add it to more kernels.
> torch custom_op support: norm

- flashinfer-aot/csrc_aot/batch_decode.cu
- flashinfer-aot/csrc_aot/batch_prefill.cu
- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/decode_params.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/attention/prefill_params.cuh
- python/flashinfer/jit/batch_decode_templ.py
- python/flashinfer/jit/batch_prefill_templ.py
- tests/test_non_contiguous_decode.py
- tests/test_non_contiguous_prefill.py
Previously, only ragged version of prefill kernel supported non-contiguous query tensor (#404). But with paged kv cache, you have to make query tensor contiguous. Libraries like vLLM or SGLang must make query tensor contiguous before calling flashinfer kernels ([vLLM call of flashinfer](https://github.com/vllm-project/vllm/blob/b7df53cd42f3eab007b4f287c151960858e949df/vllm/attention/backends/flashinfer.py#L839), [SGLang call of flashinfer](https://github.com/sgl-project/sglang/blob/87a7cfa080cec3f123618c1429b5f998bf5d99cb/python/sglang/srt/layers/attention/flashinfer_backend.py#L236)). This PR solves it, ensuring that prefill/decode kernels with paged kv cache support non-contiguous query tensor.
1. Add strides of query tensor in `BatchPrefillPagedParams` and `BatchDecodeParams`.
2. Set …
> feat: non-contiguous query with paged kv cache

- python/flashinfer/sparse.py
The block sparse attention unittests failed as noted in #554, this PR fixes the issue.
> bugfix: fix block sparse wrappers

- flashinfer-aot/csrc_aot/batch_decode.cu
- flashinfer-aot/csrc_aot/flashinfer_ops_decode.cu
- flashinfer-aot/csrc_aot/flashinfer_ops_prefill.cu
- flashinfer-aot/csrc_aot/single_prefill.cu
- python/csrc/flashinfer_sampling_ops.cu
- python/csrc/sampling.cu
- python/flashinfer/activation.py
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/gemm.py
- python/flashinfer/jit/batch_decode_templ.py
- python/flashinfer/jit/batch_prefill_templ.py
- python/flashinfer/jit/single_prefill_templ.py
- python/flashinfer/page.py
- python/flashinfer/prefill.py
- python/flashinfer/quantization.py
- python/flashinfer/rope.py
- python/flashinfer/sampling.py
- tests/conftest.py
- tests/test_batch_decode_kernels.py
- tests/test_batch_prefill_kernels.py
- tests/test_block_sparse.py
- tests/test_page.py
- tests/test_quantization.py
Follow up of #552. This PR adds torch library annotation to all FlashInfer kernels so that torch.compile can recognize the kernels. Most changes are tedious.
I manually ran subsets of pytest test cases when I made these changes, but since there are too many of them and also some of them didn't pass even before I made the change, I cannot guarantee it's all working. To run tests with torch.compile, pass `FLASHINFER_TEST_TORCH_COMPILE=1` env.
```bash
FLASHINFER_TEST_TORCH_COMPILE=1 pytest -svx tests/test_norm.py
pytest -svx tests/test_norm.py
```
Notable changes:
* For the prefill and decode pybind, it used to return `Union[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]` depending on `return_lse`. This causes trouble for `torch.compile`. I changed the pybind interface to accept a …
> feat: torch.compile and custom_op support

- python/flashinfer/__init__.py
- python/flashinfer/activation.py
- python/flashinfer/jit/__init__.py
- python/flashinfer/prefill.py
- python/flashinfer/triton/cascade.py
- python/flashinfer/triton/kernels/cascade.py
1. Make mypy happy
2. Adopt the `from .x import y as y` idiom of re-exporting things in `__init__.py`. See [PEP 484](https://peps.python.org/pep-0484/#stub-files)
```
$ cd python/
$ mypy flashinfer/
Success: no issues found in 27 source files
```
> misc: typing improvement

- include/flashinfer/utils.cuh
Llama 3.2 3B comes with 24 qo heads and 8 kv heads.
> Add group size 3 to GQA dispatch

- python/flashinfer/sparse.py
When operational intensity is low, select cuda-core implementations for block-sparse attention.
> perf: use cuda-core implemention for io-bound block-sparse attention

- python/flashinfer/sparse.py
The contiguous operation is no longer required after #513
> perf: remove unnecessary contiguous operation in block sparse attention

- flashinfer-aot/csrc_aot/flashinfer_ops.cu
- python/flashinfer/quantization.py
- python/flashinfer/utils.py
Fix bugs introduced in #554 
1. Function signature change for `chain_speculative_sampling()` pybind in aot.
2. `packbits()` uses a str default value, which is not supported by PyTorch 2.4. This PR added a workaround.
3. For Pytorch < 2.4, the two decorators (`register_custom_op()` and `register_fake_op()`) should return identity function instead of `None`.
> bugfix for torch library annotation

- include/flashinfer/attention/prefill.cuh
The iteration bound for sliding window in batch prefill kernels is wrong, this PR fixes the issue.
Note that this bug do not influence kernel accuracy, but might harm kernel performance under some circumstance.
> bugfix: fix the sliding window iteration bound for SWA in batch prefill operators

- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- python/flashinfer/sparse.py
If we use async GPU to CPU copy in `plan` functions, we synchronize before we use the cpu array.
Since we have removed synchronization in plan functions, the GPU to CPU copy should be synchronized.
For flashinfer v0.2, it's encouraged to pass cpu indptr arrays to `plan` functions, and the synchronized GPU to CPU copy will be a no-op in this case.
> bugfix: do not use non-blocking copy for gpu to cpu transfer

- python/flashinfer/jit/env.py
In my development setup, I have different machines with different GPUs. They share the home directory on a network filesystem. When I switch between machines, since the JIT compilation flags change, I'll have to recompile kernels every time.
One solution is to specify the same `TORCH_CUDA_ARCH_LIST` every time. However, I keep forgetting that.
Another solution, as proposed in this PR, is to put different arch list in different cache directory.
> Change workspace dir

- flashinfer-aot/csrc_aot/flashinfer_ops.cu
- include/flashinfer/pos_enc.cuh
- python/csrc/flashinfer_rope_ops.cu
- python/csrc/rope.cu
- python/flashinfer/__init__.py
- python/flashinfer/rope.py
- tests/test_rope.py
Previously our rope apis assume the position indices of each request is contiguous, which is not appropriate for applications such as speculative decoding, this PR fixes the issue by supporting the huggingface transformer-style API which use `pos_ids` argument to specify positions.
This PR implements parts of the feature of #530 , other requests are coming in later PRs.
cc @dreaming-panda @abcdabcd987 @byronhsu
> feat: support huggingface transformer style rope interface

- src/flashinfer_ops.cuh
Hi, when I try to rebase my current work, just found cpp integration (benchmark and test) failed to build, this is introduced by the feature #553. 
Tests have been passed.
> fix broken cpp integration caused by #553

- CMakeLists.txt
- python/_aot_build_utils/generate_batch_paged_decode_inst.py
- python/_aot_build_utils/generate_batch_paged_prefill_inst.py
- python/_aot_build_utils/generate_batch_ragged_prefill_inst.py
- python/_aot_build_utils/generate_dispatch_inc.py
- python/_aot_build_utils/generate_single_decode_inst.py
- python/_aot_build_utils/generate_single_prefill_inst.py
Hi, cpp integration was broken again by #567, please be aware that there are cpp test, cpp benchmark and also tvm integration, they all relay on cmake build.
> fix broken cpp integration caused by #567

- docs/Makefile
- python/flashinfer/prefill.py
- python/flashinfer/utils.py
Here's the reason why docs fail to build after #552: As specified in `conf.py`, Sphinx mocks `torch`. The mock makes the following predicate behave badly: `TorchVersion(torch_version) < TorchVersion("2.4")`.
The fix is to explicitly pass in an env var indicating docs building.
Also changing the way that `prefill.py` imports compiled `_kernels` so that it's consistent with other files.
> Fix Sphinx

- python/flashinfer/decode.py
- python/flashinfer/prefill.py
Make mypy and pylance happy.
For example, here's screenshots of vscode viewing `test_batch_decode_kernels.py`.
return_lse=False:
return_lse=True:
> return type overload for return_lse

- python/flashinfer/jit/env.py
When GPU is not available (e.g., `CUDA_VISIBLE_DEVICES=-1`), `_get_cuda_arch_flags()` raises IndexError.
```
/opt/venv/lib/python3.10/site-packages/flashinfer/__init__.py:17: in <module>
from .activation import (
/opt/venv/lib/python3.10/site-packages/flashinfer/activation.py:21: in <module>
from .jit import (
/opt/venv/lib/python3.10/site-packages/flashinfer/jit/__init__.py:27: in <module>
from .activation import (
/opt/venv/lib/python3.10/site-packages/flashinfer/jit/activation.py:19: in <module>
from .env import FLASHINFER_GEN_SRC_DIR
/opt/venv/lib/python3.10/site-packages/flashinfer/jit/env.py:31: in <module>
FLASHINFER_WORKSPACE_DIR = _get_workspace_dir_name()
/opt/venv/lib/python3.10/site-packages/flashinfer/jit/env.py:24: in _get_workspace_dir_name
flags = _get_cuda_arch_flags() …
```
> bugfix: workspace dir when no GPU is available

- python/setup.py
My last minute change in #567 changed `link_data_files()` to a context manager. I didn't properly test it. It would fail due to `this_dir / "flashinfer" / "data" / "version.txt"` not exist.
This PR fixes the issue. I tested that it works, with `pip install -v -e .`.
BTW, AOT wheel does not have this issue. I'm able to build AOT wheel.
> bugfix: symlinks not set up properly in setup.py

- benchmarks/bench_append_paged_kv_cache.py
Add a python benchmark for `append_paged_kv_cache`. Currently, its performance is really bad for prefill.
For example, here's the result on H100:
```
model: l1b      seqlens: [1, 1, 1, 1, 1, 1, 1, 1]                 single_layer: 0.011ms all_layers:   0.173ms throughput:    3.035GB/s
model: l1b      seqlens: [4993, 1, 1, 1, 1, 1, 1, 1]              single_layer: 2.363ms all_layers:  37.807ms throughput:    8.667GB/s
model: l1b      seqlens: [5000]                                   single_layer: 2.346ms all_layers:  37.529ms throughput:    8.731GB/s
model: l1b      seqlens: [625, 625, 625, 625, 625, 625, 625, 625] single_layer: 0.301ms all_layers:   4.819ms throughput:   68.005GB/s
---
model: l3b      seqlens: [1, 1, 1, 1, 1, 1, 1, 1]                 single_layer: 0.009ms all_layers: …
```
> add benchmark for append_paged_kv_cache

- include/flashinfer/pos_enc.cuh
Hi, now tvm wrapper build failed cause by #568.
I noticed that the new `BatchQKApplyRotary` interface removed `__restrict__` modifier from `DType* q, DType* k, DType* q_rope, DType* k_rope`, so it's trivial to just add one adapter function to fix this issue.
> fix broken tvm integration caused by #568

- python/flashinfer/cascade.py
- python/flashinfer/prefill.py
- tests/test_shared_prefix_kernels.py
This PR add support for CUDAGraph compatibility for `MultiLevelCascadeAttentionWrapper`.
cc @raywanb @pavanimajety @comaniac
> feat: CUDAGraph compatibility of multi-level cascade inference APIs

- include/flashinfer/gemm/group_gemm_sm90.cuh
The pre-commit hook (#584) re-ordered the headers. It causes `group_gemm_sm90.cuh` not able to compile. This PR add a clang-format section to preserve the include order.
Related: https://github.com/NVIDIA/cutlass/issues/1827
> bugfix: gemm_sm90 compilation error

- benchmarks/bench_append_paged_kv_cache.py
- include/flashinfer/page.cuh
- python/csrc/flashinfer_page_ops.cu
- python/csrc/page.cu
- python/csrc_aot/flashinfer_ops.cu
- python/flashinfer/__init__.py
- python/flashinfer/page.py
- src/test_page.cu
- tests/test_page.py
The performance of `append_paged_kv_cache` is terrible for small batch size, which is a known issue that we haven't fixed for a long time, this PR fixes it. This PR also adds support for non-contiguous append keys/values (which could be sliced from fused qkv matrix).
We first call a triton kernel to convert `append_indptr` to `batch_indices` and `positions` (which is similar to [CSR2COO conversion](https://docs.nvidia.com/cuda/cusparse/#cusparse-t-csr2coo) in sparse matrix). After the conversion, we can use element parallelism instead of batch parallelism.
It's also worth trying using triton for the second `AppendPagedKVCacheKernel` kernel, I think the performance should be fine. I'll leave it for future work.
Some todo items:
1. add torch.compile support.
After this PR (reference number …
> perf: fix the performance issue of `append_paged_kv_cache`

- benchmarks/bench_append_paged_kv_cache.py
```
model: l1b      seqlens: [1, 1, 1, 1, 1, 1, 1, 1]                 convert: 45us 1layer:  7us 16layers: 151us throughput:    4.936GB/s
model: l1b      seqlens: [4993, 1, 1, 1, 1, 1, 1, 1]              convert: 42us 1layer: 14us 16layers: 271us throughput: 1434.769GB/s
model: l1b      seqlens: [5000]                                   convert: 44us 1layer: 14us 16layers: 272us throughput: 1438.581GB/s
model: l1b      seqlens: [625, 625, 625, 625, 625, 625, 625, 625] convert: 46us 1layer: 14us 16layers: 274us throughput: 1440.357GB/s
---
model: l3b      seqlens: [1, 1, 1, 1, 1, 1, 1, 1]                 convert: 42us 1layer:  7us 28layers: 226us throughput:    9.946GB/s
model: l3b      seqlens: [4993, 1, 1, 1, 1, 1, 1, 1]              convert: 43us 1layer: 22us 28layers: 647us throughput: …
```
> include convert latency in bench_append_paged_kv_cache

- include/flashinfer/norm.cuh
- tests/test_norm.py
When `sizeof(T) == 2`, the sum of the read `input` and `residual` (float `x`) is split into two parts, high and low 16 bits, and saved to `input` and `residual` respectively. Later, `input` and `residual` are read out and combined to `x`, with the aim of improving the precision of the subsequent `x * rms_rcp` operation.
Increase precision from 1e-2 to 1e-3.
> Improve the precision of the FusedAddRMSNormKernel function

- python/flashinfer/page.py
The type is adjusted to be consistent with the prefill/decode wrappers.
> Fix the type of `paged_kv_cache` in append

- python/flashinfer/page.py
> hotfix: fix import issue in #597

- benchmarks/bench_fused_add_rmsnorm.py
- include/flashinfer/norm.cuh
Use `vec_t<float, VEC_SIZE> x_vec` to reduce the number of read and write operations to shared memory.
> minor: reduce the read and write of shared memory in the FusedAddRMSNormKernel

- benchmarks/bench_rope.py
- include/flashinfer/cutlass_utils.cuh
- include/flashinfer/pos_enc.cuh
- python/csrc/flashinfer_rope_ops.cu
- python/csrc/rope.cu
- python/csrc_aot/flashinfer_ops.cu
- python/flashinfer/rope.py
- tests/test_rope.py
This PR implements the final piece of #530 , so that we can partially apply rotary embedding to first head dimensions instead of entire head dimensions.
We also add a simple benchmark for RoPE, below is the result on H100:
```python
batch_size:   1, append_len:     1, num_qo_heads:    32, num_kv_heads:     8, head_dim:   128, use_cos_sin_cache: False, latency: 23us, throughput:   0.876GB/s
batch_size:   1, append_len:     1, num_qo_heads:    32, num_kv_heads:     8, head_dim:   128, use_cos_sin_cache: True, latency: 26us, throughput:   0.801GB/s
batch_size:   1, append_len:   128, num_qo_heads:    32, num_kv_heads:     8, head_dim:   128, use_cos_sin_cache: False, latency: 27us, throughput:  95.735GB/s
batch_size:   1, append_len:   128, num_qo_heads:    32, num_kv_heads:     8, head_dim: …
```
> feat: add `rotary_dim` argument to rope APIs for partial apply rope

- src/tvm_wrapper.cu
The TVM wrapper was broken in #599 because of API changes, this PR fixes the issue.
> hotfix: fix rope tvm wrapper

- docs/api/python/activation.rst
- docs/api/python/norm.rst
- docs/api/python/page.rst
- docs/api/python/rope.rst
- docs/index.rst
- python/flashinfer/activation.py
- python/flashinfer/norm.py
- python/flashinfer/page.py
Lots of APIs are missing from the documentation, this PR fixes the index.
> doc: update documentation index

- python/flashinfer/decode.py
- python/flashinfer/jit/attention.py
- python/flashinfer/jit/batch_prefill_templ.py
- python/flashinfer/jit/single_prefill_templ.py
- python/flashinfer/prefill.py
- python/flashinfer/sparse.py
- tests/test_batch_decode_kernels.py
- tests/test_batch_prefill_kernels.py
- tests/test_fp8_prefill.py
- tests/test_jit_example.py
Compile all three mask modes (causal/non-causal/custom) altogether instead of compiling them one-by-one.
> feat: simplify prefill JIT compilation

- include/flashinfer/attention/prefill.cuh
Since `o_frag` was not always aligned to a 16-byte boundary, `memcpy` implemented using 4x float moves was crashing in `cuda-gdb` when compiled with `-G`.
> Fix the alignment of o_frag

- include/flashinfer/pos_enc.cuh
The previous kernel was not parallelised sufficiently well for low batch sizes. Similarly to the regular rotary kernel, now all qo/kv heads are split across separate blocks.
In decode mode, the pos_ids kernel is now faster.
> Improve parallelism in RoPE with pos_ids

- python/flashinfer/jit/__init__.py
When running with multi-process, multiple processes may enter the if branch and the latter one cannot mkdir successfully. Adding such flag to it is enough to solve the issue.
> Fix potential multi-process compile issue

- python/csrc_aot/batch_decode.cu
- python/csrc_aot/batch_prefill.cu
- python/csrc_aot/single_decode.cu
- python/csrc_aot/single_prefill.cu
There are some compile errors in the main branch, like
```
/app/python/csrc_aot/single_prefill.cu(59): error: namespace "at::cuda" has no member "OptionalCUDAGuard"
const at::cuda::OptionalCUDAGuard device_guard(device_of(device));
^
/app/python/csrc_aot/single_prefill.cu(59): error: identifier "device_of" is undefined
const at::cuda::OptionalCUDAGuard device_guard(device_of(device));
```
cc @yzh119
> Fix compile error of OptionalCUDAGuard and device_of

- include/flashinfer/pos_enc.cuh
As observed by @james-p-xu, #609 produce wrong results for some input shapes, this PR fixes the correctness issue, and add optimizations of dispatching to different parallelism modes for different input shapes.
For large shape inputs, using the original implementation (re-use sin/cos for different heads) will be better.
For small shape inputs, using head parallelism will be better.
Some results:
```
Before #609 (no head-parallelism, re-use sin/cos value)
-----------------
batch_size:   1, append_len:     1, num_qo_heads:    32, num_kv_heads:     8, head_dim:   128, use_cos_sin_cache: False, latency: 27us, throughput:   0.762GB/s
batch_size:   1, append_len:     1, num_qo_heads:    32, num_kv_heads:     8, head_dim:   128, use_cos_sin_cache: True, latency: 22us, throughput:   0.919GB/s …
```
> bugfix: fix the rope correctness issue introduced in #609

- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- python/flashinfer/sparse.py
- tests/test_batch_decode_kernels.py
Use non-blocking memcpy only in plan functions when this option is turned on.
> feat: add an option `non_blocking` to plan function

- python/csrc/flashinfer_ops.cu
#618 breaks aot compilation because of function signature mismatch, this PR fixes the issue.
> hotfix: fix aot compilation after #618

- python/aot_setup.py
mask is no longer part of uris, this PR fixes the issue, otherwise our aot wheels will still trigger JIT compilation for prefill kernels.
> bugfix: fix prefill kernel uris for aot compilation

- python/aot_setup.py
- python/csrc/renorm.cu
- python/csrc/sampling.cu
- python/flashinfer/jit/__init__.py
- python/flashinfer/jit/batch_prefill_templ.py
- python/flashinfer/jit/core.py
- python/flashinfer/jit/utils.py
- python/flashinfer/sampling.py
- tests/test_jit_warmup.py
This PR accelerates JIT compilation by:
- Add a `parallel_load_modules` function to load necessary modules for a model in parallel using python multi-threading.
- Splitting sampling.cu into renorm.cu and sampling.cu
The batch prefill attention template could be further split into multiple instances to accelerate compilation, we leave that for future work.
> jit: further accelerate compilation by spliting files and multi-threading

- include/flashinfer/attention/cascade.cuh
- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/prefill.cuh
- src/test_cascade.cu
The cascade kernels can take a dynamic sequence length in order to allow the number of tokens to vary when executed under CUDA graphs.
This is the first step towards implementing CUDA graph support for arbitrary `qo_indptr` contents, as tracked by #626.
> Allow the cascade kernels to be executed using varying sequence lenghts

- python/flashinfer/jit/activation.py
- python/flashinfer/jit/attention.py
- python/flashinfer/jit/core.py
- python/flashinfer/jit/utils.py
- tests/jit_utils.py
- tests/test_alibi.py
- tests/test_batch_decode_kernels.py
- tests/test_batch_prefill_kernels.py
- tests/test_block_sparse.py
- tests/test_jit_warmup.py
- tests/test_logits_cap.py
- tests/test_non_contiguous_decode.py
- tests/test_non_contiguous_prefill.py
- tests/test_shared_prefix_kernels.py
- tests/test_sliding_window.py
- tests/test_tensor_cores_decode.py
Currently unittests are slow when using flashinfer jit because we only compile kernels the first time we run it, it's blocking and didn't compile multiple ops in parallel. This PR add a warmup pre-hook to kernel unittests, so that we compile all necessary kernels before running the unittests in JIT mode, which greatly accelerate the unittests.
This PR also fixes the several issues with #628 :
1. using thread-safe `make_dirs(..., exist_ok=True)` instead of relying on `os.path.exists`
2. change the signature of `parallel_load_modules` to lists of `(jit_module_creation_func, args)` instead of lambda function, because lambda function captures variable by ref instead of value, which may cause some unexpected errors.
> feat: warmup for jit kernel tests

- tests/test_shared_prefix_kernels.py
In #629 , page ops are missing in shared-prefix kernel unittest's warmup function
> misc: add page ops to shared-prefix kernel unittest warmup function

- include/flashinfer/norm.cuh
- tests/test_norm.py
gemma-style rmsnorm kernels (introduced in #477 ) are similar to original rmsnorm kernel, and we should use the same kernel for them. This PR cleans up duplicate code and unifies the kernels for gemma-style and original rmsnorm kernels.
The precision improvements (https://github.com/flashinfer-ai/flashinfer/pull/587, https://github.com/flashinfer-ai/flashinfer/pull/592) are kept in this PR.
> misc: remove duplicate norm cuda kernels

- python/flashinfer/jit/batch_prefill_templ.py
- python/flashinfer/jit/single_prefill_templ.py
Followup of https://github.com/flashinfer-ai/flashinfer/pull/628, this PR splits prefill attention jit templates so that we compile different mask modes in different files.
JIT compilation time of a prefill kernels of a certain configuration (shape, dtype etc) could be reduced to 10 seconds after this PR.
> perf: speedup jit compilation of prefill attention kernels

- tests/test_sliding_window.py
The unittests of sliding window atteniton didn't pass because we forget to set `causal` in `plan` function. This PR fixes the issue.
> bugfix: fix sliding window attention tests of ragged attention api

- include/flashinfer/norm.cuh
- tests/test_norm.py
This PR fixes the issue #634, which is brought by #592 .
If we want to use 16-bytes vectorized read/write, we need to confirm the address is aligned to 16 bytes.
When `num_warps` is not a multiple of 4 (4*sizeof(float) = 16), the address of `smem + num_warps` might not align to 16 bytes.
We can fix this by shifting the start offset of vectorized read/write to `smem + ceil_div(num_warps, 4) * 4` to force the alignment.
cc @ovowei @Abatom
> bugfix: fix the misaligned address bug of norm kernels for certain shapes

- include/flashinfer/attention/prefill.cuh
- include/flashinfer/attention/prefill_params.cuh
- include/flashinfer/attention/scheduler.cuh
- python/csrc/batch_prefill.cu
- python/flashinfer/jit/batch_prefill_templ.py
- src/flashinfer_ops.cuh
Under CUDA graph, if the graph is built with a maximal token count, the actual number of tokens from `qo_indptr` is passed on to the cascade kernels.
> Pass a dynamic token count to the cascade kernels

- python/flashinfer/decode.py
A prior PR switched up the two arguments via a typo, without tests catching the problem.
> Fix the batch size/seq len args for the decode kernel with tensor cores

- include/flashinfer/attention/scheduler.cuh
- python/csrc/batch_prefill.cu
- python/csrc/flashinfer_ops.cu
- python/flashinfer/decode.py
- python/flashinfer/jit/batch_prefill_templ.py
- python/flashinfer/prefill.py
- src/bench_batch_decode.cu
- src/bench_batch_prefill.cu
- src/bench_cascade.cu
- src/flashinfer_ops.cuh
- src/test_batch_prefill.cu
- src/test_cascade.cu
The new_batch_size was not computed correctly for CUDA graph mode. Now we ensure it is in sync with the contents of the per-block indices. Also adjusted the computation of the KV chunk sizes for CUDA graph mode.
This PR also removes the `max_seq_len` parameter from kernels, as a reasonable upper bound from it can be derived from `total_num_rows`.
> Fix the batch size & kv indptr calculation

- include/flashinfer/norm.cuh
Fix smem_size in FusedAddRMSNorm which is missed in #636 
Fix issue #645
> fix smem_size in FusedAddRMSNorm which is missed in PR #636 

- include/flashinfer/gemm/group_gemm_sm90.cuh
- python/flashinfer/gemm.py
- python/flashinfer/utils.py
- tests/test_group_gemm.py
Add optional `backend` api at gemm initialization.
Usage:
```python
backend="sm90" 
segment_gemm = flashinfer.gemm.SegmentGEMMWrapper(workspace_buffer, backend) 
```
Supported values: `sm90`, `sm80`, `auto`;
Default: `auto`.
> feat: specify gemm backend

- python/flashinfer/decode.py
```
[rank0]:   File "/home/simonmo/.conda/envs/vllm/lib/python3.10/site-packages/flashinfer/decode.py", line 1408, in run
[rank0]:     out[0] *= v_scale
[rank0]: TypeError: 'tuple' object does not support item assignment
```
This is saying `out[0]` does not allow mutation.
> Fix MLA decode error having v_scale without return_lse

- flashinfer/cascade.py
As mentioned in https://github.com/flashinfer-ai/flashinfer/issues/653, there is a type annotation error in cascade.py because we use `list` which is builtin since python 3.9 (related PR https://github.com/flashinfer-ai/flashinfer/pull/486).
> bugfix: fix type annotation error in python3.8

- include/flashinfer/attention/scheduler.cuh
The previous upper bound forgot to multiply with `gqa_group_size`.
> [rose] Fix the computation of `total_num_tiles_q`

- tests/test_alibi.py
- tests/test_batch_decode_kernels.py
- tests/test_batch_prefill_kernels.py
- tests/test_block_sparse.py
- tests/test_logits_cap.py
- tests/test_non_contiguous_decode.py
- tests/test_non_contiguous_prefill.py
- tests/test_shared_prefix_kernels.py
- tests/test_sliding_window.py
- tests/test_tensor_cores_decode.py
The unittests in AOT mode failed since https://github.com/flashinfer-ai/flashinfer/pull/629 because we didn't use return instead of yield in warmup functions, this PR fixes the issue.
> bugfix: fix unittests not yield error in AOT mode

- flashinfer/jit/batch_prefill_templ.py
The batch prefill attention JIT template was broken in https://github.com/flashinfer-ai/flashinfer/pull/635 because we messed up some jinja syntax. This PR fixes the issue.
> bugfix: fix JIT compilation of batch prefill attention kernels

- docs/api/decode.rst
`BatchDecodeMlaWithPagedKVCacheWrapper` is not indexed.
> doc: expose MLA decode API to documentation

- cmake/config.cmake
The option name of normalization is not aligned in config.cmake (`FLASHINFER_NORMALIZATION`) and [CMakeLists.txt](https://github.com/flashinfer-ai/flashinfer/blob/2bc3214075391c175057302023c4bd99f64b2899/CMakeLists.txt#L44) (`FLASHINFER_NORM`), so it does not build the test and bench for norm. This PR changed the option name in config.cmake to `FLASHINFER_NORM` to align with the option name in CMakeLists.txt.
> [small] Fix norm option in config.cmake

- scripts/run-ci-build-wheel.sh
`FLASHINFER_ENABLE_SM90` is a bash script local variable. We need to either put an `export` before it or explicitly set the env var when running `python -m build`.
> ci: Pass FLASHINFER_ENABLE_SM90 to setup.py

- aot_build_utils/generate_batch_paged_prefill_sm90_inst.py
- aot_build_utils/generate_batch_ragged_prefill_sm90_inst.py
- csrc/aot_extension_utils.h
- csrc/batch_prefill_sm90.cu
- csrc/flashinfer_ops_sm90.cu
- csrc/pytorch_extension_utils.h
- flashinfer/jit/batch_prefill_sm90_templ.py
- flashinfer/prefill.py
- flashinfer/sparse.py
- include/flashinfer/attention/hopper/prefill_sm90.cuh
- include/flashinfer/attention/hopper/tile_scheduler.cuh
- include/flashinfer/attention/scheduler.cuh
- tests/test_hopper.py
The fa3 template's plan speed is very slow because we overestimate the workspace size that needs to be transferred from CPU to GPU, this PR fixes the issue.
cc @nandor @zhyncs
> hotfix: accelerate plan speed of fa3 template

- flashinfer/utils.py
wgmma is only available for cuda 12.3 or later, turn to use sm80 version when torch.cuda version is lower.
cc @xslingcn
> bugfix: only use sm90 group gemm when torch cuda >= 12.3

- aot_build_utils/generate_batch_paged_prefill_sm90_inst.py
- aot_build_utils/generate_batch_ragged_prefill_sm90_inst.py
- aot_build_utils/generate_single_prefill_sm90_inst.py
- benchmarks/bench_hopper_attention.py
- csrc/batch_prefill_sm90.cu
- csrc/single_prefill_sm90.cu
- flashinfer/jit/attention.py
- flashinfer/jit/batch_prefill_sm90_templ.py
- flashinfer/jit/single_prefill_sm90_templ.py
- flashinfer/prefill.py
- include/flashinfer/attention/hopper/attention_updater.cuh
- include/flashinfer/attention/hopper/kernel_traits.cuh
- include/flashinfer/attention/hopper/params.cuh
- include/flashinfer/attention/hopper/prefill_sm90.cuh
- include/flashinfer/attention/hopper/variants.cuh
- tests/test_jit_example.py
Added customizable SM90 prefill kernels.
AOT command:
```
MAX_JOBS=224 \
FLASHINFER_ENABLE_AOT=1 \
TORCH_CUDA_ARCH_LIST=9.0a \
pip install -e . \
--no-cache-dir --ignore-installed --verbose --force-reinstall
```
JIT command:
```
MAX_JOBS=224 \
FLASHINFER_ENABLE_AOT=0 \
TORCH_CUDA_ARCH_LIST=9.0a \
pip install -e . \
--no-cache-dir --ignore-installed --verbose --force-reinstall
```
After either command, you can make sure the SM90 kernels work by:
```
pytest -x tests/test_hopper.py
```
An example for a `customizable_sm90_prefill_kernel` has also been added to `tests/test_jit_example.py". You can follow that example to add custom kernels.
> Customizable SM90 prefill kernels.

- flashinfer/utils.py
We observe performance degradation for small operations in flashinfer v0.2 because of the overhead of `torch.library.custom_op` introduced in #554.
This PR disables torch custom operator registrations first, we can add them back with lightweight registration later: https://github.com/vllm-project/vllm/blob/36e76700453924c8d421db99af70a88a1df835cd/vllm/utils.py#L1660-L1674
cc @zhyncs @abcdabcd987 @youkaichao
> hotfix: revert torch.library register

- .github/workflows/release_wheel.yml
- scripts/run-ci-build-wheel.sh
- setup.py
- Fix release workflow for pytorch 2.5 wheel by dropping python 3.8.
- Relax pytorch version requirements.
- Right now, install flashinfer will downgrade existing pytorch versions since it's set the version requirement to exact match.
> Improve compatibility with pytorch 2.5

- README.md
This pull request includes an update to the `README.md` file to add a new citation section. The most important change is the addition of a citation format for users who find FlashInfer helpful in their projects or research.
Documentation update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R144-R169): Added a new "Citation" section with a BibTeX entry for citing the FlashInfer paper.
> misc: add bibtex reference

- include/flashinfer/attention/prefill.cuh
We forgot to divide the packed row index by group_size when computing the sliding window iteration bound, making it larger than its actual value, and slows down the execution.
Thank @Ying1123 for spotting this bug.
> perf: fix the iteration bound of SWA in FA2 prefill template

- csrc/flashinfer_ops.cu
#713 didn't update the function signature of min-p API in AOT pybind file, this PR fixes the issue.
> bugfix: fix min-p AOT compilation in #713

- include/flashinfer/norm.cuh
- tests/test_norm.py
The original implementation will cause RuntimeError: invalid argument when hidden_size=16384.
> bugfix: FusedAddRMSNorm kernels might require more than 48KB shared memory when d is large.

- flashinfer/utils.py
Some kernels use instructions specific to Hopper, which might not be compatible with future GPUs. Fallback to non-Hopper kernels for all the other GPUs.
> bugfix: Choose sm90 kernels only for Hopper GPUs.

- CMakeLists.txt
- aot_build_utils/generate.py
- aot_build_utils/generate_sm90.py
- cmake/config.cmake
- csrc/bmm_fp8.cu
- csrc/pytorch_extension_utils.h
- flashinfer/jit/core.py
- include/flashinfer/sampling.cuh
- setup.py
- src/test_batch_decode.cu
- src/test_batch_prefill.cu
- src/test_page.cu
- src/test_single_decode.cu
- src/test_single_prefill.cu
Flags can be used to disable fp16 and either of the fp8 variants in order to speed up AOT builds.
By default, the configuration remains unchanged and the `FLASHINFER_ENABLE_FP8` flag will enable both fp8 modes.
> Finer-grained control over fp16/fp8 builds

- include/flashinfer/attention/scheduler.cuh
Close #726. Alignes KV chunk size binary search with the real strategy so that the resulting `kv_chunk_size` would yield correct `new_batch_size`.
> Align KV chunk size binary search with actual KV chunk splitting.

- pyproject.toml
The name `flashinfer` is not available in PyPI and we haven't got response from PyPI team yet(https://github.com/pypi/support/issues/5355).
In this PR, we rename the package to `flashinfer-python`, it is approved, and we successfully uploaded a sdist of v0.2.0.post1 there:
https://pypi.org/project/flashinfer-python/0.2.0.post1/#history
> ci: rename python package name to `flashinfer-python`

- docs/tutorials/kv_layout.rst
Not sure the best place to put this, but this is where I was looking when i was experiencing the error in this [issue](https://github.com/flashinfer-ai/flashinfer/issues/725). 
Note might need to be removed if the library adds dispatch to kernels with idtype=int64, or type validation in the kernels.
> Add a note about int32/int64 datatypes to the `kv_layout` tutorial

- flashinfer/decode.py
- flashinfer/jit/core.py
- flashinfer/prefill.py
- flashinfer/sparse.py
Torch ops ban the input and output pointers from aliasing altogether, thus they cannot be sliced from the same allocation. Some use cases migth also wish to explicitly specify the output buffers, this is a step towards enabling that.
> Move allocations out of torch ops

- setup.py
Ran into compilation error when setting `FLASHINFER_HEAD_DIMS=64,128,192,256`. The cause is that `prefill_sm90.cuh` has static assertion only allowing head dim 64, 128, 256.
This PR updates setup.py to filter out unsupported head dims for sm90.
> Filter out unsupported head dim for sm90

- flashinfer/decode.py
- flashinfer/prefill.py
right now flashinfer does not specify the device when creating pin-memory tensor. it will cause error when users changed the default pytorch device.
we should explicitly set the device to be `"cpu"` for pin-memory tensor.
> fix pin memory device

- flashinfer/jit/__init__.py
This pull request includes changes to the `flashinfer/jit/__init__.py` file to improve the import structure and handle the `prebuilt_ops_uri` import conditionally.
Improvements to import structure:
* Removed the unconditional import of `prebuilt_ops_uri` from `aot_config` and added it conditionally within the try-except block to handle cases where `_kernels` or `_kernels_sm90` are not available. [[1]](diffhunk://#diff-39845bb8e1f81f9ca7d510e99dad0c15c7596ebe1ac909dc1b3c25b742700b5cL20) [[2]](diffhunk://#diff-39845bb8e1f81f9ca7d510e99dad0c15c7596ebe1ac909dc1b3c25b742700b5cR48-R52)
cc @ByronHsu
> hotfix: bugfix to #756

- csrc/flashinfer_gemm_sm90_ops.cu
- flashinfer/gemm.py
> fix: match statement not supported in Python 3.8

- include/flashinfer/attention/hopper/attention_updater.cuh
- include/flashinfer/attention/hopper/prefill_sm90.cuh
- include/flashinfer/attention/hopper/variants.cuh
- tests/test_jit_example.py
Per discussion with @happierpig , user should be able to construct attention updater in their own way (and parameters).
We change the JIT interface a little bit: let user define a `GetAttentionUpdater` function for attention updater construction, so that user can compute some values in the attention variant constructor and pass them to the constructor. One example is head-wise scale for fp8 attention, where user can pre-compute `qk_scale` in the attention variant constructor, then pass it to OnlineSoftmax (with scale) constructor.
> refactor: change the structure of attention updater

- include/flashinfer/sampling.cuh
This PR addresses issue #769.  
As discussed in [this comment](https://github.com/flashinfer-ai/flashinfer/issues/769#issuecomment-2629082639), the use of the approximate division instruction `div.approx.ftz.f32` can break the loop invariant, preventing the loop from terminating. To resolve this, this PR changes the data types of `low`, `high`, and `mid` to `double`, ensuring that the compiler maintains IEEE-754 compliance and preserves numerical stability.
> bugfix: Ensure Loop Termination by Enforcing IEEE-754 Compliance in Sampling Kernels

- scripts/update_whl_index.py
Fixed the index for existing wheels in [another commit](https://github.com/flashinfer-ai/whl/commit/d252b0822343a09e026cefac14fe427ac0b9bc45). This PR fixes future releases.
> ci: change whl folder to flashinfer-python

- aot_build_utils/generate.py
- aot_build_utils/generate_dispatch_inc.py
- aot_build_utils/generate_sm90.py
- csrc/aot_extension_utils.h
- csrc/batch_prefill_sm90_config.inc
- csrc/pytorch_extension_utils.h
- csrc/single_prefill_sm90_config.inc
- setup.py
#765 introduces hacks to support DeepSeek head dims, but AOT is broken. This PR adds dispatch on the pair of QK and VO head dim.
It fixes the problem of missing symbols.
```
$ python -c "from flashinfer import _kernels_sm90"
Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: python3.10/site-packages/flashinfer/_kernels_sm90.cpython-310-x86_64-linux-gnu.so: undefined symbol: ...
$ c++filt _ZN10flashinfer34SinglePrefillWithKVCacheDispatchedILj192ELj192ELNS_8MaskModeE1ELb1ENS_13LogitsSoftCapENS_19SinglePrefillParamsIN7cutlass6half_tES5_S5_iEEEE9cudaErrorRT4_P11CUstream_st
cudaError flashinfer::SinglePrefillWithKVCacheDispatched<192u, 192u, (flashinfer::MaskMode)1, true, flashinfer::LogitsSoftCap, flashinfer::SinglePrefillParams<cutlass::half_t, …
```
> feat: Separate QK/VO head dim dispatch for sm90 AOT

- tests/test_batch_prefill_kernels.py
This pull request includes a small change to the `tests/test_batch_prefill_kernels.py` file. The change modifies the `custom_mask` parameter in the `test_batch_prefill_with_paged_kv_cache_custom_mask` function to have a default value. 
* [`tests/test_batch_prefill_kernels.py`](diffhunk://#diff-f04bd675bf627f5739bd24c7e2eed84ae66aba380b1855a9b13b69c4a000de6fL550-R550): Changed the `custom_mask` parameter to `custom_mask=custom_mask` to set a default value.
> bugfix: fix batch prefill attention kernel unittests

- setup.py
This PR removes `head_dim=64` from pre-built AOT wheels, `head_dim=64` will be supported using JIT in the future.
> misc: remove head dimension 64 from AOT

- setup.py
Keeps the default behavior of #782, i.e., build AOT without `head_dim=64`. But gives an option to specifically enable `head_dim=64`.
`head_dim=64` is used by some small models like [Qwen2.5-0.5B](https://huggingface.co/Qwen/Qwen2.5-0.5B/blob/main/config.json).
> misc: allow head_dim=64 for sm90 AOT

- csrc/batch_prefill.cu
- csrc/batch_prefill_customize_config.jinja
- csrc/single_prefill.cu
- csrc/single_prefill_customize_config.jinja
- include/flashinfer/attention/default_prefill_params.cuh
- include/flashinfer/attention/prefill.cuh
We put `group_size` outside of params mainly because we observe better performance, but with some recent refactor such as #748 and #776 , there is no need to decouple group_size with other parts of the parameters, this PR merge `group_size` back to parameter class.
> refactor: make `group_size` a part of params

- flashinfer/jit/attention.py
- include/flashinfer/attention/decode.cuh
After this fix, the `mse_use_flashinfer` in `test_mla_decode_kernel.py` will improve significantly.
> bugfix: MLA decode should multiply sm_scale by math::log2e

- include/flashinfer/attention/decode.cuh
- tests/test_mla_decode_kernel.py
Co-authored-by: pankajroark <pankajroark@users.noreply.github.com>
As titled, unblock the FlashInfer integration. E2E testing is functioning properly. cc @yzh119 @pankajroark @merrymercy @Ying1123 @ispobock
```bash
python3 tests/test_mla_decode_kernel.py
```
```
Now use MLA decode kernel!
2025-02-06 22:55:31,946 - INFO - flashinfer.jit: Loading JIT ops: batch_decode_mla_with_kv_cache_dtype_q_f16_dtype_kv_f16_dtype_o_f16_dtype_idx_i32_head_dim_qk_512_head_dim_vo_512_use_swa_False_use_logits_cap_False
/usr/local/lib/python3.10/dist-packages/torch/utils/cpp_extension.py:1964: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
warnings.warn( …
```
> fix rope logic in mla decoding

- flashinfer/sparse.py
- tests/test_non_contiguous_prefill.py
#765 introduced changes to the API of `plan`, including renaming `head_dim` to `head_dim_qk` and adding `head_dim_vo`. However, some calling sites were not updated to reflect these changes, resulting in failing unit tests.
This PR addresses the issue by updating the relevant calls, which should resolve the following unit test failures after merging:
- `tests/test_block_sparse.py::test_block_sparse_attention`
- `tests/test_non_contiguous_prefill.py::test_batch_paged_prefill_packed_input`
> Fix arguments of `plan` for split QK/VO head dims

- aot_build_utils/generate.py
There is two problem, 
1)  when called by cmake command, the argument is "ON" / "OFF" instead of "True"
2) `nargs="+"`  make the parser returned `enable_fp8_e4m3` as a type of list, which further caused `if enable_fp8_e4m3` always be true
> bugfix: fix aot build not compatible with cmake command

- include/flashinfer/attention/default_prefill_params.cuh
- include/flashinfer/attention/prefill.cuh
For bf16 kernels, we need to use f32 as the intermediate data type for split-k partial output to avoid numerical errors. This PR adds support for f32 output in CUDA templates.
This PR is the first step towards addressing the bf16 kernel numerical issues.
The remaining tasks include:
1. do not pre-apply `sm_scale` to query, apply `sm_scale` to logits instead.
2. change the split-k default partial output dtype to float32.
> feat: support f32 attention output in FA2 template

- benchmarks/bench_deepseek_mla.py
- csrc/batch_mla_config.jinja
- csrc/batch_mla_plan.cu
- csrc/batch_mla_pybind.cu
- csrc/batch_mla_run.cu
- flashinfer/__init__.py
- flashinfer/jit/__init__.py
- flashinfer/jit/attention.py
- flashinfer/mla.py
- include/flashinfer/attention/heap.h
- include/flashinfer/attention/mla_fa2.cuh
- include/flashinfer/attention/mla_params.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/attention/scheduler.cuh
- include/flashinfer/attention/variant_helper.cuh
- tests/test_deepseek_mla.py
**Description:**
This PR implements a memory efficient fused Deepseek MLA PageAttention kernel for decode, prefill, and chunked prefill operations.
MLA computation after matrix absorption can be described as a (multi-query attention) MQA kernel, with same K/V cache and special head dimensions: `head_dim_qk=576, head_dim_vo=512`.
**Background:**  
For Deepseek v2/3, the large `head_dim` (512) makes it challenging to store the output tensor in registers when using tensor cores. A previous approach ([#551](https://github.com/flashinfer-ai/flashinfer/pull/551)) split `head_dim` across `gridDim.y`, which led to two main issues:
- **Re-computation Overhead:** Multiple blocks had to redundantly compute the Q*K operation.
- **Memory Access Latency:** Using multiple blocks prevented shared memory …
> perf: memory efficient deepseek mla fused page-attention kernel

- include/flashinfer/attention/mla_fa2.cuh
Generalize the MLA template to support different `CTA_TILE_KV` and `NUM_STAGES` for GPUs such as A100.
> feat: unlocking MLA for A100

- include/flashinfer/attention/mla_fa2.cuh
This PR changes the MLA attention template to support sm89 GPUs, which has small shared memory size (99kb per sm), so we have to further reduce shared memory usage: the `NUM_STAGES` can only be set to 1, and `CTA_TILE_KV` could only be set to atmost 16.
We add an option `QK_SHARD` in the KernelTraits (our previous template only supports `QK_SHARD=true`):
1. If true, we use the schedule mentioned in #804, and shards the QK computation on KV dimension, each warpgroup compute half of it, and we need to perform a round of allgather on shared memory for getting the full P in PV computation.
2. If false, we duplicate QK computation on two warpgroups (which is not necessary) but we save the allgather step for P.
We set `QK_SHARD=true` for A100/H100 (shared memory limit is 164kb and 228kb, …
> feat: unlock MLA attention for sm89 (L40/L40s/4090)

- docs/api/mla.rst
DeepSeek-V3 paper link is incorrect in docs，this commit fix it.
> doc: Fix the incorrect DeepSeek-V3 paper link

- csrc/flashinfer_gemm_sm90_ops.cu
Follow up of #823 , the `CutlassSegmentGEMMSM90` API do not have member `plan_info_vec`
> bugfix: fix the signature of `CutlassSegmentGEMMSM90`

- flashinfer/jit/__init__.py
Followup of #823 , we should import `from .. import flashinfer_kernels, flashinfer_kernels_sm90` instead of `from .. import _kernels, _kernels_sm90`, otherwise we will be using JIT compilation all the code.
Also add some logic to catch "undefined symbol" errors in case the AOT wheel compilation is successful but failed to be loaded.
> bugfix: Another bugfix for torch.library

- flashinfer/decode.py
The variable names do not match the names in the comments.
> misc: fix parameters name

- README.md
Hi,
Just fixed typo for "hierical" -> "hierarchical"
Didier
> Update README.md: fixing a typo for "hierical"

- README.md
Hi,
fixing 1 grammar typo for verb: see diff commit for details.
Best,
Didier
> Update README.md: fixing 1 typo

- README.md
This pull request includes a small change to the `README.md` file. The change adds a new project, `TensorRT-LLM`, to the list of projects adopting FlashInfer.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R152): Added `TensorRT-LLM` to the list of projects using FlashInfer.
> adds `TensorRT-LLM` to the list of projects adopting FlashInfer

- csrc/batch_decode_mla_config.jinja
- csrc/batch_decode_mla_cute_sm80.cu
- flashinfer/decode.py
- flashinfer/jit/attention.py
- include/flashinfer/attention/decode_mla_cute_sm80.cuh
- include/flashinfer/attention/scheduler.cuh
- tests/test_mla_decode_kernel.py
Hi @yzh119 , this is a follow up of #766, an interesting idea came to my mind today, can't help to change few lines to verify this idea. 
We can use asymmetric warp config to solve the register file size limit issue, the solution is simply to use 8 warps for the output mma stage, and keep other parts unchanged, because the limitation is on the reg num per cuda block not the whole SM, there is 64K 32b registers per SM which is enough for the f32 output of 64 heads. 
So we now have 4 warps for the att mma stage, 2 warps for the softmax stage, 8 warps for output mma stage, and 4 warps for data load stage, the diagram is updated below:
After the change, output mma stage needs more computation, the benchmark drops a little as expected, but still looks good:
It seems the performance of this …
> perf: MLA decode kernel implemented by CuTe targeted to SM80

- flashinfer/prefill.py
Fix https://github.com/flashinfer-ai/flashinfer/issues/807
For the BatchPrefillWith*KVCacheWrapper that support both FA2 and FA3, user may call the ctor() once and the plan() multiple times.
This PR adds support to reset/select backend in plan()
> fix: Pass backend in BatchPrefillWith*KVCacheWrapper.plan()

- include/flashinfer/attention/decode.cuh
This PR fixes a bug in decode kernel that fails to process the `q_rope_offset` provided in Params. The variable naming follows the existing example in prefill kernel:
https://github.com/flashinfer-ai/flashinfer/blob/ab6484effafd5133514890999ff23129ce3b8a9b/include/flashinfer/attention/prefill.cuh#L39
> bugfix: Fix inline RoPE in decode kernels

- csrc/batch_mla_run.cu
This PR removes the duplicate set of `params.kv_indices` in the MLA kernel.
> misc: Remove duplicate param set in MLA kernel

- include/flashinfer/attention/decode.cuh
Having building error with multiple definitions of `has_maybe_q_rope_offset_v` with building command:
```
TORCH_CUDA_ARCH_LIST="9.0a" FLASHINFER_ENABLE_AOT=1 pip install -e . -v
```
The reason is that we both defined same template struct in `prefill.cuh` and `decode.cuh`:
https://github.com/flashinfer-ai/flashinfer/blob/7bee1cfb6d0322c58ee864f0b592d1952e8c758c/include/flashinfer/attention/prefill.cuh#L39
https://github.com/flashinfer-ai/flashinfer/blob/7bee1cfb6d0322c58ee864f0b592d1952e8c758c/include/flashinfer/attention/decode.cuh#L36
So if the struct is just for condition check, add a prefix of `decode` could avoid this, if no other uses of this struct.
> Unique the symbol of maybe_q_rope_offset_v.

- include/flashinfer/attention/decode.cuh
Following up on #855 and #847, this PR fixes a typo of inline RoPE in decode kernel.
> typo: update `decode_maybe_q_rope_offset`

- include/flashinfer/attention/scheduler.cuh
I am using flashinfer as the c++ backend to make some development. Find two compiler-check error:
1. shouldn't use `move` in returning local object.
2. `num_cluster` is `int32_t`, but in for-loop, it is compared to `uint32_t i = 0`
> fix some compiler pre-check.

- benchmarks/bench_deepseek_mla.py
- csrc/batch_mla_run.cu
- include/flashinfer/attention/cascade.cuh
- include/flashinfer/attention/mla_fa2.cuh
- include/flashinfer/attention/mla_params.cuh
- include/flashinfer/attention/scheduler.cuh
#804 didn't implement split-k, which might result in performance degradation if concurrency is not large enough. This PR fixes issue.
We implemented the v2 scheduler and write-through optimization mentioned in [our paper](https://arxiv.org/pdf/2501.01005) (section 3.3 and appendix in D.2) for load-balancing.
In an early PR (https://github.com/flashinfer-ai/flashinfer/pull/72), we turned off `cudaLaunchCooperativeKernels` and `grid.sync()` because we are not sure whether it's compatible with CUDAGraph. This PR adds them back again for grid synchronization, to save some kernel launch overhead.
On H100 SXM5 80GB (3352 GB/s), this PR:
```
Config: batch_size=1, seq_len=1024, num_heads=16
Memory bandwidth: 22.33 GB/s
Config: batch_size=16, seq_len=1024, num_heads=16
Memory bandwidth: 330.72 …
```
> perf: dynamic split-k for MLA

- .github/workflows/release_wheel.yml
ref
https://github.com/flashinfer-ai/flashinfer/actions/runs/13376817887/job/37357692946
fix
```
Looking in indexes: https://download.pytorch.org/whl/cu121
ERROR: Could not find a version that satisfies the requirement torch==2.6.* (from versions: 2.1.0+cu1[21](https://github.com/flashinfer-ai/flashinfer/actions/runs/13376817887/job/37357692946#step:3:22), 2.1.1+cu121, 2.1.2+cu121, 2.2.0+cu121, 2.2.1+cu121, 2.2.2+cu121, 2.3.0+cu121, 2.3.1+cu121, 2.4.0+cu121, 2.4.1+cu121, 2.5.0+cu121, 2.5.1+cu121)
ERROR: No matching distribution found for torch==2.6.*
```
> fix cu121 torch2.6

- tests/test_deepseek_mla.py
@yzh119  PLZ take a look for this test. It will fail when `kv_len` is not multiple of `page_size`. I checked the kernel but had no clue. If I was not wrong, some bound check in mla kernel was wrong?
> unittest: add MLA test cases where kv_len is evenly divided by page_size.

- include/flashinfer/attention/scheduler.cuh
- tests/test_deepseek_mla.py
The scheduling algorithm in #863 do not consider some requests have kv-cache length 0, this PR fixes the issue.
> bugfix: fix the behavior of MLA kernel when kv-length is 0

- aot_build_utils/generate_dispatch_inc.py
head_dim args from setup.py and parser in aot_build_utils/generate_dispatch_inc.py missmatch
> fix geneate_dispatch_inc args from parser

- include/flashinfer/attention/mla_fa2.cuh
The variable `ckv_smem_offset_w` and `kpe_smem_offset_w`  are never used after update in current loop, and they will be redefined and recomputed in the next loop.I think these are redundant code.
> misc:Remove unused k_smem_offset_w update in MLA kernel

- pyproject.toml
`flashinfer.jit.attention` package is introduced in https://github.com/flashinfer-ai/flashinfer/pull/880, but it's not added into the packages list when building wheel. Python will complain about the package not found during import.
Repro steps:
```
FLASHINFER_ENABLE_AOT=1 python -m build --no-isolation --wheel
pip install --force-reinstall dist/flashinfer_python-0.2.1.post2-cp38-abi3-linux_x86_64.whl
```
Log:
```
Python 3.11.11 (main, Dec 06 2024, 17:06:18) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flashinfer
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/build/ktransformers/venv/lib64/python3.11/site-packages/flashinfer/__init__.py", line 18, in <module>
from .activation import gelu_and_mul as …
```
> [Hotfix] Add flashinfer.jit.attention into packages

- include/flashinfer/attention/scheduler.cuh
- tests/test_deepseek_mla.py
This update also addresses an issue in the scheduler that could cause the program to hang under certain conditions.
> unittest: add unittests for MLA + cudagraph

- include/flashinfer/attention/mla.cuh
As pointed in https://github.com/flashinfer-ai/flashinfer/issues/892#issuecomment-2677596676 The second stage of split-k seems to have a huge overhead. This PR is the first second in addressing these issues, by changing the vector size from 4 to 8.
> perf: fix the performance of stage stage of split-k

- flashinfer/mla.py
- flashinfer/sparse.py
Use cpu as default device for pin_memory in mla.py and sparse.py
> fix: pin_memory use cpu as default device

- csrc/batch_mla_run.cu
- csrc/batch_mla_sm90_run.cu
- include/flashinfer/attention/mla.cuh
- include/flashinfer/attention/mla_hopper.cuh
- include/flashinfer/attention/mla_params.cuh
- include/flashinfer/attention/scheduler.cuh
As observed in #892 , we found flashinfer mla's second stage of split-k is very slow (when batch size is small), this is because our scheduler only uses one CTA for the second stage of split-k.
> perf: fix MLA split-k performance bug

- include/flashinfer/attention/mla_hopper.cuh
This pull request includes a change to the `convert_s_to_p` function in the `mla_hopper.cuh` file to improve type safety and clarity.
Function signature modification:
* [`include/flashinfer/attention/mla_hopper.cuh`](diffhunk://#diff-5ebeba4848db48074fb2636d9ef52f85409674d9fcaba1e2b8091cf6fc36e651L554-R554): Changed the return type of the `convert_s_to_p` function from `auto` to `void` to explicitly indicate that the function does not return a value.
> bugfix: Fix no return type error

- pyproject.toml
This PR adds `tvm_binding` to `pyproject.toml` so that when releasing and building wheels, the contents under `tvm_binding` will be packed together.
> [Package] Add tvm binding to `flashinfer.data` when packaging

- flashinfer/gemm.py
- flashinfer/page.py
- flashinfer/triton/gemm.py
- flashinfer/triton/page.py
Some platforms do not support triton but user still need other functionlities (e.g. JIT) in flashinfer, this PR moves triton dependency to flashinfer.triton and defer the import so that user can still use flashinfer without installing triton.
cc @MasterJH5574
> refactor: move triton dependency to flashinfer.triton

- csrc/flashinfer_ops.cu
- csrc/flashinfer_sampling_ops.cu
- csrc/sampling.cu
- flashinfer/sampling.py
- include/flashinfer/sampling.cuh
- tests/test_sampling.py
In our previous sampling algorithms, the rejection sampling algorithm for top-p/top-k sampling is not guaranteed to stop within given number of rounds, and the API would return an `success` array indicating whether the sampling is successful or not. If not, serving engines will fall back to naive sorting-base sampling algorithm.
This PR improves the rejection sampling algorithm, instead of relying on a single pivot, we propose to use dual pivot, and the bound `[low, high]` is guaranteed to shrink by half each round. After 32 rounds, the gap between low and high will be within 2^-32.
Design doc: https://docs.google.com/document/d/1rhdgOM5VawSMAK6jjapFS02-1neGYd8dNazhtmZg7fA/edit?usp=sharing
* This PR removes the `success` return value of all sampling API, which is not compatible with …
> sampling: dual pivot rejection sampling algorithm to improve top-p/top-k sampling efficiency

- csrc/norm.cu
- include/flashinfer/norm.cuh
- tests/test_norm.py
We should support normalization functions where input and output are not contiguous.
> feat: support non-contiguous input/output in normalization functions

- csrc/flashinfer_ops.cu
- csrc/flashinfer_sampling_ops.cu
- csrc/sampling.cu
- flashinfer/sampling.py
- include/flashinfer/sampling.cuh
- tests/test_sampling.py
1. add a parameter `indices` to sampling APIs to allow multiple samples from the same probability distribution.
2. address the abnormal case of sum(probs) < u, where our earlier implementation might return an impossible value.
3. add unittest for comparing the sampled result distribution (with a lot of trials) and original distribution.
> feat: improve sampling algorithm robustness

- include/flashinfer/sampling.cuh
Reduce maximum number of iterations.
> perf: use max probability instead of 1 as upper bound in top-p/k sampling

- profiler/README.md
As the title suggest, `tg4perfetto` requires the specific version of `protobuf` as dependency (i.e., 3.20.0)
> fix: add install step of profiler's dependency

- flashinfer/jit/__init__.py
When ① build flashinfer with CUDA >= 12.5 (using system-wide CUDA toolkit under `/usr/local/cuda`), and ② run with CUDA < 12.5 (using `libcudart.so` under the python environment `/usr/local/lib/python3.10/dist-packages/nvidia/cuda_runtime/lib/libcudart.so.12`), one would meet the issue of undefined symbol `cudaGetDriverEntryPointByVersion`, which is introduced since CUDA 12.5.
This issue has been reported and fixed in other projects:
- cutlass: https://github.com/NVIDIA/cutlass/pull/2086
- sglang: https://github.com/sgl-project/sglang/pull/3372
This fix is a workaround of this issue which forces flashinfer use system-wide CUDA toolkit, refer to the fix in [sglang](https://github.com/sgl-project/sglang/pull/3372), cc @zhyncs.
> fix: undefined symbol cudaGetDriverEntryPointByVersion with CUDA >= 12.5

- csrc/activation.cu
- csrc/flashinfer_norm_ops.cu
- csrc/flashinfer_ops.cu
- csrc/norm.cu
- flashinfer/activation.py
- flashinfer/jit/activation.py
- flashinfer/norm.py
- include/flashinfer/activation.cuh
- include/flashinfer/norm.cuh
- tests/test_activation.py
- tests/test_norm.py
[PDL](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#programmatic-dependent-launch-and-synchronization) can be used to overlap prologue and epilogue of two kernels on Hopper or later architectures. This PR adds initial PDL support for some simple kernels such as norm and activations.
> feat: experimenta support of PDL

- flashinfer/activation.py
- flashinfer/norm.py
Fix terminology from "programmatic dependency loading" to "programmatic dependent launch"
> typo: fix pdl terminology

- flashinfer/sampling.py
Looks like another typo in #912 - sorry for taking 3 PRs to fix one docstring! :roll_eyes: 
```
>>> # uniform samples for rejection sampling
-    >>> uniform_samples = torch.rand(batch_size, num_speculate_tokens + 1).to(0)
-    tensor([[0.8823, 0.9150, 0.3829], device='cuda:0')
>>> target_probs = torch.tensor([[[0.0, 0.1, 0.6, 0.3], [1.0, 0.0, 0.0, 0.0], [0.7, 0.1, 0.1, 0.1]]]).to(0)
```
> typo: remove another uniform samples leftover

- benchmarks/bench_append_paged_mla_kv_cache.py
- csrc/flashinfer_ops.cu
- csrc/flashinfer_page_ops.cu
- csrc/page.cu
- docs/api/page.rst
- flashinfer/__init__.py
- flashinfer/page.py
- include/flashinfer/page.cuh
- scripts/task_jit_run_tests_part2.sh
- tests/test_mla_page.py
related to [#877 ](https://github.com/flashinfer-ai/flashinfer/issues/877)
This PR implement MLA cache store，and passed correctness test in the case of ckv_dim=512 and kpe_dim=64，but no further performance test yet. Sincerely hope somebody who familiar with CUDA can help improve performance.
> feat - support mla kvcache store

- include/flashinfer/attention/mla.cuh
- tests/test_deepseek_mla.py
We found that in the batch MLA FA2 implementation, if there exists NaN data within the computed CKV cache page, the kernel implementation would inadvertently read these invalid values and corrupt other valid data, ultimately resulting in all outputs becoming NaN. Therefore, this PR introduces masking logic to exclude CKV entries outside the computation scope from being processed.  It may cause other requests to get error response when previous request precision overflow
and write nan to kvcache.
1. modify `test_batch_mla_varlen_page_attention` in `test_deepseek_mla.py` to use fa2 implement, and set an nan data in unrelated sequence
```
if causal and qo_len > min(kv_len_0, kv_len_1, kv_len_2):
pytest.skip("qo_len > kv_len not supported for causal attention")
num_different_kv_len = 3
..... …
```
> fix - fix bug when not relevant seq has nan data

- csrc/pytorch_extension_utils.h
Complete the PyModuleDef structure initialization in pytorch_extension_utils.h by adding NULL initializers for m_slots, m_traverse, m_clear, and m_free fields.
This resolves compiler errors when using -Werror=missing-field-initializers.
> bugfix: Fix missing PyModuleDef field initializers

- Jenkinsfile
- include/flashinfer/attention/mla.cuh
- include/flashinfer/attention/prefill.cuh
- scripts/task_jit_run_tests_part4.sh
- tests/conftest.py
- tests/test_deepseek_mla.py
The sm86/sm89 version of mla kernel was not tests after change #942, this PR fixes the issue.
This PR also make the following changes:
1. adding the mla unittest to CI (on a10g node). 
2. shrinking the unittest of mla so that CI can finish in reasonable time.
3. change `is_sm90a_supported(torch.device("cuda"))` to `backend == "fa3" and not is_sm90a_supported(torch.device("cuda")):` for non-hopper GPUs, as pointed by @Atream .
> bugfix: bugfix to #949

- csrc/flashinfer_ops.cu
- setup.py
We currently don't generate the AOT implementations for POD Attention. This causes missing symbols when loading AOT shared library.
I'll try to work on #791 later this week so that we can have a unified code path for AOT and JIT.
> misc: Temporarily disable POD from AOT wheels

- include/flashinfer/vec_dtypes.cuh
Compiling FlashInfer on CUDA 12.2 triggers errors such as those shown below. This PR aims to fix this issue.
```
#10 1380.2 /usr/flexflow-serve/deps/flashinfer/include/flashinfer/attention/../vec_dtypes.cuh(55): error: more than one instance of function "flashinfer::__hmul" matches the argument list:
#10 1380.2             function "__hmul(__nv_bfloat16, __nv_bfloat16)" (declared at line 3518 of /usr/local/cuda/include/cuda_bf16.hpp)
#10 1380.2             function "flashinfer::__hmul(__nv_bfloat16, __nv_bfloat16)" (declared at line 44)
#10 1380.2             argument types are: (const __nv_bfloat16, const __nv_bfloat16)
#10 1380.2     val.x = __hmul(a.x, b.x);
#10 1380.2             ^
#10 1380.2 
#10 1380.2 /usr/flexflow-serve/deps/flashinfer/include/flashinfer/attention/../vec_dtypes.cuh …
```
> Fix compilation on cuda 12.2

- flashinfer/decode.py
- flashinfer/pod.py
- flashinfer/prefill.py
- flashinfer/sparse.py
As noted in #965 , we have some misleading docstring about the use of `non_blocking` option in plan functions of attention wrappers (they are only necessary in our old designs which we deprecate later), this PR fixes the issue.
> doc: remove misleading docstring about `non_blocking`

- flashinfer/activation.py
- flashinfer/cascade.py
- flashinfer/decode.py
- flashinfer/gemm.py
- flashinfer/mla.py
- flashinfer/norm.py
- flashinfer/page.py
- flashinfer/pod.py
- flashinfer/prefill.py
- flashinfer/quantization.py
- flashinfer/rope.py
- flashinfer/sampling.py
This pr fixes https://github.com/flashinfer-ai/flashinfer/issues/960,  #764 refactors the codebase to use torch.library which introduces some cpu-side overhead when operators are not captured by CUDAGraph.
As suggested by @youkaichao , we can bypass the pytorch dispatcher by `torch.ops.namespace.op_name.default`.
Co-authored-by: Kaichao You <youkaichao@gmail.com>
> perf: reduce torch.library dispatch overhead

- csrc/pod.cu
- csrc/pod_customize_config.jinja
- csrc/pod_kernel_inst.jinja
- include/flashinfer/attention/pod.cuh
Removes AOT header files from JIT compilation flow and corrects some typos so that JIT compilation of POD doesn't fail anymore.
> Fix POD JIT bugs

- benchmarks/bench_renorm.py
Partial results:
```
---
top-p renorm
vocab_size: 128512, batch_size: 512, distrib: normal_distribution(std=1), p: 0.1, duration: 2014.94 us, effective bandwidth: 261.24 GB/s
vocab_size: 128512, batch_size: 512, distrib: normal_distribution(std=1), p: 0.9, duration: 2568.39 us, effective bandwidth: 204.95 GB/s
vocab_size: 128512, batch_size: 512, distrib: gumbel_distribution(beta=1), p: 0.1, duration: 2021.48 us, effective bandwidth: 260.40 GB/s
vocab_size: 128512, batch_size: 512, distrib: gumbel_distribution(beta=1), p: 0.9, duration: 2377.93 us, effective bandwidth: 221.36 GB/s
---
top-k renorm
vocab_size: 128512, batch_size: 512, distrib: normal_distribution(std=1), k: 10, duration: 1761.15 us, effective bandwidth: 298.89 GB/s
vocab_size: 128512, batch_size: 512, distrib: …
```
> benchmark: add sampling.renorm benchmarks

- benchmarks/bench_deepseek_mla.py
- include/flashinfer/attention/mla_hopper.cuh
- include/flashinfer/attention/prefill.cuh
This PR implements #892 .
Per benchmark, 2WG pipeline (FlashMLA's implementation) is faster than our current 3WG pipeline design on Hopper. While it remains investigation where the gap comes from, we should implements the 2WG (and 4WG in the future) pipeline in FlashInfer to make sure our implementation not getting worse performance than flashmla.
Before this PR:
```
Config: batch_size=64, seq_len=1024, num_heads=64
Memory bandwidth: 1547.23 GB/s
FLOPs: 167.29 TFLOPs
Config: batch_size=64, seq_len=1024, num_heads=128
Memory bandwidth: 1483.82 GB/s
FLOPs: 290.23 TFLOPs
Config: batch_size=128, seq_len=1024, num_heads=64
Memory bandwidth: 2238.72 GB/s
FLOPs: 242.06 TFLOPs
Config: batch_size=128, seq_len=1024, num_heads=128
Memory bandwidth: 1612.66 GB/s
FLOPs: 315.43 TFLOPs
Config: …
```
> perf: Use 2WG pipeline design for MLA implementation on Hopper

- CMakeLists.txt
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/fp16.h
As described in #806 and #936, setting the cmake build flag `FLASHINFER_GEN_USE_FP16_QK_REDUCTIONS` to "true" causes a build failure due to `cuda_fp16.h` not supporting `constexpr` cast from `__half` type to `float`. Note that the issue is not just a CMake/C++ configuration issue the issue will be triggered even in the flashinfer JIT code compilation path as reported in #915.
The PR fixes #806 and #936 by adding a modified version of the FP16 header from the [FP16 library](https://github.com/Maratyszcza/FP16) that supports `constexpr` versions of the conversion functions. To make the conversion functions `constexpr`, I am using `std::bit_cast` that is the reason for bumping the required standard to 20.
With these changes I am able to build the C++ API with both …
> Fix compilation with FP16_QK_REDUCTION enabled.

- flashinfer/jit/core.py
If `FLASHINFER_JIT_VERBOSE=1`, flashinfer JIT compilation will:
* Print verbose output (register usage, etc).
* Set `lineinfo` for using [compute-sanitizer](https://docs.nvidia.com/compute-sanitizer/ComputeSanitizer/index.html)
> misc: Use environment variable to control JIT verbose flag

- flashinfer/jit/env.py
I'm using sglang in kubernetes; sglang is importing flashinfer
I have rather strict setup that does not allow root user to run the container, so I'm running the container with user `nobody` and I need to specify various directories that are supposed to be writable.
With latest flashinfer, I noticed that it tries to create some directories under `$HOME`. Common way to get around it is to path some env variable to the libraries trying to write stuff so I can control the target path and let it write to the writable directory (And in my case this is not $HOME). So I'm proposing to add an option to explicitly specify directory where flashinfer wants to write so that the user has more control over it
> Allow passing workspace base directory via environment variable

- .github/workflows/release_wheel.yml
torch 2.6 + cu124 wheel is not compatible with torch 2.6 + cu126 wheel because pytorch switch from manylinux 2014 to manylinux 2_28 (https://dev-discuss.pytorch.org/t/pytorch-linux-wheels-switching-to-new-wheel-build-platform-manylinux-2-28-on-november-12-2024/2581) from torch 2.6 + cu126 on, which will result in ABI incompatibility issue: https://github.com/flashinfer-ai/flashinfer/issues/911#issuecomment-2764408674
> ci: add torch 2.6+cu126 wheel

- .devcontainer/Dockerfile
Corrected the path for the Python 3.12 environment from `/home/devuser/envs/py312/bin` to `/home/devuser/conda/envs/py312/bin`.
> misc: fix devcontainer conda path

- include/flashinfer/attention/hopper/block_sparse_gather.cuh
- include/flashinfer/attention/mla_hopper.cuh
Update cutlass to latest version (v3.9) for incoming pull requests on blackwell support.
Hopper workloads experienced slight performance degradation, will investigate them later.
> 3rdparty: upgrade cutlass to 3.9

- flashinfer/jit/core.py
- setup.py
We observed some performance degradation after upgrading cutlass to v3.9.
This is because some runtime checks are added to cutlass in debug mode:
* https://github.com/NVIDIA/cutlass/blob/df8a550d3917b0e97f416b2ed8c2d786f7f686a3/include/cutlass/pipeline/sm90_pipeline.hpp#L66-L70
* https://github.com/NVIDIA/cutlass/blob/df8a550d3917b0e97f416b2ed8c2d786f7f686a3/include/cutlass/pipeline/sm90_pipeline.hpp#L82-L86
This PR addresses the issue by adding `-DNDEBUG` to compilation flags in both JIT and AOT mode.
After this PR, we no longer observe the performance degradation.
> perf: add `-DNDEBUG` compilation flag

- .github/workflows/release_wheel.yml
- .github/workflows/release_wheel_sglang.yml
torch 2.6 + cu126 and later torch versions uses manylinux_2_28 instead of manylinux_2014 and we have to select manylinux_2_28 docker images for new versions.
Ref: https://dev-discuss.pytorch.org/t/pytorch-linux-wheels-switching-to-new-wheel-build-platform-manylinux-2-28-on-november-12-2024/2581
cc @abcdabcd987 @zhyncs
> ci: select 2_28 manylinux builder for new torch+cuda versions

- README.md
- docs/installation.rst
This pull request updates the installation instructions for the FlashInfer PyTorch API in the `README.md` file to reflect the latest CUDA and torch versions.
Installation instructions update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L51-R59): Updated the CUDA version from 12.4 to 12.6 and the torch version from 2.5 to 2.6 in the installation commands.
> misc: update REAMDME.md

- flashinfer/__init__.py
In `tests/test_mla_decode_kernel.py`, the code below uses `BatchDecodeMlaWithPagedKVCacheWrapper`:
https://github.com/flashinfer-ai/flashinfer/blob/f579ca254ca321f9ab4ba23ab6ea2e49b0da9c11/tests/test_mla_decode_kernel.py#L348-L355
However an AttributeError is thrown:
```
AttributeError: module 'flashinfer' has no attribute 'BatchDecodeMlaWithPagedKVCacheWrapper'. Did you mean: 'BatchDecodeWithPagedKVCacheWrapper'?
```
Because the module `flashinfer` does not import  `BatchDecodeMlaWithPagedKVCacheWrapper` from submodule `.decode` and export it.
This patch can solve it.
> bugfix: import wrapper of mla decode

- csrc/flashinfer_ops.cu
- csrc/single_decode.cu
- csrc/single_decode_jit_pybind.cu
- flashinfer/decode.py
- flashinfer/prefill.py
- include/flashinfer/attention/decode.cuh
- tests/test_tensor_cores_decode.py
This PR updates the decode attention APIs by:
* Adding `lse` return value for `single_decode_with_kv_cache` API per requested in #1006 (note that it's not the preferred API and only useful for single batch inference).
There is no breaking changes in this PR.
> feat: update decode attention APIs

- profiler/README.md
We created a fork of [tg4perfetto](https://github.com/flashinfer-ai/tg4perfetto) to use the latest protobuf (6.30.2 at this time). Updating the doc accordingly.
> doc: use latest protobuf for profiler

- flashinfer/prefill.py
When using custom mask for Medusa or other method, flashinfer api will inference with custom mask buf, but when there has no draft token, the flashinfer api will be inference using causal prefill or decode. But, I found that when convert custom mask into causal inference, the custom mask buf is not setted to None, So the result will be error using non-casual or casual when after using custom mask with same prefill warpper.
> bugfix: fix custom mask not be reseted after convert custom mask into causal or non-causal

- include/flashinfer/attention/hopper/sparse_mainloop.cuh
This PR fixes the out-of-bound K/V value loading in the FA3 `sparse_mainloop.cuh`, which may cause a nan value for `BatchPrefillWithPagedKVCacheSM90Run` and `BlockSparseAttentionWrapper `. The accumulation of out-of-bound V and S causes the nan value.
This may solve the issue https://github.com/flashinfer-ai/flashinfer/issues/1018.
> fix: add zero init for KV tiled copy

- .devcontainer/Dockerfile
Fix #1041 
As mentioned in rapidsai/devcontainers#373, the `ubuntu` user is pre-installed in Ubuntu Lunar/Noble base images. 
In my testing, removing the default `ubuntu` user and keeping only `devuser` successfully resolved the issue.
> fix: remove default ubuntu user in Lunar/Noble

- include/flashinfer/attention/pod.cuh
For some reason cudaOccupancyMaxActiveBlocksPerMultiprocessor returns 0, so manually calculate the value instead.
> Fix KV chunking for POD. 

- include/flashinfer/attention/cutlass_mla.cuh
There are some bugs with blackwell mla when split-kv is enabled, temporally disable it to guarantee the correctness of results.
> bugfix: temporally disable split-kv in blackwell mla

- csrc/fmha_cutlass_sm100.cu
- csrc/fmha_cutlass_sm100_pybind.cu
- csrc/group_gemm_groupwise_sm100.cu
- csrc/group_gemm_sm100_pybind.cu
- flashinfer/gemm.py
- flashinfer/prefill.py
- include/flashinfer/attention/blackwell/fmha_cutlass_sm100.cuh
- include/flashinfer/gemm/gemm_groupwise_sm100.cuh
- include/flashinfer/gemm/group_gemm_groupwise_sm100.cuh
Instead of device allocation inside operators, we should pre-allocate (and cache) workspace buffers to avoid allocation for each kernel run.
cc @yongwww  @cyx-6 .
> bugfix: remove device allocation

- setup.py
Before, when building wheel with AOT enabled:
```
...
return _build_backend().build_wheel(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/setuptools/build_meta.py", line 415, in build_wheel
return self._build_with_temp_dir(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/dist-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
self.run_setup()
File "/usr/local/lib/python3.12/dist-packages/setuptools/build_meta.py", line 313, in run_setup
exec(code, locals())
File "<string>", line 275, in <module>
File "/usr/local/lib/python3.12/dist-packages/torch/utils/cpp_extension.py", line 1207, in CUDAExtension
return setuptools.Extension(name, sources, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> bugfix: Cast build paths to str before setuputils Extension

- .github/workflows/release_wheel.yml
---
Add a build for PyTorch 2.7.0 https://pytorch.org/blog/pytorch-2-7 and also remove 2.4 to keep only the last 3 PyTorch releases https://github.com/flashinfer-ai/flashinfer/pull/835
As there is no official release of FlashInfer for PyTorch 2.7 yet, I'm currently building FlashInfer from [source on vLLM](https://github.com/vllm-project/vllm/blob/main/docker/Dockerfile#L258-L261) and that adds to the build time there.
---
PyTorch 2.7 also moves to CUDA 12.8 build and removes 12.4 (and 12.1)
> Add PyTorch 2.7.0 build

- include/flashinfer/attention/blackwell/collective/sm100_fmha_fwd_epilogue_tma_warpspecialized.hpp
- include/flashinfer/attention/blackwell/collective/sm100_fmha_fwd_mainloop_tma_warpspecialized.hpp
- include/flashinfer/attention/blackwell/fmha_cutlass_sm100.cuh
- include/flashinfer/attention/blackwell/kernel/sm100_fmha_fwd_kernel_tma_warpspecialized.hpp
- tests/test_blackwell_fmha.py
---
This PR adds LSE output of blackwell fmha kernels (adapted from cutlass example).
Co-authored-by: v0i0 <mhohnerbach@nvidia.com>
---
> bugfix: adding lse output to blackwell fmha kernels

- flashinfer/jit/__init__.py
- flashinfer/jit/core.py
- flashinfer/jit/cpp_ext.py
- flashinfer/jit/env.py
- flashinfer/jit/parallel_load_modules.py
- flashinfer/jit/utils.py
Part of AOT Refactor (#1064)
First, this PR introduces a `JitSpec` class for describing the build instructions for a torch cpp extension. In future PRs, all modules will return a `JitSpec` instead of a loaded torch ops. Then, AOT can build all of these in one pass.
Second, instead of relying on torch, we generate the ninja files by ourselves. This gives us more flexible control over the build process. The major difference in the ninja file is that we prefix the target files with the extension name (i.e., `$name/xxx.o` instead of `xxx.o`). This allows us to use `subninja` to include all ops for the AOT build.
> misc: jit: Introduce JitSpec and Generate ninja file

- flashinfer/activation.py
- flashinfer/cascade.py
- flashinfer/custom_all_reduce.py
- flashinfer/decode.py
- flashinfer/gemm.py
- flashinfer/jit/__init__.py
- flashinfer/jit/activation.py
- flashinfer/jit/attention/pytorch.py
- flashinfer/jit/core.py
- flashinfer/mla.py
- flashinfer/norm.py
- flashinfer/page.py
- flashinfer/pod.py
- flashinfer/prefill.py
- flashinfer/quantization.py
- flashinfer/rope.py
- flashinfer/sampling.py
- tests/test_deepseek_mla.py
- tests/test_jit_example.py
This PR changes the caller of `load_cuda_ops()` to directly use `JitSpec`. Also add deprecation warning for `load_cuda_ops()`.
> misc: jit: Deprecate `load_cuda_ops()`

- flashinfer/activation.py
- flashinfer/cascade.py
- flashinfer/custom_all_reduce.py
- flashinfer/gemm.py
- flashinfer/jit/__init__.py
- flashinfer/mla.py
- flashinfer/norm.py
- flashinfer/page.py
- flashinfer/quantization.py
- flashinfer/rope.py
- flashinfer/sampling.py
Separate `gen_xxx_module() -> JitSpec` out of `get_xxx_module()`. In upcoming PR, AOT script will call `gen_xxx_module()` to get all `JitSpec` then compile everything in one run.
> misc: jit: Refactor gen JitSpec out of get_xxx_module

- flashinfer/cascade.py
- flashinfer/custom_all_reduce.py
- flashinfer/gemm.py
- flashinfer/jit/__init__.py
- flashinfer/jit/activation.py
- flashinfer/jit/attention/pytorch.py
- flashinfer/jit/attention/tvm.py
- flashinfer/jit/core.py
- flashinfer/jit/cpp_ext.py
- flashinfer/jit/env.py
- flashinfer/mla.py
- flashinfer/norm.py
- flashinfer/page.py
- flashinfer/quantization.py
- flashinfer/rope.py
- flashinfer/sampling.py
Change from
```python
from .jit.env import FLASHINFER_XXX
```
to
```python
from .jit import env as jit_env
jit_env.FLASHINFER_XXX
```
This allows the AOT script to override the env vars.
> misc: jit: Import jit_env as a module

- flashinfer/aot.py
- flashinfer/jit/cpp_ext.py
Provide a script to build all AOT ops. The default parameters should cover most models. The script builds the ops in `$PROJECT_ROOT/build/aot/` folder, then copies the `.so` files to `$PROJECT_ROOT/aot-ops/` folder. In future PR, the packaging script will copy those ops to `data/aot-ops/` in the wheel.
This script can also serve as a template. If other developers wants to build a AOT wheel with a very different set of kernels, they can do something similar to what this script does.
Example run:
```
$ TORCH_CUDA_ARCH_LIST="8.0 9.0a 10.0a+PTX" python -m flashinfer.aot
AOT build summary:
out_dir: /flashinfer-src/aot-ops
build_dir: /flashinfer-src/build/aot
fa2_head_dim: [(64, 64), (128, 128)]
fa3_head_dim: [(192, 128), (128, 128)]
f16_dtype: [torch.float16, …
```
> misc: aot: Add script to build all AOT ops

- .gitignore
- README.md
- custom_backend.py
- docs/installation.rst
- flashinfer/__init__.py
- flashinfer/aot.py
- flashinfer/jit/core.py
- flashinfer/jit/cpp_ext.py
- flashinfer/jit/env.py
- pyproject.toml
- scripts/run-ci-build-wheel.sh
- scripts/task_test_aot_build_import.sh
- setup.py
This PR updates packaging for AOT wheel and JIT sdist, and update documents.
How AOT kernel is selected at runtime:
* In `JitSpec.build_and_load()`, if `flashinfer/data/aot/$name/$name.so` exists, it loads the so file and skips JIT.
* `prebuilt_ops_uri` and `has_prebuilt_ops` are not longer needed (will remove in next PR).
AOT wheel packaging flow:
1. `python -m flashinfer.aot`. This generates AOT kernels in `aot-ops/$name/$name.so`. 
2. `python -m build --no-isolation --wheel`
* The custom build backend symlinks `build/aot-ops-package-dir` to `aot-ops`. All kernels are then copied to `flashinfer/data/aot/` as package data.
* Note that there's no need for `FLASHINFER_ENABLE_AOT=1` any more.
JIT sdist packaging flow:
1. `python -m build --sdist`
* The custom …
> misc: aot: Refactor AOT packaging

- docs/conf.py
- flashinfer/activation.py
- flashinfer/cascade.py
- flashinfer/custom_all_reduce.py
- flashinfer/decode.py
- flashinfer/gemm.py
- flashinfer/jit/__init__.py
- flashinfer/norm.py
- flashinfer/page.py
- flashinfer/pod.py
- flashinfer/prefill.py
- flashinfer/quantization.py
- flashinfer/rope.py
- flashinfer/sampling.py
- tests/test_activation.py
- tests/test_alibi.py
- tests/test_batch_decode_kernels.py
- tests/test_batch_prefill_kernels.py
- tests/test_block_sparse.py
- tests/test_group_gemm.py
- tests/test_logits_cap.py
- tests/test_non_contiguous_decode.py
- tests/test_non_contiguous_prefill.py
- tests/test_pod_kernels.py
- tests/test_shared_prefix_kernels.py
- tests/test_sliding_window.py
- tests/test_tensor_cores_decode.py
`has_prebuilt_ops` and `prebuilt_ops_uri` is no longer needed. Inside `JitSpec.build_and_load()`, it tests if prebuilt ops exists.
> misc: aot: Remove has_prebuilt_ops

- benchmarks/bench_groupwise_grouped_gemm_fp8_blackwell.py
- csrc/group_gemm_groupwise_sm100.cu
- csrc/group_gemm_sm100_pybind.cu
- docs/api/gemm.rst
- flashinfer/gemm.py
- include/flashinfer/gemm/group_gemm_groupwise_sm100.cuh
- tests/test_groupwise_scaled_gemm_fp8.py
This PR reduce the grouped gemm overhead outside kernel itself:
1. remove the multiple of 4 check, and add notice in the documentation (the multiple ensurance should be guaranteed when we prepare these inputs, in an outer moe module).
2. use pdl for prepare args and gemm kernel.
3. fixed int overflow bug in prepare args kernel (use int64 to compute stride instead).
---
---
---
cc @cyx-6  @yongwww  @elfiegg
> perf: accelerate blackwell grouped gemm

- csrc/group_gemm_groupwise_sm100.cu
- include/flashinfer/gemm/group_gemm_groupwise_sm100.cuh
Fix stride for cutlass sm100 grouped gemm. The input scale tensor may be larger than `m_indptr[-1]`. The real stride should be infered from tensor shape.
> Fix Cutlass grouped GEMM stride

- csrc/batch_prefill_fp8_sm90.cu
- flashinfer/aot.py
- include/flashinfer/attention/hopper/quantization/prefill_sm90.cuh
- `batch_indices_offset` (introduced in #1015 ) are not passed to fp8 attention kernels, this PR fixes the issue.
- adding fp8 kernels to aot generators.
#1064 
---
---
---
cc @abcdabcd987
> bugfix: fix fp8 attention kernels aot compilation issue

- setup.py
Follow-up of AOT Refactor (#1064)
Currently, the wheel doesn't contains a platform tag (i.e. `none`), for example:
```
flashinfer_python-0.2.5+20250530.976cfb4.torch270.cu128-py3-none-any.whl
```
The platform tag is used to distinguish x86_64 systems and ARM systems.
The cause is that setuptools doesn't see any extensions or c libraries, so it determines that this wheel is a pure python wheel. Based on [this stackoverflow answer](https://stackoverflow.com/a/45150383), we can override this behavior.
After the fix, the wheel contains platform tag correctly:
```
flashinfer_python-0.2.5+20250530.976cfb4.torch270.cu128-cp39-abi3-linux_x86_64.whl
flashinfer_python-0.2.5+20250530.976cfb4.torch270.cu128-cp39-abi3-linux_aarch64.whl
```
> misc: aot: Add platform tag to wheel

- README.md
Previous slack link requires an email address (with cs.washington.edu), which is not expected.
> misc: update slack link

- flashinfer/aot.py
- flashinfer/utils.py
Do not compile sm90a/sm100a kernels for CUDA version lower than certain threshold.
Check the failed jobs https://github.com/flashinfer-ai/flashinfer/actions/runs/15504091163/job/43657444651
cc @abcdabcd987 @wenscarl
> ci: add guard for aot compilation

- docs/wrap_run_llm.py
#1132 was prematurely merged. This PR corrects the runllm widget id again.
> misc: correct runllm widget (again)

- flashinfer/activation.py
- flashinfer/cascade.py
- flashinfer/decode.py
- flashinfer/fp4_quantization.py
- flashinfer/fused_moe.py
- flashinfer/gemm.py
- flashinfer/mla.py
- flashinfer/norm.py
- flashinfer/page.py
- flashinfer/pod.py
- flashinfer/prefill.py
- flashinfer/quantization.py
- flashinfer/rope.py
- flashinfer/sampling.py
- flashinfer/sparse.py
Our codebase widely uses global dict for caching modules, and it's preferable to use functools.cache instead.
> refactor: use functools.cache instead of global dict for caching modules

- flashinfer/jit/cpp_ext.py
- Added support for `FLASHINFER_EXTRA_LDFLAGS` environment variable to allow users to pass additional linker flags
- Enables users to specify custom CUDA library paths when the default `$cuda_home/lib64` is not available on their system
- Modified `flashinfer/jit/cpp_ext.py` to read and parse the `FLASHINFER_EXTRA_LDFLAGS` environment variable
- The environment variable is split on whitespace and added to the ldflags list before any explicit extra_ldflags
Users can now set:
```bash
export FLASHINFER_EXTRA_LDFLAGS="-L/usr/local/cuda/lib"
```
This addresses systems where CUDA libraries are located in `$cuda_home/lib` instead of the default `$cuda_home/lib64`.
Fixes #1143
> feat: Add support for FLASHINFER_EXTRA_LDFLAGS environment variable

- include/flashinfer/trtllm/common.h
- include/flashinfer/trtllm/fmha/fmhaKernels.cuh
This is meant to help debugging the lookup/launch sequence for these kernels.
New log will look like this:
```
[DEBUG] Loading new kernel for dtypeQ=FP16, dtypeKv=FP16, dtypeOut=FP16, sm=100 with 18 loaded kernels
[DEBUG] Searching for kernel traits (18 available) in TllmGenFmhaKernel(FP16, FP16, FP16, 100) qkvLayout=2, maskType=0, kernelType=2, tileScheduler=0, multiCtasKvMode=1, headDimPerCtaV=128, headDimQk=128, headDimV=128, tileSizeKv=128, numTokensPerPage=16, maxNumHeadsQPerKvInCta=8, reuseSmemKForV=0, uses2CtaMma=0
...
[DEBUG] TRTLLM-Gen launch info (in TllmGenFmhaKernel FP16, FP16, FP16, 100): kernelName = fmhaSm100Kernel_QFp16KvFp16AccFp32OFp16HQk128HV128LayoutPagedKvMaskDenseP16VarSeqLenTileSizeQ8TileSizeKv128PersistentSwapsMmaAbForGeneration
```
> Add more logging to TRTLLM-GEN debug trace (NFC)

- tests/test_fp4_quantize.py
For the FP4 MoE application, the typical pattern is: quantization without swizzling → all-gather → swizzling, in order to save bandwidth.
Add tests to cover the swizzling and unswizzling logic, including cases where the batch dimension is not a multiple of 128.
> Add fp4 quantization swizzling tests

- csrc/flashinfer_ops.cu
- csrc/flashinfer_sampling_ops.cu
- csrc/sampling.cu
- flashinfer/__init__.py
- flashinfer/logits_processor/operators.py
- flashinfer/sampling.py
- include/flashinfer/sampling.cuh
- tests/test_sampling.py
This adds the fused temperature online softmax kernel to the sampling and logits processor API.
Baseline: [torch.softmax()](https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cuda/SoftMax.cu) on H200
> feat: Fused temperature online softmax kernel

- flashinfer/aot.py
- flashinfer/autotuner.py
- flashinfer/tllm_utils.py
- flashinfer/utils.py
The `trtllm_utils` library also needs symbols from common files, e.g. the `llmException`. Extend the dependencies to link `trtllm_utils.so` with common helpers.
```python
>>> flashinfer.utils.get_trtllm_utils_module()
Traceback (most recent call last):
...
OSError: ...flashinfer/data/aot/trtllm_utils/trtllm_utils.so: undefined symbol: _ZTIN12tensorrt_llm6common13TllmExceptionE
```
Fixes: #1167
> Fix missing symbols in trtllm_utils.so

- docs/api/green_ctx.rst
- flashinfer/green_ctx.py
- flashinfer/utils.py
- tests/test_green_ctx.py
Add `split_device_green_ctx_by_sm_count` to create green context by a list of SM count.
cc @yzh119
> feat: support green ctx creation by a list of SM counts

- csrc/batch_attention.cu
- csrc/batch_attention_customize_config.jinja
- csrc/batch_attention_jit_pybind.cu
- flashinfer/attention.py
- flashinfer/jit/attention/pytorch.py
- include/flashinfer/attention/cascade.cuh
- include/flashinfer/attention/persistent.cuh
- include/flashinfer/attention/persistent_template.cuh
- include/flashinfer/attention/scheduler.cuh
- include/flashinfer/profiler.cuh
- profiler/batch_attention.py
- tests/test_batch_attention.py
This is a follow-up PR on https://github.com/flashinfer-ai/flashinfer/pull/1137, optimizing scheduling balance & reduction overhead, and achieving 2x speedup. Optimization includes:
1. Conduct fewer kv-split on decode requests. This reduces the number of reduction operations needed.
2. Write-through. Attention without kv-split is directly written back into the final buffer without additional copy.
3. Warp-level reduction. Changing CTA-wise reduction into warp-wise reduction increase parallelism, greatly reducing the reduction overhead.
This PR also investigates _**fine-grained gmem barrier**_ as discussed in https://github.com/flashinfer-ai/flashinfer/pull/1137. However, due to the overhead of memory ordering operations, we do not see performance gain on our usecases (static scheduling), …
> [feat] optimize persistent batch attention perf.

- flashinfer/attention.py
- include/flashinfer/attention/scheduler.cuh
- tests/test_batch_attention.py
The mismatch between `kv_chunk_size` and `CTA_TILE_KV` could lead to unmask `nan` value during small batch inference. This PR enforces `kv_chunk_size` to be multiple times of `CTA_TILE_KV` to avoid this case.
> [fix] fix BatchAttention CTA_TILE_KV mask issue

- tvm_binding/batch_decode.cu
- tvm_binding/batch_decode_jit_tvm_binding.cu
- tvm_binding/batch_prefill.cu
- tvm_binding/batch_prefill_jit_tvm_binding.cu
- tvm_binding/batch_prefill_sm90.cu
- tvm_binding/batch_prefill_sm90_jit_tvm_binding.cu
As of now PDL is not introduced in the TVM attention kernel interface, so we remove it from here and use false by default.
> [TVM] Remove `enable_pdl` from TVM binding interface

- flashinfer/comm/trtllm_ar.py
- include/flashinfer/comm/trtllm_allreduce_fusion.cuh
- include/flashinfer/comm/trtllm_moe_allreduce_fusion.cuh
- tests/test_trtllm_allreduce_fusion.py
We add some notes on each api to help integration to vllm/sgl.
And we try to fix the error in issues.
To avoid workspace size overflow, the max lamport communication size MAX_COMM_SIZE (computed as hidden * max_token) should be less than round_down(INT_32_MAX, 2MB). For any larger size, it would be rewritten to this value with a warning "warning: lamport_comm_size 2147483648 is greater than MAX_COMM_SIZE 2145386496, set to MAX_COMM_SIZE".
If the actual lamport communication size (computed as hidden * token_num) exceeds this MAX_COMM_SIZE, always set use_oneshot to be False.
Otherwise, you could set use_oneshot on your preference; and for the min-latency case, set it to be (token_num <= 128).
#1223 
https://github.com/sgl-project/sglang/pull/7621
Thank you for contributing to FlashInfer! …
> fix: add trtllm-allreduce-fusion api notes and fix memory error

- docker/install/install_python_packages.sh
cuda-python is widely used for communication kernels and so on and should be part of our CI docker image.
> docker: add cuda-python to CI docker image

- custom_backend.py
Add the remaining PEP 517 build hooks explicitly, and ensure that they perform the required setup, in order to fix building when the build backend does not query the build dependencies.  For example, this can happen when using:
```
$ python -m build -wn --skip-de
* Building wheel...
running bdist_wheel
[...]
error: package directory 'build/aot-ops-package-dir' does not exist
ERROR Backend subprocess exited when trying to invoke build_wheel
```
Since PEP 517 does not require calling `get_requires*()` hook, and the build backend can invoke `build_*()` immediately instead, override it as well.
> If you are unsure about how to set up `pre-commit`, see [the …
> bugfix: Fix building without `get_requires*()` invocation

- include/flashinfer/vec_dtypes.cuh
This PR tries to fix an issue that occured while enabling fp8 kv-cache support for vllm (https://github.com/vllm-project/vllm/pull/17005).
The issue was that in an generated inc file (e.g. in my case
flashinfer/100/generated/batch_decode_with_kv_cache_dtype_q_bf16_dtype_kv_u8_dtype_o_bf16_dtype_idx_i32_head_dim_qk_128_head_dim_vo_128_posenc_0_use_swa_False_use_logits_cap_False/batch_decode_config.inc
)
we declared DTypeKV to be uint8_t, shown as below:
```
using DTypeKV = uint8_t;
...
struct Params {
...
using DTypeKV = DTypeKV;
...
};
```
Consequently, when we instantiate the vec_ from cast_load_impl defined in vec_dtypes.cuh, i.e.
```
vec_t<src_float_t, vec_size> tmp;
```
src_float_t is instantiated to uint8_t through template parameter T=Params::DTypeKV, where Params::DTypeKV is …
> bugfix: support uint8_t for vec_t class template

- csrc/trtllm_mnnvl_allreduce.cu
- flashinfer/comm/__init__.py
- flashinfer/comm/mnnvl.py
- flashinfer/comm/trtllm_mnnvl_ar.py
- include/flashinfer/comm/trtllm_mnnvl_allreduce.cuh
- tests/test_trtllm_mnnvl_allreduce.py
This PR adds TRT LLM's Multi-Node NVLink All-Reduce kernel. This includes the necessary code to set up the multicast and unicast buffers on the GPU.
- [] I have installed `pre-commit` by running `pip install pre-commit` (or used your preferred method).
- [V] I have run the hooks manually with `pre-commit run --all-files` and fixed any reported issues.
This test requires multiple nodes and can be run as follows:
srun -N2 --container-image=<your_aarch64_container>  --mpi=pmix --container-name=mb_flashinfer …
> [comm] TRT-LLM's Multi-Node NVLink All-Reduce Kernel

- flashinfer/comm/nvshmem.py
- flashinfer/jit/env.py
- Add `get_nvshmem_include_dirs`, `get_nvshmem_lib_dirs`, and `get_nvshmem_ldflags` to flashinfer/jit/env.py, to:
- Allow overriding NVSHMEM include and library paths via NVSHMEM_INCLUDE_PATH and NVSHMEM_LIBRARY_PATH environment variables
- Allow custom linker flags via NVSHMEM_LDFLAGS environment variable
- Fallback to nvidia.nvshmem package paths if environment variables are not set
- Update `flashinfer/comm/nvshmem.py` to use new env functions and support multiple include/library paths and custom linker flags
This enables downstream builds with system NVSHMEM packages and ensures all communication backends can be AOT-compiled.
Fixes #1252
> feat: support environment variable overrides for NVSHMEM paths and linker flags

- docker/install/install_python_packages.sh
Since we added nvidia-nvshmem-cu12 in setup.py, we need to install it in
the CI container image so unit tests can run when the module is loaded.
Related #1260
> CI: install `nvidia-nvshmem-cu12`

- flashinfer/__init__.py
- flashinfer/fp4_quantization.py
- flashinfer/gemm.py
- tests/test_mm_fp4.py
support a/b input type e2m1, block quant type e4m3 with block size 16 output bfloat16 and fp16.
init add mm_fp4 use cudnn backend
> add mm_fp4 use cudnn backend

- flashinfer/profiler/__init__.py
- include/flashinfer/profiler.cuh
- pyproject.toml
Simply add smid into the profiler tag. Now it looks like this 
Also fixed profiler install in pyproject.toml 
cc @happierpig @yzh119 
> [Feature] SM level profiler 

- csrc/trtllm_fmha_kernel_launcher.cu
- csrc/trtllm_fmha_runner.cu
- flashinfer/decode.py
- flashinfer/utils.py
- include/flashinfer/trtllm/fmha/fmhaRunnerParams.h
- include/flashinfer/trtllm/fmha/kernelParams.h
- tests/test_fp4_quantize.py
- tests/test_trtllm_gen_decode.py
- tests/utils_fp4.py
Only added fp4 support to trtllm_batch_decode_with_kv_cache, not added to wrapper yet.
> feat: support output nvfp4 in trtllm-gen function call.

- csrc/trtllm_fused_moe_routing_kernel.cu
When all expert scores are `NaN` or `-INFINITY` the default expert index is returned which is currently -1, and this causes an illegal memory access, changed the default index to 0.
> bugfix: Change default index in routingTopKExperts

- flashinfer/cascade.py
`MultiLevelCascadeAttentionWrapper.plan()` ends up calling `plan()` on `BatchPrefillWithPagedKVCacheWrapper`. `BatchPrefillWithPagedKVCacheWrapper.plan()` supports `kv_data_type` but `MultiLevelCascadeAttentionWrapper.plan()` does not. 
Fixes https://github.com/vllm-project/vllm/issues/21822
> Support passing kv_data_type to MultiLevelCascadeAttentionWrapper.plan()

- flashinfer/prefill.py
- tests/test_trtllm_gen_context.py
- tests/test_trtllm_gen_decode.py
Make the old prefill test cover the direct function call and fp8.
Also add a new prefill test, which is more comprehensive and have very similar structure to decode test, I plan to merge prefill/decode test after added the output_dtype API in prefill test. And we may able to remove the old test
Also fix some wrapper issue captured.
> Add trtllm-gen prefill test. Fix related wrapper issue.

- flashinfer/cudnn/decode.py
- setup.py
- tests/test_cudnn_decode.py
This PR tries to integrate cudnn decode by calling the cudnn kernels directly instead of through the cubin path.
Also, enabled nvidia-cudnn-frontend on all platforms
> Add native cudnn_decode for improved cudnn decode performance

- csrc/trtllm_fmha_kernel_launcher.cu
- flashinfer/decode.py
- flashinfer/prefill.py
- include/flashinfer/trtllm/fmha/fmhaKernels.cuh
- tests/test_trtllm_gen_context.py
- tests/test_trtllm_gen_decode.py
Support nvfp4 for prefill function call. (not wrapper yet)
The nvfp4 test won't pass until the trtllm-gen kernel update as there is a bug that ignored v_scale. I tested locally and will update the kernels latter.
> support trtllm-gen prefill fp4 output

- csrc/fp4_gemm_cutlass.cu
- csrc/fp4_gemm_cutlass.jinja
- csrc/pytorch_extension_utils.h
- flashinfer/gemm.py
- include/flashinfer/arch_condition.h
- include/flashinfer/cutlass_utils.cuh
- include/flashinfer/gemm/cutlass_gemm_configs.h
- include/flashinfer/gemm/fp4_gemm_cutlass.h
- include/flashinfer/gemm/fp4_gemm_cutlass_template.h
- include/flashinfer/gemm/fp4_gemm_template_sm100.h
- tests/test_mm_fp4.py
support a/b input type e2m1, block quant type e4m3 with block size 16 output bfloat16 and fp16.
add mm_fp4 use trtllm cutlass backend. those kernels are known to have better perf for large bs. 
> add cutlass backend for mm_fp4

- tests/test_groupwise_scaled_gemm_mxfp4.py
`fp4_swizzle_blockscale_sm100` function was removed in #1214 and thus breaking tests/test_groupwise_scaled_gemm_mxfp4.py unittest, this PR fixes the issue.
cc @ttyio @azhurkevich
> hotfix: update mxfp4 groupwise-scaled gemm unittests

- csrc/fused_moe/cutlass_backend/cutlass_fused_moe_kernels.cuh
cutlass fused moe modules are broken after https://github.com/flashinfer-ai/flashinfer/pull/1355 because the structure of `FP4QuantizationSFLayout` has changed. This PR fixes the issue.
cc @wenscarl @ttyio
> bugfix: fixed cutlass fused moe usage of FP4QuantizationSFLayout::SWIZZLED

- flashinfer/jit/cpp_ext.py
On AArch64, the order matters for the linker
> Fix flag order

- include/flashinfer/sampling.cuh
Fix compilation issue on gb200 due to shared mem alignment conflict.
https://github.com/flashinfer-ai/flashinfer/issues/1400
> fix shared memory alignment conflict in sampling.cuh

- csrc/trtllm_moe_allreduce_fusion.cu
[bugfix] Fix compilation failure when compiling csrc/trtllm_moe_allreduce_fusion.cu
This file includes FP4QuantizationSFLayout from
`flashinfer/comm/trtllm_moe_allreduce_fusion.cuh` which still uses the old format.
> [bugfix] Fix compilation failure when compiling csrc/trtllm_moe_allreduce_fusion.cu

- flashinfer/aot.py
This change integrates the `gen_nvshmem_module` into the Ahead-of-Time (AOT) build process.
By including this module, users can now pre-compile the NVSHMEM-based communication kernels,
which is necessary for using this backend in environments where just-in-time compilation
is not available or desired.
Fixes #1260
> feat(aot): add nvshmem module for aot compilation

- setup.py
The dependency is not required because:
* For x86_64 user environments that installs pytorch from pypi, nvidia-nvshmem-cu12 is already a torch dependency
(https://github.com/pytorch/pytorch/blob/3f1636ebef9b45e8a3cb0eb20d327ee6acb74be0/.github/scripts/generate_binary_build_matrix.py#L44-L95),
and flashinfer depends on torch, there is no need to specify another nvidia-nvshmem-cu12 dependency in flashinfer.
* For user environments where nvidia-nvshmem-cu12 is not a torch dependency (like in nvidia's pytorch container),
nvshmem is installed at system wide.
Fixes #1387
> If you are unsure about how to set up `pre-commit`, see [the pre-commit …
> install: remove nvidia-nvshmem-cu12 from package dependency

- flashinfer/decode.py
- flashinfer/prefill.py
- tests/test_trtllm_gen_context.py
- tests/test_trtllm_gen_decode.py
We do need k,v scale !=1 for llama3 fp4 model.
> Fix missing v_scale for prefill wrapper.

- benchmarks/routines/attention.py
- flashinfer/prefill.py
- tests/test_cudnn_prefill.py
- [x ] I have installed the hooks with `pre-commit install`.
> Allow BatchPrefillPagedWrapper to call cudnn API

- tests/test_fp4_quantize.py
- tests/test_trtllm_gen_context.py
- tests/test_trtllm_gen_decode.py
- tests/test_trtllm_gen_fused_moe.py
- tests/utils_fp4.py
- add mxfp4 quantization unit test
- add mxfp4 x mxfp8 and mxfp4 x bf16 moe unit test
> Add Mxfp4 trtllm-gen moe unit tests

- csrc/trtllm_fused_moe_kernel_launcher.cu
Verify that `num_experts >= local_num_experts + local_expert_offset` to avoid Illegal memory access.
Currently when calling `fused_moe.trtllm_fp8_per_tensor_scale_moe` with `local_num_experts+local_expert_offset > num_experts`, it results in a `CUDA: Illegal memory access`.
> bugfix: Verify num_experts greater or equal to local_experts + offset

- include/flashinfer/attention/mla_hopper.cuh
Seeing the following error on GB200 on https://github.com/flashinfer-ai/flashinfer/blob/fe442a2df64f46b021f3ad2bc184cd10b09b1d7d/include/flashinfer/attention/mla_hopper.cuh#L829
```
flashinfer/attention/mla_hopper.cuh(829): error: more than one operator "/" matches these operands:
built-in operator "arithmetic / arithmetic"
function "flashinfer::operator/(uint32_t, const flashinfer::uint_fastdiv &)" (declared at line 85 of flashinfer/attention/../fastdiv.cuh)
operand types are: IdType / const flashinfer::uint_fastdiv
(CAUSAL ? min(kv_end, kv_len - q_len + packed_qo_start / num_heads) : kv_end) /
^
detected during:
instantiation of "void flashinfer::mla::hopper::BatchMLAPageAttentionHopperKernel<KTraits,Params>(Params) [with KTraits=flashinfer::mla::hopper::HopperKernelTraits<true, 2U, …
```
> Fix "more than one operator "/" matches these operands"

- flashinfer/fused_moe/core.py
Change CUTLASS kernels JitSpec name as to not collide with `trtllm` FusedMoE name.
Currently, in a python session we can't both `trtllm` FusedMoE backend, and CUTLASS backend at the same time, this PR enables this support.
> feat: Enable multiple fused-moe backends

- flashinfer/jit/cubin_loader.py
The level of verbosity when downloading cubins is on the high-side (3 messages for each file).
It also reports a "Failed to load ..." which confuses some users into thinking that something went wrong.
> Tone down the amount of logging when downloading cubins

- flashinfer/fused_moe/core.py
- tests/test_trtllm_gen_fused_moe.py
Fix the missing `enable_pdl` argument introduced in #1446 .
> fix missing enable_pdl argument in trtllm-gen fp4 moe

- flashinfer/decode.py
- flashinfer/prefill.py
- flashinfer/utils.py
- tests/test_trtllm_gen_attention.py
- tests/utils_fp4.py
Fixed the shape checking for FP4 scale factor tensor. After #1363, we could pass `o_sf_start_index` to write the scale factor shared by prefill and decode kernel. Current implementation still assumes the batch dim of scale factor tensor is the same with query, but it should be a combination of both prefill and decode scale. This PR fixed the checking, as well as do the correct swizzling recovery.
> Fix TRTLLM NVFP4-out attention kernel scale factor dim issue

- flashinfer/gemm.py
- tests/test_bmm_fp8.py
add "auto" backend and autotune tactics among cutlass, cudnn and cublas.
> refactor: unify autotuner for bmm_fp8

- flashinfer/cute_dsl/blockscaled_gemm.py
This PR updates the documentation to clarify that `m32 * m4 * rm`, `n32 * n4 * rn`, and `k4 * rk` correspond to `M`, `N`, and `K` respectively, where each is padded to the nearest multiple of 128 (or 4 for `K`).
> doc: Update the masked grouped gemm doc

- csrc/fp8_gemm_cutlass.cu
- flashinfer/gemm.py
- include/flashinfer/gemm/fp8_gemm_cutlass.h
- include/flashinfer/gemm/fp8_gemm_cutlass_template.h
- include/flashinfer/gemm/fp8_gemm_template_sm100.h
Previous cutlass implementation require combine of scale_a/scale_b in the python, so extra aten kernel is used which may cost 1us. Now we support separate alpha_a and alpha_b in epilog, to avoid this extra aten kernel.
> Perf: support scale_a/scale_b instead of combined scale in cutlass bmm_fp8

- flashinfer/cute_dsl/blockscaled_gemm.py
- flashinfer/cute_dsl/utils.py
- tests/test_cute_dsl_blockscaled_gemm.py
The kernel interface exposed in #1331 is not friendly for JIT caching and mix the compile time parameters and runtime arguments. This PR refactors these classes following these rules:
1. Compile time parameters should be passed to `__init__` functions.
2. Use `@cute.kernel` to decorate device-side kernels.
3. Use `@cute.jit` to decorate host-side launcher functions (https://docs.nvidia.com/cutlass/media/docs/pythonDSL/cute_dsl_general/dsl_introduction.html), where we can call device-side kernels.
4. `cute.compile` accepts a host-side launcher function decorated by `@cute.jit`.
https://github.com/flashinfer-ai/flashinfer/issues/1519
> If you are unsure about how …
> refactor fp4 masked gemm cute-dsl implementation and add manual cache

- custom_backend.py
When building flashinfer-python with AOT enabled, we need the 'requests'
package otherwise it fails with missing packages when importing modules.
Fixes #1516
> fix: add missing 'requests' when building the package with AOT

- flashinfer/artifacts.py
- flashinfer/decode.py
- flashinfer/jit/__init__.py
- flashinfer/jit/attention/pytorch.py
- flashinfer/jit/cubin_loader.py
- flashinfer/prefill.py
- include/flashinfer/cubin_loader.h
- include/flashinfer/trtllm/fmha/cubin/kernelMetaInfo.h
- include/flashinfer/trtllm/fmha/fmhaKernels.cuh
- include/flashinfer/trtllm/fmha/kernelParams.h
- tests/test_trtllm_gen_attention.py
This reverts commit 7812a779776ba104a99bf9fa45865ff23c582234.
Revert #1518 because it relies on cubins built for cuda 13 and not compatible for cuda-12 based user environment.
Will bring it back once artifactory for both cuda-12 and cuda-13 is ready.
> Revert "backend: Refactor trtllm-gen fmha metainfo loading (#1518)"

- include/flashinfer/sampling.cuh
Fixed a typo in `sampling.cuh` line 1418 where `args[]` was declared with 7 parameters, including a duplicate `&d`, while `SamplingFromProbKernel` only accepts 6. Removed the redundant `&d` parameter.
https://github.com/flashinfer-ai/flashinfer/issues/1544#issuecomment-3213659293
> Fix typo in sampling.cuh: Remove duplicate parameter

- include/flashinfer/comm/trtllm_allreduce_fusion.cuh
twoshot kernel use 80 registers per thread, and H20 has 64k registers per sm, so num_threads should be set less than 819.
This pr use register_num to calculate limit for num_threads.
> fix trtllm_allreduce_fusion twoshot register problem.

- csrc/fused_moe/cutlass_backend/cutlass_fused_moe_kernels.cuh
- flashinfer/aot.py
- flashinfer/fp4_quantization.py
- tests/test_fp4_quantize.py
This fixes an OOB issue in the fused MoE and creates a separate sm90 and sm100 path fp4 quantization.
fix required for https://github.com/vllm-project/vllm/pull/23369
> fix: separate out fp4 lib into sm90 and sm100 versions, add oob checking in fused moe

- include/flashinfer/attention/persistent.cuh
- scripts/task_jit_run_tests_part4.sh
- tests/jit_utils.py
- tests/test_batch_attention.py
An explicit `__syncthreads` is required for guarantee correctness on blackwell, otherwise unittests will fail.
Also add `test_batch_attention` unittests to CI.
cc @Edenzzzz @happierpig
> bugfix: fix persistent attention kernel correctness on blackwell

- Jenkinsfile
- csrc/fused_moe/cutlass_backend/cutlass_fused_moe_kernels.cuh
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/cutlass_type_conversion.h
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/include/moe_gemm_kernels.h
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/include/moe_kernels.h
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/moe_gemm/moe_gemm_kernels_bf16_fp4.cu
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/moe_gemm/moe_gemm_kernels_fp16_fp4.cu
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/moe_gemm/moe_gemm_template_dispatch.h
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/moe_gemm/moe_gemm_template_dispatch_tma_ws.h
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/moe_gemm/moe_gemm_template_dispatch_tma_ws_mixed_dtype.h
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/moe_gemm/moe_tma_warp_specialized_traits.h
- csrc/nv_internal/tensorrt_llm/thop/fp4Op.cpp
- csrc/pytorch_extension_utils.h
- flashinfer/aot.py
- flashinfer/fp4_quantization.py
- flashinfer/fused_moe/core.py
- flashinfer/jit/cpp_ext.py
- flashinfer/jit/cutlass_gemm/generate_kernels.py
- include/flashinfer/cutlass_utils.cuh
- scripts/task_test_aot_build_import.sh
As reported in https://github.com/flashinfer-ai/flashinfer/pull/1557#issuecomment-3217441569, our UT do not cover the cuda 12.6 environment, this PR fixes the issue by adding cu126/cu128/cu129 UT to CI.
https://github.com/flashinfer-ai/flashinfer/pull/1557#issuecomment-3217441569
cc @yongwww @zhyncs
> ci: add unittest for different cuda version

- benchmarks/README.md
- benchmarks/routines/moe.py
Add autotuning support for moe benchmark scripts. The support is for CUTLASS and TRTLLM nvfp4 moe.
> benchmark: Add autotunner to moe benchmark

- include/flashinfer/comm/trtllm_allreduce_fusion.cuh
- include/flashinfer/comm/trtllm_moe_allreduce_fusion.cuh
- include/flashinfer/cutlass_utils.cuh
It's off by 10x.
Maybe one day we'll see cuda 120 :)
> bugfix: fix cuda version guard macros

- flashinfer/decode.py
- flashinfer/prefill.py
Instead of directly use `query.dtype` as `out_dtype`, we could infer the `out_dtype` from `out.dtype` if `out` is passed into the API.
tests/test_trtllm_gen_attention.py::test_trtllm_batch_prefill:
`==== 972 passed, 4 warnings in 47.94s ====`
tests/test_trtllm_gen_attention.py::test_trtllm_batch_decode:
`==== 2592 passed, 15 warnings in 88.27s (0:01:28) ====`
> feat: Support for inferring out_dtype from out.dtype for TRTLLM attention kernel

- csrc/trtllm_batched_gemm_runner.cu
- csrc/trtllm_fused_moe_kernel_launcher.cu
- csrc/trtllm_fused_moe_routing_deepseek.cu
- csrc/trtllm_fused_moe_routing_llama4.cu
- csrc/trtllm_fused_moe_routing_renormalize.cu
- csrc/trtllm_fused_moe_runner.cu
Fixed arg passing to `TORCH_CHECK` and `TORCH_WARN` macros, as they don't support printf style formatting.
> bugfix: Fix arg passing to TORCH_CHECK and TORCH_WARN macros

- tests/test_fp4_quantize.py
`test_fp4_quantize` currently has failures on SM100. This PR fixes those failures by using a different unswizzling helper function. Separately, I'd like to understand why there are multiple unswizzling helpers, but to simplify things, I'm not refactoring in this PR.
I also changed the skip reasons in this test file to explicitly say that there's a min CUDA version for NVFP4, because that was an issue I had in my environment that wasn't immediately obvious from the current skip reason.
None that I know of.
- [ ✅ ] I have installed `pre-commit` by running `pip install pre-commit` (or used your preferred method).
- [ ✅ ] I have installed the hooks with `pre-commit install`.
- [ ✅ ] I have run the hooks manually with `pre-commit run --all-files` and fixed any reported issues.
I've tested …
> bugfix: Fix test_fp4_quantize test bug

- csrc/trtllm_fused_moe_routing_llama4.cu
- csrc/trtllm_fused_moe_routing_renormalize.cu
- flashinfer/fused_moe/core.py
- remove `.to(torch.bfloat16)` which causes illegal memory access when using deepseek v3 routing.
- handle the case when `routing_logits` is `None` to support `trtllm_fp4_block_scale_routed_moe`
- fix the `invalid argument` error in llama and renormalize routing
> update trtllm-gen fp4 autotuner and routing

- flashinfer/comm/mnnvl.py
- flashinfer/comm/trtllm_alltoall.py
- tests/test_mnnvl_custom_comm.py
Make Mnnvl memory initialization independent of mpi4py communicator.
Depends by https://github.com/flashinfer-ai/flashinfer/pull/1550
> Mnnvl memory with custom communicator

- include/flashinfer/sampling.cuh
On blackwell, we will encounter `failed with error code too many resources requested for launch` (register overflow) issue when using the `TopKRenormProbKernel` (another issue that only happens on blackwell). This PR fixes the issue by reducing the loop unroll number to reduce the number of registers used in the kernel.
This PR is based upon #1596 , these two PRs together will fix the failed UTs on blackwell.
cc @bkryu
> bugfix: fix the register overflow issue for topk renorm kernels on blackwell

- flashinfer/utils.py
test_fp8_quantize unittest is broken by #1446 because we didn't check the special case of cpu input.
> bugfix: fix unittest test_fp8_quantize

- tests/test_create_ipc_buffer.py
- tests/test_nvshmem_allreduce.py
- tests/test_trtllm_allreduce.py
- tests/test_trtllm_allreduce_fusion.py
- tests/test_trtllm_moe_allreduce_fusion.py
- tests/test_trtllm_moe_allreduce_fusion_finalize.py
- tests/test_vllm_custom_allreduce.py
Tests should return "skipped" when current environment is not supported instead of returning a failure.
Current PR replaces raise errors to pytest.skip in test scripts
> bugfix: fix multi-gpu/node unit-test: skip when there aren't enough GPUs instead of failing

- csrc/nv_internal/tensorrt_llm/kernels/quantization.cuh
Fixed the fp4 quantization with 8x4 scale factor layout.
> bugfix: fix fp4 quantization with 8x4 scale factor layout

- scripts/task_test_aot_build_import.sh
Previously, MAX_JOBS was calculated but not exported, causing the build system to use all available CPU cores for parallel compilation.
> fix: export MAX_JOBS for AOT build

- include/flashinfer/attention/persistent.cuh
- include/flashinfer/attention/scheduler.cuh
- tests/test_batch_attention.py
This PR fixes precision issues of BatchAttention (Persistent FA2 of https://github.com/flashinfer-ai/flashinfer/pull/1137), when `CTA_TILE_Q` is not a multiple of `gqa_group_size` (e.g., Qwen family models). Prior implementation assumes that all `qo_heads` of a `kv_head` on a specific token will all be split-kv or non-split-kv. However, when `gqa-group-size == 7`, some `qo_heads` can be non-split while the remaining can be split.
cc @Edenzzzz
> bugfix: fix merge_attention_state in BatchAttention w/ gqa-group-size in Qwen family

- csrc/gemm_groupwise_sm120.cu
- csrc/gemm_groupwise_sm120_kernel_inst.jinja
- csrc/gemm_sm120_pybind.cu
- csrc/group_gemm_fp8_groupwise_sm120.cu
- csrc/group_gemm_fp8_groupwise_sm120_kernel_inst.jinja
- csrc/group_gemm_sm120_pybind.cu
- flashinfer/gemm.py
- flashinfer/utils.py
- include/flashinfer/cutlass_utils.cuh
- include/flashinfer/gemm/gemm_groupwise_sm120.cuh
- include/flashinfer/gemm/group_gemm_fp8_groupwise_sm120.cuh
- tests/test_groupwise_scaled_gemm_fp8.py
It depends on https://github.com/flashinfer-ai/flashinfer/pull/1608, mainly the cutlass fp8 gemm support for sm120/121, will rebase after #1608 lands.
> feat: cutlass fp8 gemm bringup for SM120 & SM121

- csrc/trtllm_batched_gemm_runner.cu
- flashinfer/artifacts.py
- flashinfer/fused_moe/core.py
- include/flashinfer/trtllm/batched_gemm/trtllmGen_bmm_export/GemmOptions.h
- tests/test_trtllm_gen_fused_moe.py
Enable splitK for trtllm-gen fused moe.
Make autotuner for trtllm-gen fp4 fused moe more robust.
Add autotuner for trtllm-gen fused moe test.
> perf: Enable SplitK and fix autotuner for trtllm fp4 fused moe

- docker/install/install_python_packages.sh
- setup.py
The following warning info can be hidden by switching the package `pynvml` to `nvidia-ml-py`.
```
.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:61: 
FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. 
If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
import pynvml  # type: ignore[import]
```
The Usage remains the same.
Ref: https://pypi.org/project/pynvml/ and https://pypi.org/project/nvidia-ml-py/
Relevant reproducible detail:
```
$ uv pip list | grep -E "(torch|flashinfer)"
flashinfer-python                 0.3.1
torch                             2.7.1
torchaudio                        2.7.1
torchvision                       0.22.1
```
> chore: Switch `pynvml` to `nvidia-ml-py`

- tvm_binding/tvm_binding_utils.h
The latest TVM ffi refactor renames `NDArray` to `Tensor`, to align with the terminology in PyTorch. This PR updates flashinfer tvm binding with the rename.
https://github.com/apache/tvm/pull/18275
N/A
N/A
N/A
> [TVM] Rename `NDArray` -> `Tensor`

- flashinfer/jit/core.py
> Tiny allow compiling with line info and release moe

- benchmarks/bench_tgv_gemm.py
- csrc/tgv_gemm.cu
- csrc/tgv_gemm.jinja
- flashinfer/__init__.py
- flashinfer/aot.py
- flashinfer/gemm.py
- include/flashinfer/gemm/tgv_gemm.cuh
- include/flashinfer/gemm/tgv_gemm_configs.h
- include/flashinfer/gemm/tgv_gemm_template.h
- scripts/codeowner_analyzer.py
- tests/test_tgv_gemm.py
We are adding a new BF16 GEMM backend named TGV as a more performant alternative to cuBLAS on small problem sizes. TGV GEMMs are optimized for minimum latency use cases and shown to achieve up to 60% speedup on B200 (gpcclk=1800MHz) compared to cuBLAS in our unit tests (see attached table). 
N/A
> TGV GEMM as a BF16 backend alternative to cuBLAS

- include/flashinfer/attention/decode.cuh
- tests/test_jit_example.py
I noticed that only prefill kernels use `variant.OutputTransform()`. This PR replaces `state.normalize()` in decode kernels with `variant.OutputTransform()` to match the behavior of prefill kernels, as well as enabling customizing decode kernels.
I don't have much experience working with the FlashInfer codebase, so feedback is welcome.
My goal is to enable `v_scale` epilogue fusion for FP8 KV-cache https://github.com/flashinfer-ai/flashinfer/blob/6dff34d1b8aadec626bd507715a5f45999458329/flashinfer/decode.py#L572
<details>
<summary>Test snippet (let me know if I need to add this test somewhere)</summary>
```python
from flashinfer.decode import (
single_decode_with_kv_cache_with_jit_module,
BatchDecodeWithPagedKVCacheWrapper,
)
from flashinfer.jit.attention import ( …
```
> feat: Add `variant.OutputTransform()` to decode kernels

- flashinfer/artifacts.py
- flashinfer/deep_gemm.py
- tests/test_groupwise_scaled_gemm_fp8.py
Fix failed with KeyError: '103a' for deepGEMM backend tests (groupwise gemm): `tests/test_groupwise_scaled_gemm_fp8.py::test_fp8_groupwise_batch_deepgemm_masked` and `tests/test_groupwise_scaled_gemm_fp8.py::test_fp8_groupwise_group_deepgemm` 
> Update deepgemm backend for 103a

- flashinfer/gemm.py
- tests/test_mm_fp4.py
While the mx_fp4 format uses per-block scales only, some cases do benefit from having a global scale to avoid truncating the range. This PR enables this and makes the following changes:
* construct the cuDNN graph with a global scale if one is provided
* Adjust the mm_fp4 API with an explicit use_nvfp4 bool: previously the API could use the presence of an "alpha" factor to distinguish between nvfp4 (required global scale) and mx_fp4 formats. Now we have an explicit parameter to indicate this: use_nvfp4.
This change was decided after a feedback discussion with the requester of [issue #1592](https://github.com/flashinfer-ai/flashinfer/issues/1592).
> If you are …
> gemm: Enabled alpha with the mx_fp4 format

- include/flashinfer/attention/prefill.cuh
- scripts/task_jit_run_tests_part4.sh
- tests/test_batch_prefill_kernels.py
1. xfail the prefill + cudagraph UT, until we fully fix the workspace overflow issues.
2. fixes the correctness of pageattention + custom mask
3. add tests/test_batch_prefill_kernels.py to public CI
cc @nvmbreughe @yongwww
> ci: fix prefill attention unittests

- benchmarks/routines/flashinfer_benchmark_utils.py
- benchmarks/routines/gemm.py
- flashinfer/gemm.py
Current PR:
* `flashinfer_benchmark.py` enhancements:
* Adds `--autotune` support for `mm_fp4` and `bmm_fp8` benchmarking (trtllm and cutlass backends)
* Adds `mxfp4` support for `mm_fp4` benchmarking.
* Restores `mm_fp4`'s default behavior that was changed in [PR1688](https://github.com/flashinfer-ai/flashinfer/pull/1688/files#diff-fe40099e55becd25fe2ccadfdb739eabc95308bc9e80fda26c1ad5db0bbc3f92R2008): 
* The `use_nvfp4` input argument was added in PR1688 and set to `False` by default. The `mm_fp4` behavior prior to PR1688 is always using nvfp4, which led to breaking existing `mm_fp4` usages. Current PR sets the default True.
> If you are unsure about how to …
> feat: Benchmark mm_fp4 mxfp4 support and gemm autotune support.  Restore mm_fp4 API behavior

- flashinfer/jit/cpp_ext.py
- flashinfer/jit/env.py
This PR removes some dependencies on `torch.utils.cpp_extension":
1. After #1608 , we should no longer rely on `_get_cuda_arch_flags`, this PR fixes the issue.
2. Remove dependency on `_get_pybind11_abi_build_flags` as mentioned in https://github.com/flashinfer-ai/flashinfer/issues/1591.
After #1641 we will remove all dependencies on `torch.utils.cpp_extension`.
#1591 
> misc: remove unused `torch.utils.cpp_extension` dependencies

- csrc/fmhaReduction.cu
- flashinfer/artifacts.py
- flashinfer/jit/attention/pytorch.py
- include/flashinfer/trtllm/common/cudaUtils.h
- include/flashinfer/trtllm/fmha/fmhaKernels.cuh
- include/flashinfer/trtllm/fmha/fmhaReduction.h
- include/flashinfer/trtllm/fmha/fmhaRunnerParams.h
- include/flashinfer/trtllm/fmha/kernelUtils.h
- tests/test_attention_sink_blackwell.py
This also updated the kernels which fixed mha perf regression and fp8 sink attention accuracy issue.
> perf: Port the separate reduce kernel mode from trtllm.

- .pre-commit-config.yaml
- flashinfer-cubin/.gitignore
- flashinfer-cubin/MANIFEST.in
- flashinfer-cubin/build_wheel.py
- flashinfer-cubin/download_cubins.py
- flashinfer-cubin/flashinfer_cubin/__init__.py
- flashinfer-cubin/pyproject.toml
- flashinfer-cubin/setup.py
- flashinfer/__init__.py
- flashinfer/artifacts.py
- flashinfer/jit/env.py
- pyproject.toml
User prefers a standalone wheel for cubin files in flashinfer, this PR implements this feature.
> ci/cd: bring up flashinfer-cubin package

- flashinfer/jit/core.py
Add device debug information and disable cuda kernel optimization in verbose mode.
N/A
> disable optimization and add more debug information during verbose mode

- docker/Dockerfile.cu130
This PR bumps the base image of [flashinfer-ci-cu130](https://hub.docker.com/r/flashinfer/flashinfer-ci-cu130) from [nvidia/cuda:13.0.0-devel-ubuntu24.04](https://hub.docker.com/layers/nvidia/cuda/13.0.0-devel-ubuntu24.04/images/sha256-435220c0fef35cbf712e11999f8670a83835ef3cdd18564e5e8122f83078c88c) to [nvidia/cuda:13.0.1-devel-ubuntu24.04](https://hub.docker.com/layers/nvidia/cuda/13.0.1-devel-ubuntu24.04/images/sha256-84e5f33efdccadc21599978ea7e6ed80cbe19bb432f9c339b15a66c4025ac983)
The updated base image container contains the CUDA Toolkit 13.0 Update 1
> If you are unsure about how to set up `pre-commit`, see [the pre-commit …
> Bump base container image from 13.0.0 to 13.0.1 for cu130 container

- docker/install/install_python_packages.sh
Current `flashinfer-ci-cu[12x, 130]` containers all install [nvidia-cudnn-cu12](https://pypi.org/project/nvidia-cudnn-cu12/). However, in CUDA 13 environments,  [nvidia-cudnn-cu13](https://pypi.org/project/nvidia-cudnn-cu13/) should be installed.
The PR modifies `install_python_packages.sh` such that if CUDA 13 is used, `nvidia-cudnn-cu13>=9.12.0.46` is installed (note that [9.12.0.46](https://pypi.org/project/nvidia-cudnn-cu13/#history) is the earliest version)
> fix: CI containers install nvidia-cudnn-cu12 vs. nvidia-cudnn-cu13 based on CUDA Version

- tests/test_cudnn_prefill.py
Slightly increase `atol` from `2e-3` to `3e-3` to pass the unit test.
Also, explicitly specify the backend to make reference choice deterministic. 
> hotfix: slightly bump up `atol` to `3e-3` to pass `test_cudnn_prefill` on B40

- tests/test_trtllm_gen_attention.py
Fix failing tests in` tests/test_trtllm_gen_attention.py::test_trtllm_batch_prefill ` and `tests/test_trtllm_gen_attention.py::test_trtllm_batch_decode` due to `AssertionError: Tensor-likes are not close!`. An example error message was (all the failing tests had similar error messages): 
```
E       AssertionError: Tensor-likes are not close!
E
E       Mismatched elements: 1 / 169269760 (0.0%)
E       Greatest absolute difference: 2.0 at index (60221, 1, 77) (up to 1.0 allowed)
E       Greatest relative difference: 1.0 at index (60221, 1, 77) (up to 0.4 allowed)
```
which suggests that this is not a functional bug, but the testing could be relaxed to allow for a small number of mismatches (in this case, 1 out of 169 million elements), especially since the abs/rel difference is not wildly …
> Fix tests/test_trtllm_gen_attention.py::test_trtllm_batch_prefill, ::test_trtllm_batch_decode mismatch error

- flashinfer/artifacts.py
- tests/test_attention_sink_blackwell.py
- tests/test_trtllm_gen_attention.py
Update trtllm-gen cubin to fix accuracy regression about sink.
Integrate sink test to attention test as the old sink test didn't test and catch the fp8 accuracy issue before.
Clean up attention test code.
Attention test case has inflated a lot as param num raise. Reduce by using pairwise combination instead of Cartesian product.
> Fix sink attention accuracy regression, add sink test and cleanup.

- flashinfer/deep_gemm.py
- flashinfer/gemm.py
- tests/test_groupwise_scaled_gemm_fp8.py
skip test_fp8_groupwise_group_deepgemm and test_fp8_groupwise_group_deepgemm where SM not 100 and 103, add relevant checks in library
> tests: skip non SM100/103 for grouped deepgemm

- flashinfer/gemm.py
- flashinfer/utils.py
- tests/test_mm_fp4.py
* A library bug is prevening mx_fp4 matmul on SM120
* While waiting for the patch, this test is now xfailed
* Added a LibraryError class was added to handle these issues in general
- [V] I have installed the hooks with `pre-commit install`.
- [V] Tests have been added or updated as needed.
> Added xfail for mx_fp4 matmul on SM120

- tests/test_trtllm_gen_fused_moe.py
This is to add kimi k2 problem size to unit test.
num of experts is 384
top_k is 8
The support for kimi k2 moe is added w/ [PR 1696](https://github.com/flashinfer-ai/flashinfer/pull/1696)
> add test case for trtllm gen fused moe with kimi k2 problem sizes

- flashinfer/decode.py
- tests/conftest.py
- tests/test_mla_decode_kernel.py
test_mla_decode_kernel.py::test_mla_decode_kernel uses use_tensor_cores=false, which calls the internal sm80 MLA decode kernel, which doesn't support B40 chips (sm120).
This change adds checks to the test to skip when running on B40, and in the code before calling the internal sm80 MLA decode kernel to return a better error message. 
- [ x] I have installed `pre-commit` by running `pip install pre-commit` (or used your preferred method).
- [ x] I have installed the hooks with `pre-commit install`.
- [ x] I have run the hooks manually with `pre-commit run --all-files` and fixed any reported issues.
> If you are unsure about how to set up `pre-commit`, see [the …
> Waive / disable test_mla_decode_kernel.py::test_mla_decode_kernel for not sm80 

- flashinfer/jit/cubin_loader.py
This PR removes cleanup of filelock files after downloading cubins, it may cause race conditions in concurrent environments where multiple processes might be downloading the same cubin simultaneously.
The filelock library already has robust internal mechanisms to handle lock cleanup. By removing the manual cleanup in  the finally block, we allow filelock to manage its own lock files correctly. This prevents race conditions where one process might delete a lock file while another process is still using it, especially in concurrent download scenarios. …
> bugfix: remove the filelock cleanup logic in cubin_loader.py

- flashinfer/decode.py
- flashinfer/sampling.py
- tests/test_sampling.py
This adds the `_check_tensor_params` function in `sampling.py` that is used in the different sampling functions to check that the parameters make sense for this function (see related issues). This also adds some `dtype` validation checks in `decode.py` to make sure we don't silently produce wrong results when passing in the wrong `dtype`. 
I tried to make just one small function that would cover the cases. But please let me know if there is a case I missed. Looking forward to the feedback. 
This was originally from this issue https://github.com/flashinfer-ai/flashinfer/issues/1634 that showed that we can pass relatively bogus inputs to sampling function and get wrong output. Now, when running his code, only the first case passes, which seems correct to me. The second case is passing a 2D …
> fix: add _check_tensor_params to check correct sampling parameters and dtype validation in decode.py

- flashinfer/autotuner.py
The code assume the `opt_shapes` got from `spec.gen_tuning_buckets` is non-decreasing order, but actually the tuning config like [HERE](https://github.com/flashinfer-ai/flashinfer/blob/f21f94abab89a3c5193e38cfdc0edae3c9dd790c/flashinfer/fused_moe/core.py#L531) can use decreasing order, which make the min shape bigger than max shape.
Since current code base don't use the min max value. So it didn't bring issue yet.
> Fix autotune profile min shape bigger than max shape.

- flashinfer/jit/cpp_ext.py
Change the logic of `get_cuda_version`: when nvcc is not installed, return torch.version.cuda, this patch could unblock #1781 .
#1781 
cc @Flynn-Zh
> hotfix: make aot wheel work without nvcc

- csrc/cudnn_sdpa_kernel_launcher.cu
- docker/install/install_python_packages.sh
- flashinfer/artifacts.py
- flashinfer/deep_gemm.py
- flashinfer/fused_moe/core.py
- flashinfer/gemm.py
- flashinfer/jit/attention/modules.py
- flashinfer/jit/cubin_loader.py
- include/flashinfer/trtllm/batched_gemm/trtllmGen_bmm_export/BatchedGemmInterface.h
- include/flashinfer/trtllm/fmha/fmhaKernels.cuh
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/GemmInterface.h
- tests/test_artifacts.py
Encountered some issues when adding some cubin's. This change set and tests should ensure future contributors do not run into the same issues.
- Warp `urljoin` into a helper which joins URLs independently of the presence of a trailing slash
- Add unit tests for this utility and the functions that use it
> chore: improved URL handling for CUBIN/artifacts downloads

- csrc/nv_internal/cpp/kernels/quantization.cu
- csrc/nv_internal/tensorrt_llm/kernels/quantization.cuh
- csrc/nv_internal/tensorrt_llm/kernels/quantization.h
- csrc/nv_internal/tensorrt_llm/thop/fp4Quantize.cpp
- csrc/nv_internal/tensorrt_llm/thop/fp4Quantize.h
- docs/api/fp4_quantization.rst
- flashinfer/__init__.py
- flashinfer/activation.py
- flashinfer/fp4_quantization.py
- tests/utils/test_fp4_quantize.py
This PR quantizes the tensor to NVFP4 along with the associated scales, making it directly usable by FlashInfer’s grouped_gemm_nt_masked.
Note: Leave the [permutation](https://github.com/sgl-project/sglang/pull/9200/files#diff-2ca2a4489a09cea1af7ccc5c59ba92c5d6acf9feb931ed0351128bbfe1a0052eR360) to framework . 
cc @kaixih
> Masked batch nvfp4 quantization

- csrc/nv_internal/tensorrt_llm/kernels/quantization.cuh
- tests/utils/test_fp4_quantize.py
Add per-expert global scaling factor for fp4 batched quantize
> [Quantization] Add per-expert global scaling factor for fp4 batched quantize

- .github/workflows/release-ci-docker.yml
- Jenkinsfile
Previously, FlashInfer CI Docker images only maintained a 'latest' tag, making it difficult to rollback to older images when regressions occur. This PR add the tag with date-sha.
> docker: add image tags with date-SHA suffix

- flashinfer/__main__.py
- tests/cli/test_cli_show_config.py
I believe the show-config command line option was broken by #1794, because it change the return type of `get_artifacts_status` from a list of size 3 tuples to a tuple of size 2 tuples. This code in `__main__.py` expects the former:
```
status = get_artifacts_status()
num_downloaded = sum(1 for _, _, exists in status if exists)
total_cubins = len(status)
```
This PR has a fix and a test to protect against future breaks.
Is this the right place to add CLI tests? Note that I've added a `tests/cli` subdirectory.
> bugfix: show-config command

- flashinfer/fused_moe/core.py
- flashinfer/gemm.py
- flashinfer/jit/attention/modules.py
- flashinfer/jit/cpp_ext.py
This PR add `-lcuda` to default ldflags instead of making it optional.
> jit: add `-lcuda` to default ldflags

- Jenkinsfile
- ci/docker-tags.yml
Followup of #1839 , this PR created a `docker-tags.yml` (placed under `ci/`) file to specify the tag used for each docker image, format:
```
image: tag
```
Each tag is composed of date and git-hash.
For public/gitlab CI, we can read from this file to specify the CI docker version.
The docker file update and unittest on new container are decoupled, after we upgrade dockerfile, the ci will still be running in earlier tag until we update the `docker-tags.yml`.
cc @bkryu @nvmbreughe @yongwww
> ci: add docker-tags.yml to specify the docker image tag used in CI

- .github/workflows/release-ci-docker.yml
- docker/install/install_python_packages.sh
TVM-FFI made a new release with bugfix on potential memory leak:
https://github.com/apache/tvm-ffi/pull/87
This PR bumps the apache-tvm-ffi version in docker container.
https://github.com/apache/tvm-ffi/pull/87
> docker: upgrade apache-tvm-ffi==0.1.0b15 in docker container

- csrc/fused_moe/cutlass_backend/flashinfer_cutlass_fused_moe_sm100_binding.cu
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/moe_gemm/moe_gemm_template_dispatch.h
- tests/moe/test_trtllm_cutlass_fused_moe.py
- Add safety check for empty tactics to provide clear error message
- Allow SM121 devices to use SM120 kernel configurations
- Mark test_moe_mxfp8_mxfp4 as xfail (kernel not yet implemented) for sm120/121
cc: @djmmoss @yzh119 @bkryu @cyx-6  @nv-yunzheq
> bugfix: add check for empty MoE tactics and allow sm121 to use sm120 config

- docker/install/install_python_packages.sh
The click package was not being installed, which led to failures of a test in tests/cli. This worked locally on some machines as `pip install --user` was mixed with `conda`. We should add it with conda for consistency.
> Added click package

- .github/workflows/release-ci-docker.yml
- docker/Dockerfile.cu126
- docker/Dockerfile.cu126.dev
- docker/Dockerfile.cu128
- docker/Dockerfile.cu128.dev
- docker/Dockerfile.cu129
- docker/Dockerfile.cu129.dev
- docker/Dockerfile.cu130
- docker/Dockerfile.cu130.dev
- docker/install/install_python_packages.sh
- requirements.txt
- setup.py
To avoid duplication bugs between Dockerfile (install_python_packages.sh) and setup.py, the common dependencies were moved into requirements.txt
> Moved common requirements from docker and setup.py to file
