flashinfer-ai/flashinfer

- python/flashinfer/ops/__init__.py
add prefill kernel pytorch api
> PyTorch API for Single Request Prefill Operator

- include/flashinfer/permuted_smem.cuh
- include/flashinfer/prefill.cuh
Reverts flashinfer-ai/flashinfer#38
> Revert "[Refactor] Rename cell to b128"

- include/flashinfer/permuted_smem.cuh
- include/flashinfer/prefill.cuh
#38  is buggy and was reverted in #39 , this PR fixes the compilation errors.
> [Refactor] Rename cell to b128

- src/test_batch_decode.cu
- src/test_batch_prefill.cu
- src/test_single_decode.cu
- src/test_single_prefill.cu
> [Test] Add unittests for `group_size=4`

- include/flashinfer/cascade.cuh
- include/flashinfer/prefill.cuh
- include/flashinfer/utils.cuh
Some silly bugs in PR #48 , this PR fixes them.
> [Hotfix] Fix the bugs in #48

- include/flashinfer/cascade.cuh
Use another schedule for merge states function.
> [Performance] Accelerate merge function when batch size is small

- include/flashinfer/cascade.cuh
- src/test_cascade.cu
More lengths, sparse/non-sparse S.
> [Unittest] Enhance merge state(s) unit tests

- src/bench_cascade.cu
> [Bugfix] Fix the bug in `bench_cascade`

- .github/workflows/build-doc.yml
The `build-doc.yml` is buggy, this PR fix the issue.
> [Doc] Fix github action workflows.

- .github/workflows/release_wheel.yml
> [CI] Bugfix on artifact path

- python/flashinfer/page.py
Thanks @soodoshll for reporting this issue.
> [Bugfix] Fix the import issue in `page.py`

- docs/api/python/cascade.rst
- docs/conf.py
- docs/installation.rst
- docs/tutorials/kv_layout.rst
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/page.py
- python/flashinfer/prefill.py
Add examples for all classes/functions.
> [Doc] More examples

- python/flashinfer/__init__.py
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/page.py
- python/flashinfer/prefill.py
Also fix some format issues in python docstring.
> [Bugfix] Python package do not have `__version__`

- .github/workflows/release_wheel.yml
> fix: fix the re expression in build wheel scripts

- .github/workflows/release_wheel.yml
> ci: add an option of skipping build wheels

- .github/workflows/release_wheel.yml
> ci: run release if build wheel success or skipped

- README.md
- docs/conf.py
- docs/installation.rst
new wheels url formats (for different pytorch versions)/
> doc: update 0.0.2 documentation

- python/setup.py
1. This PR revert the changes of relative path in `setup.py`. See comments: https://github.com/flashinfer-ai/flashinfer/pull/128#discussion_r1500172800
2. Fix python3.8 build.
> [Minor] Quick fix on python build for path and python3.8

- include/flashinfer/attention/decode.cuh
The same optimization was used in our prefill attention kernels, this PR applies this optimization to decode attention kernels.
> perf: multiple q by sm_scale in decode kernels

- python/flashinfer/decode.py
- python/flashinfer/prefill.py
> doc: fix docstring of `pos_encoding_mode` field

- include/flashinfer/attention/prefill.cuh
To speed up compilation a little bit.
> misc: ignore invalid configurations

- python/MANIFEST.in
Scripts used for generating cu files are not included.
> bugfix: fix `manifest.in`

- docs/conf.py
documentation version number was out-dated.
> doc: bump documentation version

- include/flashinfer/mma.cuh
MMA instructions for fp8 are available in PTX 8.4 and CUDA 12.4.
> feat: add mma instructions for fp8

- python/csrc/batch_prefill.cu
- python/csrc/single_prefill.cu
The previous message for dispatch error is confusing #157 #181
> fix: fix python package dispatch error message

- .gitignore
- include/flashinfer/attention/handler.cuh
- include/flashinfer/decode_attention_decl.cuh
- include/flashinfer/mma.cuh
- python/csrc/batch_decode.cu
- python/csrc/batch_prefill.cu
- python/csrc/pytorch_extension_utils.h
- python/csrc/single_decode.cu
- python/csrc/single_prefill.cu
- python/generate_dispatch_inc.py
- python/literal_map.py
- python/setup.py
- scripts/formatter.sh
We used to mix use two different styles of dispatch mode,  in this PR we refactor the codebase to use a unified dispatch scheme.
> refactor: unify dispatch scheme

- CMakeLists.txt
- include/flashinfer/norm.cuh
- include/flashinfer/sampling.cuh
- include/flashinfer/utils.cuh
- src/bench_sampling.cu
- src/test_norm.cu
- src/test_sampling.cu
Remove debug codes, and support different vec_size.
> sampling: fix alignment issue for vocab_size not divisible by vec_size

- include/flashinfer/prefill_attention_decl.cuh
- python/csrc/batch_prefill.cu
move `DISPATCH_PAGE_SIZE` out of `BatchPrefillWithPagedKVCacheWrapperDispatched`
> move dispatch for batch prefill

- include/flashinfer/sampling.cuh
skip the scan operation on a chunk if we know this chunk do not overlap with the uniform needle.
> perm: optimize sampling performance

- include/flashinfer/sampling.cuh
follow up of #213 , add the parallel version of parallel sampling without top-p restriction.
> misc: parallel sampling from probability

- include/flashinfer/sampling.cuh
- src/tvm_wrapper.cu
This commit adds the wrapper functions for sampling functions.
> [TVMWrapper] Add wrapper functions for sampler

- include/flashinfer/sampling.cuh
- src/bench_sampling.cu
- src/test_sampling.cu
- src/tvm_wrapper.cu
max_top_p/k_rounds doesn't have to be a template parameter.
> misc: make max_top_p/k_rounds a input argument instead of template parameter

- CMakeLists.txt
- python/generate_batch_paged_prefill_inst.py
> cmake: fix cmake files

- include/flashinfer/sampling.cuh
> bugfix: fix sampler's implementation bug when dtype is not float32

- python/setup.py
This reverts commit f1da148032bef25b817bcc87f00560264a859ab4.
> Revert "ci: remove multi-threading in nvcc compile flags (#229)"

- python/setup.py
> fix: remove 8 from default page size

- include/flashinfer/attention/handler.cuh
we observed that the multiple `cudaMemcpyAsync` still incurs non-negligible overhead in `BeginForward` functions, this PR accelerates `BeginForward` by:
1. pre-allocate paged-locked host memory (pinned memory) for host-side page data structures.
2. Issue a single `cudaMemcpyAsync` that copies all page data structure.
cc @tqchen
> perm: use page-locked host memory for auxiliary data structure on CPU

- docs/api/python/decode.rst
- docs/api/python/sampling.rst
Update documentation for cudagraph wrapper and spec sampling apis
> doc: update documentation

- docs/tutorials/kv_layout.rst
(num_heads, head_dim, seq_len) to (num_heads, seq_len, head_dim)
> doc: bugfix in kv-layout docs

- .gitmodules
For group gemm in MoE and LoRA models, we use the combination of custom CUDA kernels and cutlass & composable kernels (for NVIDIA & AMD GPUs, correspondingly).
This PR adds dependency to the two repos.
> 3rdparty: add dependency to cutlass and composable kernels

- docs/tutorials/kv_layout.rst
- python/flashinfer/prefill.py
- python/setup.py
add fix the bugs in `single_prefill_with_kv_cache` and `single_prefill_with_kv_cache_return_lse` when using mask.
> doc: add some documentation for attention with mask API

- python/setup.py
Some debug compilation configs are simplified for debugging purpose, this PR adds them back.
> hotfix: fix setup.py

- python/flashinfer/decode.py
- python/setup.py
- python/tests/test_decode_fp8_calibration_scale.py
> fp8: add calibration scale for decode attention operators

- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/sampling.cuh
- python/csrc/batch_decode.cu
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/flashinfer/decode.py
- python/flashinfer/prefill.py
Reverts flashinfer-ai/flashinfer#275
> Revert "feat: support cuda graph for batched multi-query(prefill/append) attention"

- include/flashinfer/distributed/all_reduce.cuh
We missed some synchronizations in all reduce operators, which causes deadlock and incorrect result some times.
> bugfix: fix the synchronization issue in distributed operators

- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/handler.cuh
- include/flashinfer/decode_attention_decl.cuh
- python/generate_batch_paged_decode_inst.py
- src/bench_batch_decode.cu
- src/flashinfer_ops.cuh
- src/test_batch_decode.cu
Change the use of an optional `fixed_grid_size` to `padded_batch_size`.
> refactor: refactor decode handler

- python/flashinfer/decode.py
- python/flashinfer/prefill.py
follow up of #299, pre-attention -> pre-softmax.
> doc: fix logits cap docstring

- python/tests/test_group_gemm.py
The case of `column_major=True` and `use_weight_indices=False` is not properly handled.
> test: fix unittest for group gemm

- python/tests/test_decode_fp8_calibration_scale.py
Do not test alibi because of large numerical difference.
> test: fix fp8 calibration test

- include/flashinfer/attention/handler.cuh
- include/flashinfer/attention/prefill.cuh
- python/tests/test_batch_prefill_kernels.py
- src/test_cascade.cu
Cascade inference test was failed for a while, this PR fixes it.
Also fixes some of formats issues of previous PR #310.
> bugfix: fix cascade test

- include/flashinfer/attention/handler.cuh
- python/csrc/batch_prefill.cu
- python/csrc/flashinfer_ops.h
- python/flashinfer/decode.py
- python/flashinfer/prefill.py
- src/bench_batch_decode.cu
- src/bench_cascade.cu
- src/test_batch_prefill.cu
- src/test_cascade.cu
- src/tvm_wrapper.cu
Some last commits for bugfix are missing for #322.
> Bugfix: bugfix to #322

- .github/workflows/release_wheel.yml
- .gitignore
- docs/conf.py
- scripts/update_whl_index.py
> ci: separate `update_whl_index` from github action files

- python/flashinfer/prefill.py
> doc: bugfix on documentation about mask usage

- python/flashinfer/prefill.py
- python/tests/test_batch_prefill_kernels.py
> bugfix: fix the `forward_return_lse` function in `BatchPrefillWithRaggedKVCache` class

- .gitmodules
> misc: use https for submodule spdlog

- README.md
Hi @yzh119 May you help review this PR? Thanks. cc @guocuimi
> docs: update README for ScaleLLM

- CHANGELOG.md
> docs: fix CHANGELOG link

- include/flashinfer/attention/prefill.cuh
- include/flashinfer/fastdiv.cuh
Alibi experienced a performance degradation after #262 because of increased number of integer division.
> perf: accelerate alibi

- docs/api/python/sampling.rst
- docs/conf.py
- docs/index.rst
- python/flashinfer/__init__.py
* bump doc version
* add `top_k_top_p_sampling_from_probs` and `flashinfer.sparse` to documentation.
> doc: update documentation to v0.1.0

- python/flashinfer/__init__.py
- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/group_gemm.py
- python/flashinfer/norm.py
- python/flashinfer/page.py
- python/flashinfer/prefill.py
- python/flashinfer/quantization.py
- python/flashinfer/sampling.py
- python/flashinfer/sparse.py
- python/flashinfer/utils.py
- python/mypy.ini
- scripts/task_cpplint.sh
- scripts/task_mypy.sh
- scripts/task_pylint.sh
For better formatting and code style for python/C++ codes.
> ci: setup mypy, pylint and cpplint

- README.md
- docs/installation.rst
Also add some instructions to compile pip wheel from sources and C++ benchmarks from source.
> doc: update documentation for cuda 12.4 and pytorch 2.4

- include/flashinfer/attention/prefill.cuh
- include/flashinfer/permuted_smem.cuh
The swizzling mode name in #420 is wrong, this PR aligns it with ptx documentation:
32B -> 64B
64B -> 128B
> refactor: rename swizzling mode name

- include/flashinfer/sampling.cuh
1. A `__syncthreads` is missing after cub `BlockReduce`.
2. Use unique uniform samples.
> bugfix: fix chain speculative sampling implementation

- include/flashinfer/sampling.cuh
- python/tests/test_sampling.py
> bugfix: fix the correctness issue of spec sampling kernels

- python/csrc/pytorch_extension_utils.h
Fix https://github.com/flashinfer-ai/flashinfer/issues/402#issuecomment-2254175747
> bugfix: fix dispatch fp16 type when enable fp8

- include/flashinfer/attention/prefill.cuh
- include/flashinfer/frag_layout_swizzle.cuh
- include/flashinfer/utils.cuh
> perf: slight optimization on f16->f8 fragment layout swizzling

- include/flashinfer/frag_layout_swizzle.cuh
- include/flashinfer/vec_dtypes.cuh
> perf: slight optimization on fragment layout swizzle

- python/flashinfer/prefill.py
some tests are failed because we use the wrong function for prefill wrapper with custom mask, this pr fixes the issue.
> bugfix: fix the python api of prefill wrapper + custom mask

- python/flashinfer/cascade.py
- python/flashinfer/decode.py
- python/flashinfer/group_gemm.py
- python/flashinfer/page.py
- python/flashinfer/prefill.py
- python/flashinfer/quantization.py
- python/flashinfer/sampling.py
1. example of SegmentGEMMWrapper
2. example of chain_speculative_sampling
3. example of renorm kernels
4. example of packbits, segment_packbits
5. fix the misuse of `Notes`
> docs: add some documentation

- python/flashinfer/cascade.py
- python/flashinfer/group_gemm.py
- python/flashinfer/rope.py
- python/flashinfer/sampling.py
- fix broken links
- add rope docs
- add default option for sampling apis
> doc: another bunch of documentation improvement

- docs/api/python/gemm.rst
- python/flashinfer/cascade.py
- python/flashinfer/gemm.py
- python/tests/test_group_gemm.py
The documentation was not indexed properly in #469 , this PR fixes the issue.
> doc: fix fp8 bmm documentation

- include/flashinfer/activation.cuh
- python/csrc/activation.cu
- python/csrc/flashinfer_ops.cu
- python/csrc/flashinfer_ops.h
- python/flashinfer/__init__.py
- python/flashinfer/activation.py
- python/tests/test_activation.py
> feat: add gelu_and_mul

- include/flashinfer/norm.cuh
remove redundant load in FusedAddRMSNormKernel
> fix: remove redundant load

- include/flashinfer/norm.cuh
as titled
thanks @Bruce-Lee-LY @MARD1NO cc @yzh119
> minor: refine norm

- python/csrc/flashinfer_ops.h
- python/csrc/norm.cu
- python/flashinfer/norm.py
- python/tests/test_norm.py
as titled
fix https://github.com/flashinfer-ai/flashinfer/issues/500
> minor: add out parameter for rmsnorm and gemma_rmsnorm

- README.md
We created a slack workspace for flashinfer discussions.
> community: add link to slace workspace

- include/flashinfer/gemm/bmm_fp8.cuh
- python/csrc/bmm_fp8.cu
This PR made refactors `bmm_fp8.cuh` to fix the following behaviors:
1. We should not instantiate templates in header files, if there are two source files includes this header, there will be symbol conflict. So it's preferable to instantiate templates in source files.
2. We don't want to depend on torch source code in the headers as torch api's might subject to changes and other backends do not want to rely on a specific version of torch. We should make the dependency of header files as simple as possible (only cuda and libc++).
cc @zhyncs
> refactor: refactor `bmm_fp8.cuh`

- include/flashinfer/attention/decode.cuh
- include/flashinfer/attention/prefill.cuh
- include/flashinfer/attention/variants.cuh
If true, use online softmax rules to update attention states.
If not, simply adding the partial attention results.
In the future, we can generalize this as a state update function.
> feat: add a `use_softmax` field in variant class

- include/flashinfer/attention/scheduler.cuh
Throw errors when qo_indptr or kv_indptr is not monotonic
> misc: Improve scheduler error checking

- include/flashinfer/attention/prefill.cuh
- include/flashinfer/mma.cuh
- include/flashinfer/vec_dtypes.cuh
> misc: replace `is_same` with `is_same_v`

- python/flashinfer/jit/__init__.py
When we run multi-GPU inference with flashinfer JIT mode, multiple processes will simultaneously JIT the same op, which causes a "File exists" error. This PR adds file lock for the build directory before op JIT to avoid this error.
> Add file lock before op JIT.

- flashinfer-aot/csrc_aot/batch_decode.cu
- flashinfer-aot/csrc_aot/batch_prefill.cu
- python/flashinfer/decode.py
- python/flashinfer/jit/batch_decode_templ.py
- python/flashinfer/jit/batch_prefill_templ.py
- python/flashinfer/prefill.py
- python/flashinfer/sparse.py
- tests/test_batch_decode_kernels.py
> perf: improve plan performance by using non-blocking memcpy

- flashinfer-aot/csrc_aot/batch_prefill.cu
#554 didn't update the `batch_prefill.cu` (which was used in AOT mode) according to the API change.
cc @abcdabcd987
> bugfix: fix `batch_prefill.cu` in AOT mode after #554

- include/flashinfer/sampling.cuh
No need to name the nested struct.
> misc: simplifying sampilng data structures

- docs/conf.py
Documentation build was failed, this PR mocks triton import to fix it.
> [doc] mock triton import

- include/flashinfer/attention/prefill.cuh
The prefill attention kernel performance has degraded significantly in recent releases (since v0.1.2), especially on A100 when `causal=True`, this is mainly because we add new attention variants (which increases register usage thus incurs register spilling) and move some parameters from compile-time to runtime.
This PR alleviates the issue by caching some of the variables regarding GQA group size.
In the next PR, we will support another mode `kv_head_major` in addition to `qo_head_major`, to further accelerate GQA prefill with query size >= 64.
cc @AKKamath
> perf: fix prefill kernel performance degradation (step 1)

- README.md
- docs/index.rst
Add lorax and acknowledge aitemplate for kernel generation.
> doc: update readme

- python/flashinfer/page.py
> doc: improve the docstring of `append_paged_kv_cache`

- src/bench_batch_decode.cu
Add `typename TKV` so that it's convenient to benchmark FP8 KVCache. A example output:
> test: add DtypeKV template param in bench_batch_decode

- python/flashinfer/decode.py
- python/flashinfer/jit/attention.py
- python/flashinfer/jit/batch_decode_mla_templ.py
- tests/test_mla_decode_kernel.py
Some of the commits for fixing MLA are missing in #618, this PR add them back.
> bugfix: fix MLA with new JIT pipeline

- include/flashinfer/attention/prefill.cuh
- include/flashinfer/utils.cuh
fragment should refer to the element hold by each thread in tensor core layout.
mma is a more accurate term for a mma block.
> refactor: rename num_frags to num_mma

- custom_backend.py
otherwise aot compilation will be too slow.
> packaging: add ninja to dependencies

- tests/test_alibi.py
- tests/test_batch_decode_kernels.py
- tests/test_batch_prefill_kernels.py
- tests/test_block_sparse.py
- tests/test_logits_cap.py
- tests/test_non_contiguous_decode.py
- tests/test_non_contiguous_prefill.py
- tests/test_shared_prefix_kernels.py
- tests/test_sliding_window.py
- tests/test_tensor_cores_decode.py
> bugfix: fix AOT mode unittests

- flashinfer/jit/attention.py
- flashinfer/jit/batch_prefill_sm90_templ.py
- flashinfer/jit/core.py
- flashinfer/jit/single_prefill_sm90_templ.py
- flashinfer/prefill.py
- tests/test_jit_warmup.py
> feat: add JIT compilation support for FA3 templates

- include/flashinfer/attention/hopper/mainloop_mma.cuh
This PR resolves an issue in the SWA implementation introduced in #667, where the process would hang under specific conditions.
> bugfix: Fix SWA Implementation Hanging Issue

- scripts/run-ci-build-wheel.sh
- setup.py
sm90 is not available for cuda11.
> ci: disable sm90 for cuda11

- scripts/run-ci-build-wheel.sh
wgmma works for cu123 and above.
> ci: change sm90 minimal requirement to cu123

- flashinfer/utils.py
Should only enable fa3 for cuda 12.3+
> bugfix: bug fix on `determine_attention_backend` condition

- .github/workflows/release_wheel.yml
- scripts/update_whl_index.py
> ci: fix the update_whl_index script to regonize version number with "post" and add torch2.5

- aot_build_utils/generate_batch_paged_decode_inst.py
- src/flashinfer_ops.cuh
* Create MLA instantiations
* Set `use_sliding_window=False` in benchmarks.
> [bugfix] Fix cpp tests/benchmarks

- README.md
- docs/installation.rst
- scripts/update_whl_index.py
Followup of #729 , this PR fixes the installation instructions as well as scripts for matching package names.
> misc: addressing the package renaming issues

- include/flashinfer/attention/hopper/variants.cuh
Some commits are missing in #772 , this PR fix the issue.
> hotfix: follow up of #772

- tests/jit_utils.py
- tests/test_jit_warmup.py
Followup of #765 , fix the JIT warmup utilities functions.
> bugfix: fix the JIT warmup arguments in unittests

- aot_build_utils/generate_batch_paged_prefill_inst.py
- aot_build_utils/generate_batch_ragged_prefill_inst.py
- csrc/batch_prefill_paged_kernel_inst.jinja
- csrc/batch_prefill_ragged_kernel_inst.jinja
- include/flashinfer/utils.cuh
#776 added CTA_TILE_Q=32 but it produces incorrect result.
> bugfix: drop CTA_TILE_Q=32

- include/flashinfer/attention/mla_fa2.cuh
The previous PR #804 only tests page_size 1, this PR fixes the issue with other page sizes and add corresponding unittests.
> bugfix: mla page-attention kernel for different page sizes

- benchmarks/bench_deepseek_mla.py
- csrc/batch_mla_plan.cu
- csrc/batch_mla_pybind.cu
- csrc/batch_mla_run.cu
- docs/api/mla.rst
- docs/index.rst
- flashinfer/__init__.py
- flashinfer/mla.py
- include/flashinfer/attention/mla_fa2.cuh
- tests/test_deepseek_mla.py
* Add new MLA API to documentation.
* Rename PageAttention to PagedAttention to align with other frameworks.
> doc: add documentation to new MLA interface

- flashinfer/mla.py
> bugfix: fix the behavior of mla plan function when provided with host tensors

- include/flashinfer/attention/mla_fa2.cuh
Follow up of #814 , we found some correctness issue of sm89 MLA kernels, this PR fixes them.
> bugfix: bugfix on sm89 MLA

- include/flashinfer/attention/mla_fa2.cuh
We met some very weird issues, might be a nvcc bug.
> hotfix: bugfix on #812

- flashinfer/jit/core.py
> bugfix: update `clear_cache_dir` in JIT

- .github/workflows/release_wheel.yml
suggest to use 3 latest pytorch versions to release the wheel.
> use 3 latest pytorch version

- docs/api/page.rst
Hi,
Fixing 1 spelling typo
Didier
> Update page.rst: fixing 1 typo

- docs/installation.rst
Hi,
Fixed 2 wording issues in text: see commit diff
Best,
Didier
> Update installation.rst: fixing 2 typos

- flashinfer/decode.py
- flashinfer/mla.py
- flashinfer/prefill.py
- flashinfer/sparse.py
- flashinfer/utils.py
- tests/test_batch_decode_kernels.py
- tests/test_batch_prefill_kernels.py
- tests/test_block_sparse.py
- tests/test_deepseek_mla.py
> feat: adding `out` and `lse` parameters to `run` functions to allow user allocated output buffer

- flashinfer/activation.py
- flashinfer/norm.py
- flashinfer/page.py
- flashinfer/prefill.py
Hi,
As per your request, 4 previous PRs re. typos have been merged into this global one.
I'll do that again in the future
Didier
> Merge of previous PRs for typos in a single one. As per your request.

- README.md
ref https://github.com/ModelTC/lightllm/pull/737/files
> add lightllm adoption

- flashinfer/sampling.py
> [API] Fix top_k_top_p_sampling_from_logits param typo

- tvm_binding/batch_mla_run.cu
This PR fixes the header include, following changes in #887.
> [JIT] Fix MLA header in TVM binding

- docs/tutorials/kv_layout.rst
Hi,
As said in title: fixing different spelling issues in  doc file kv_layout.rst
Didier
> Fixing several typos in doc file kv_layout.rst

- include/flashinfer/attention/mla_hopper.cuh
> perf: tweak register amount for producer/consumer in MLA template

- include/flashinfer/attention/mla_hopper.cuh
1. defer barrier sync for `p_smem`
2. change unroll number from 1 to 2
We found there are still significant overhead for synchronizing two consumers in qk stage. Use only one warpgroup for qk can resolve the issue.
> perf: tweak the pipeline design of mla kernel

- .github/workflows/release-ci-docker.yml
- docker/Dockerfile.ci_gpu
- docker/install/install_python.sh
- docker/install/install_torch.sh
Add add a github action to create docker images for CI.
> ci: add dockerfile for CI

- csrc/pytorch_conversion_utils.h
Fix the issue mentioned in https://github.com/flashinfer-ai/flashinfer/pull/931#discussion_r1993111175
> bugfix: fix include header name conflict

- tvm_binding/batch_mla_run.cu
This PR applies changes in #898 and #900 to the MLA TVM binding.
> fix: Fix MLA TVM binding for the latest changes

- include/flashinfer/attention/mla_hopper.cuh
> bugfix: fix potential issues of FA3 template loading nans for PageAttention

- Jenkinsfile
> ci: switch to on-demand instances if spot instance is interrupted

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/install/install_python.sh
- .devcontainer/install/install_python_packages.sh
- docker/install/install_python_packages.sh
Use cu128 and nightly pytorch for blackwell development.
> misc: update devcontainer

- include/flashinfer/attention/variants.cuh
PR for solving issue: https://github.com/flashinfer-ai/flashinfer/issues/1005
> bugfix: Fix illegal memory access due to custom mask ptr

- benchmarks/bench_batch_decode.py
- benchmarks/bench_grouped_gemm.py
- csrc/flashinfer_gemm_sm90_ops.cu
- csrc/flashinfer_ops_sm90.cu
- csrc/group_gemm_bf16_bf16_sm90.cu
- csrc/group_gemm_e4m3_bf16_sm90.cu
- csrc/group_gemm_e4m3_f16_sm90.cu
- csrc/group_gemm_e5m2_bf16_sm90.cu
- csrc/group_gemm_e5m2_f16_sm90.cu
- csrc/group_gemm_f16_f16_sm90.cu
- csrc/group_gemm_sm90.cu
- flashinfer/gemm.py
- include/flashinfer/gemm/group_gemm_sm90.cuh
- setup.py
- tests/test_deepseek_mla.py
Move benchmarks from C++ side to python for easier performance tracking.
> misc: more benchmark scripts in Python

- include/flashinfer/attention/mla_hopper.cuh
Follow up of #952 , this PR adds the instrument code base to profile mla hopper implementation (fix #995 )
cc @ziyuhuang123
> misc: fix instrument code for mla profiler

- include/flashinfer/sampling.cuh
- tests/test_sampling.py
This closes https://github.com/flashinfer-ai/flashinfer/issues/1049.
> fix: top_k_mask_logits hangs on -inf inputs

- benchmarks/bench_mixed_attention.py
Supersedes https://github.com/yzh119/flashinfer-dev/pull/5
`python benchmarks/bench_mixed_attention.py`
> Benchmark: POD vs batched prefill

- .github/pull_request_template.md
> misc: add pull request template

- docs/tutorials/kv_layout.rst
> fix: fix a typo in docs

- flashinfer/jit/cpp_ext.py
> misc: jit: fix missing _get_glibcxx_abi_build_flags

- csrc/gemm_groupwise_sm100.cu
- csrc/gemm_sm100_pybind.cu
- csrc/group_gemm_groupwise_sm100.cu
- csrc/group_gemm_sm100_pybind.cu
- flashinfer/gemm.py
- include/flashinfer/gemm/gemm_groupwise_sm100.cuh
- include/flashinfer/gemm/group_gemm_groupwise_sm100.cuh
- tests/test_groupwise_scaled_gemm_fp8.py
1. Add support for SM100 groupwise GeMM K-major scale inputs
2. Add support for switching MMA SM for SM100 groupwise GeMM
3. Enable SM100 groupwise GeMM PDL(Programmatic Dependent Launch)
4. Upgrade CUTLASS version to 4.0
> SM100 Groupwise GeMM K-Major Scale Supports

- flashinfer/decode.py
> fix head_dim not defined if sm_scale is not None

- .github/workflows/build-doc.yml
- docs/build_docs.sh
- docs/wrap_run_llm.py
Adds the Ask-AI widget (powered by [run-llm](https://www.runllm.com/)) to the bottom-right corner of every documentation page. It's currently configured with a personal test account (assistant-id 1048). We may consider replacing it with a shared production assistant.
> doc: add Ask-AI widget

- csrc/nv_internal/include/tensorrt_llm/common/NvInferRuntime.h
- csrc/nv_internal/include/tensorrt_llm/common/dataType.h
- csrc/nv_internal/tensorrt_llm/cutlass_extensions/include/cutlass_extensions/epilogue/collective/epilogue_moe_finalize.hpp
- csrc/nv_internal/tensorrt_llm/cutlass_extensions/include/cutlass_extensions/gemm/kernel/moe_cute_util.cuh
- csrc/nv_internal/tensorrt_llm/kernels/cutlass_kernels/cutlass_type_conversion.h
- csrc/nv_internal/tensorrt_llm/kernels/internal_cutlass_kernels/include/moe_kernels.h
- csrc/nv_internal/tensorrt_llm/kernels/lora/lora.h
- flashinfer/fp4_quantization.py
- flashinfer/jit/core.py
- tests/test_trtllm_cutlass_fused_moe.py
Fix test and output shape of fp4 quantize to inline with that vllm's `scaled_fp4_quant`
> bugfix: Fix test and output shape of fp4 quantize

- .github/workflows/release_wheel_aarch64.yml
- scripts/run-ci-build-wheel.sh
> ci: Update images for self-hosted ARM64 runner

- docs/wrap_run_llm.py
Update assistant id.
cc @Ubospica
> misc: update runllm widget

- docker/Dockerfile.ci_gpu
- docker/install/install_python_packages.sh
Install the python packages for CI docker: mpi4py, pynvml. They will be used for the comm ops.
https://github.com/flashinfer-ai/flashinfer/pull/1145, https://github.com/flashinfer-ai/flashinfer/pull/1134
> ci: Install mpi4py

- flashinfer/logits_processor/fusion_rules.py
- flashinfer/logits_processor/operators.py
- flashinfer/logits_processor/processors.py
- tests/test_logits_processor.py
Add fustion rule to apply recently implemented fused temperature + softmax kernel in https://github.com/flashinfer-ai/flashinfer/pull/1153.
> feat: logits processor fustion rule for temperature softmax

- docs/conf.py
> bugfix: fix broken docs build by adding missing dependencies

- tests/test_groupwise_scaled_gemm_fp8.py
Fix `test_groupwise_scaled_gemm_fp8.py` by modifying the distributions of random inputs and weights.
> Fix test_groupwise_scaled_gemm_fp8.py

- include/flashinfer/attention/blackwell/collective/sm100_fmha_fwd_epilogue_tma_warpspecialized.hpp
- include/flashinfer/attention/blackwell/collective/sm100_fmha_fwd_mainloop_tma_warpspecialized.hpp
- include/flashinfer/attention/blackwell/kernel/sm100_fmha_fwd_kernel_tma_warpspecialized.hpp
- tests/test_blackwell_fmha.py
Cherry picked from cutlass v4.0 changes.
cc @pavanimajety
> bugfix: fix blackwell fmha hanging issue for empty kv_len

- csrc/cudnn_sdpa_kernel_launcher.cu
Update the missing hash that is required 
- [ x] I have installed `pre-commit` by running `pip install pre-commit` (or used your preferred method).
- [x ] I have installed the hooks with `pre-commit install`.
- [ x] I have run the hooks manually with `pre-commit run --all-files` and fixed any reported issues.
- [ x] Tests have been added or updated as needed.
- [ x] All tests are passing (`unittest`, etc.).
> Fix missing hash in the cudnn cubin path

- csrc/cudnn_sdpa_kernel_launcher.cu
- flashinfer/cudnn/prefill.py
- tests/test_cudnn_prefill.py
- tests/test_cudnn_prefill_deepseek.py
Allow non-causal kernels of cudnn in cubin.
- [ x] I have installed `pre-commit` by running `pip install pre-commit` (or used your preferred method).
- [ x] I have installed the hooks with `pre-commit install`.
- [ x] I have run the hooks manually with `pre-commit run --all-files` and fixed any reported issues.
- [x ] All tests are passing (`unittest`, etc.).
> feat: Add non-causal cudnn prefill kernels

- csrc/trtllm_fused_moe_dev_kernel.cu
- include/flashinfer/trtllm/batched_gemm/trtllmGen_bmm_export/BatchedGemmInterface.h
- include/flashinfer/trtllm/batched_gemm/trtllmGen_bmm_export/KernelMetaInfo.h
Patch fp8 cubin availability (followup of #1212 )
> Patch fp8 cubin availability

- benchmarks/bench_groupwise_grouped_gemm_fp8_blackwell.py
- benchmarks/bench_groupwise_grouped_gemm_mxfp4_blackwell.py
- csrc/group_gemm_fp8_groupwise_sm100.cu
- csrc/group_gemm_mxfp4_groupwise_sm100.cu
- csrc/group_gemm_sm100_pybind.cu
- csrc/pytorch_extension_utils.h
- flashinfer/gemm.py
- flashinfer/jit/core.py
- include/flashinfer/cutlass_utils.cuh
- include/flashinfer/gemm/group_gemm_fp8_groupwise_sm100.cuh
- include/flashinfer/gemm/group_gemm_mxfp4_groupwise_sm100.cuh
- tests/test_groupwise_scaled_gemm_mxfp4.py
> feat: Support MXFP8 x MXFP4 CUTLASS grouped GEMM

- flashinfer/decode.py
Remove the redundant `sm_count` argument in the `TrtllmGenDecodeModule` which takes `window_left` position.
> Fix redundant argument in TrtllmGenDecodeModule

- flashinfer/gemm.py
add torch float4_e2m1fn_x2 check for cudnn fp4 backend
cudnn need this datatype to build graph.
> add torch float4_e2m1fn_x2 check for cudnn fp4 backend

- setup.py
only add cudnn dependency for x86 platform
> only add cudnn dependency for x86 platform

- csrc/trtllm_fused_moe_kernel_launcher.cu
- flashinfer/fused_moe.py
- tests/test_trtllm_gen_fused_moe.py
Make Fp8 MoE routing_bias optional
> Make Fp8 MoE routing_bias optional

- include/flashinfer/attention/pod.cuh
Mistakenly added a duplicate kernel launch last time (actually by cursor, but should've checked more closely😂)
cc @yzh119 
> Bug fix: fix duplicate launch in POD

- csrc/trtllm_gemm_runner.cu
- flashinfer/gemm.py
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/Enums.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/GemmInterface.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/GemmOptions.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/KernelMetaInfo.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/KernelParams.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/KernelTraits.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/TmaDescriptor.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/trtllm/gen/CommonUtils.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/trtllm/gen/CudaKernelLauncher.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/trtllm/gen/DtypeDecl.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/trtllm/gen/MmaDecl.h
- include/flashinfer/trtllm/gemm/trtllmGen_gemm_export/trtllm/gen/SfLayoutDecl.h
- tests/test_groupwise_scaled_gemm_fp8.py
Add fast implementation of DeepSeek-style block-scaled FP8 GEMM.
> Add blockwise-scaled FP8 GEMM via TRTLLM-Gen.

- flashinfer/gemm.py
LRU cache eviction blocks frameworks for cuda graph replay. Setting to a higher size. 
```Fatal Python error: Segmentation fault
Thread 0x00007f62e7ffe6c0 (most recent call first):
File "/opt/mycode/python/sglang/srt/managers/scheduler.py", line 2215 in watchdog_thread
File "/usr/lib/python3.12/threading.py", line 1010 in run
File "/usr/lib/python3.12/threading.py", line 1073 in _bootstrap_inner
File "/usr/lib/python3.12/threading.py", line 1030 in _bootstrap
Current thread 0x00007f62ebfff6c0 (most recent call first):
File "/usr/local/lib/python3.12/dist-packages/torch/cuda/graphs.py", line 88 in replay
File "/opt/mycode/python/sglang/srt/model_executor/cuda_graph_runner.py", line 752 in replay
File "/opt/mycode/python/sglang/srt/model_executor/model_runner.py", line 1633 in _forward_raw …
```
> [Bugfix] Change max_size for LRU

- flashinfer/comm/trtllm_ar.py
fixes https://github.com/flashinfer-ai/flashinfer/issues/1256
> gen_trtllm_comm_module: fix device capability detection

- docker/install/install_python_packages.sh
Add nvidia-cudnn-cu12 and nvidia-cudnn-frontend to the docker container.
#1283  #1312 #1317 
cc @Anerudhan
> Update CI docker container to use latest cudnn

- docker/install/install_python_packages.sh
Fix the CI error in https://github.com/flashinfer-ai/flashinfer/pull/1369
https://github.com/flashinfer-ai/flashinfer/pull/1369
> ci: add requests to ci docker container

- flashinfer/gemm.py
enable cublas for fp4 gemm when cudnn == 9.11.1 or >= 9.13
> feature: enable cublas for fp4 gemm when cudnn == 9.11.1 or >= 9.13

- tests/conftest.py
> Relax the clear_cuda_cache

- csrc/trtllm_fused_moe_kernel_launcher.cu
> Fix trtllm moe launcher local_num_experts

- flashinfer/fused_moe/core.py
> Fix redundant kernels in moe

- .github/workflows/release-ci-docker.yml
> Use self hosted runner for arm image build

- NOTICE
Adds NOTICE file to specify copyrights for both NVIDIA and Flashinfer community.
Follows: https://infra.apache.org/licensing-howto.html#example-notice
None
- [ ✅ ] I have installed `pre-commit` by running `pip install pre-commit` (or used your preferred method).
- [ ✅ ] I have installed the hooks with `pre-commit install`.
- [ ✅ ] I have run the hooks manually with `pre-commit run --all-files` and fixed any reported issues.
- [ N/A ] Tests have been added or updated as needed.
- [ N/A ] All tests are passing (`unittest`, etc.).
Check dates and naming of "Flashinfer community"
> Add NOTICE with copyrights

- .github/workflows/release-ci-docker.yml
> Add disk cleanup for Docker builds

- Jenkinsfile
> ci: Add ARM AOT test

- flashinfer/gemm.py
replace the gemm+pointwise(alpha) with
gemm+pointwise(scale_a)+pointwise(scale_b)
> bugfix: fix perf issue by using fp8 graph that can use cublaslt

- flashinfer/jit/core.py
This is useful for me to figure out the logs belong to which line during debugging.
> [RFC] log filename and lineno in flashinfer jit logger

- flashinfer/aot.py
- include/flashinfer/comm/vllm_custom_all_reduce.cuh
Fixes the issue in https://github.com/flashinfer-ai/flashinfer/issues/1468.
> Remove __restrict__ extension to fix compilation error on GB200

- flashinfer/aot.py
> fix(aot): unused compute in has_sm

- flashinfer/jit/cpp_ext.py
Add cuda version check for option `-static-global-template-stub`. `-static-global-template-stub` is only enabled for cuda >= 12.8.
cc: @zhyncs
> add cuda version check for jit

- flashinfer/gemm.py
Add sm check for sm100 only cutlass/trtllm kernel
> Add sm check for sm100 only cutlass/trtllm kernel

- tests/test_groupwise_scaled_gemm_mxfp4.py
bump cutlass submodule to support b300 and Thor.
> bump cutlass submodule to v4.2

- flashinfer/cute_dsl/blockscaled_gemm.py
> typo: fix typo in variable names of fp4 masked gemm

- csrc/trtllm_gemm_runner.cu
update trtllm-gen gemm kernel names
> bugfix: update trtllm-gen gemm kernel names

- tests/test_hopper.py
- tests/test_hopper_fp8_attention.py
> bugfix: Adding version checks to tests/test_hopper*.py files

- flashinfer/comm/mnnvl.py
Port changes from https://github.com/NVIDIA/TensorRT-LLM/pull/6645/files#diff-d9b4b5c89e04e85b9e1b2fa1d3d523e14c2846e5a17afc30746d63743d1f3418 which allows MnnvlMemory to be used on B200 instead of only GB200. This is used for the alltoallv workspaces.
Since `supports_mnnvl` has been updated, tests which were previously skipped will now run.
> feat: Enable MnnvlMemory (for alltoallv) on B200

- .github/workflows/release-ci-docker.yml
- docker/Dockerfile.cu130
- docker/install/install_python_packages.sh
> ci: add ci container of cuda 13 and add cute-dsl as dependency.

- flashinfer/cute_dsl/blockscaled_gemm.py
- flashinfer/cute_dsl/utils.py
Optimize make_ptr performance for cute_dsl as a workaround. Will remove the WAR after CuTeDSL release the optimization.
Performance: 20us+ => 1.4us
> [cute dsl] optimize cute dsl make_ptr perf

- csrc/trtllm_gemm_runner.cu
- flashinfer/artifacts.py
- flashinfer/gemm.py
- tests/test_mm_fp4.py
> patch mm segfault & patch cubin avail.

- csrc/nv_internal/tensorrt_llm/thop/fp4Quantize.cpp
- csrc/nv_internal/tensorrt_llm/thop/fp4Quantize.h
- flashinfer/__init__.py
- flashinfer/fp4_quantization.py
- tests/test_fp4_quantize.py
Add the support of fp4_batched_quantize(), ported from TensorRT-LLM.
https://github.com/flashinfer-ai/flashinfer/issues/1551
> feat: add support of fp4_batched_quantize

- scripts/codeowner_analyzer.py
Help automate the process of setting up CODEOWNER
> misc: add script to analyzer code owners from git history

- flashinfer/__main__.py
- flashinfer/aot.py
- flashinfer/jit/__init__.py
- flashinfer/jit/core.py
Added functionality to check if modules are compiled, whether they're JIT/AOT, update times, etc.
New commands:
```python
python -m flashinfer list-modules gemm_sm100 # or other module
python -m flashinfer module-status
```
Module status now shows up in python -m flashinfer show-config too.
CI tests for AOT module coverage coming in future PRs.
@cyx-6 @yongwww
> ci: collect module status and update flashinfer-cli

- tests/test_trtllm_gen_fused_moe.py
Do real quantization on hidden_states and relax the threshold.
> test: better fp8 quantization init for fused_moe test

- .gitignore
- scripts/run_test_blackwell_attention_kernels.sh
- scripts/run_test_blackwell_gemm_kernels.sh
- scripts/run_test_blackwell_moe_kernels.sh
- scripts/run_test_blackwell_utils_kernels.sh
- scripts/task_test_blackwell_kernels.sh
Refactor the Blackwell unit test scripts so that they will run to completion regardless of failures and output JUnit xml for rendering pass/fail status.
> Refactor Blackwell unit test scripts

- flashinfer/prefill.py
- tests/test_attention_sink_blackwell.py
- tests/test_batch_attention.py
- tests/test_bmm_fp8.py
- tests/test_groupwise_scaled_gemm_fp8.py
- tests/test_groupwise_scaled_gemm_mxfp4.py
- tests/test_mm_fp4.py
- tests/test_trtllm_gen_attention.py
- tests/test_trtllm_gen_fused_moe.py
- tests/test_trtllm_gen_mla.py
- tests/test_xqa.py
> test: skip the unsupported test cases for sm120/121

- benchmarks/README.md
> typo: Super tiny fix typo

- docs/tutorials/recursive_attention.rst
> doc: Super tiny fix doc math

- csrc/cudnn_sdpa_kernel_launcher.cu
- flashinfer/aot.py
There are still some modules not captured by aot.py, this PR completes them.
> ci: complete the list of modules in aot.py

- tests/test_triton_cascade.py
> Small fix on an exception

- docker/install/install_python_packages.sh
- scripts/run_test_blackwell_attention_kernels.sh
- scripts/run_test_blackwell_comm_kernels.sh
- scripts/run_test_blackwell_gemm_kernels.sh
- scripts/run_test_blackwell_moe_kernels.sh
- scripts/run_test_blackwell_utils_kernels.sh
- scripts/task_test_blackwell_kernels.sh
Moved pip installs to docker script.
> Docker updates

- docker/install/install_python_packages.sh
Incorporate changes in https://github.com/apache/tvm-ffi/commit/eb5492a1d2feaff5f11a51f32cf5ad339c789665 to fix the CI errors in https://ci.tlcpack.ai/blue/organizations/jenkins/flashinfer-ci/detail/PR-1641/95/pipeline
#1641 
cc @nvmbreughe @cyx-6 @tqchen
> ci: upgrade apache-tvm-ffi version in ci containers

- tests/conftest.py
- tests/test_triton_cascade.py
fix "AttributeError: 'GPUArchitectureError' object has no attribute 'msg'" error. 
> fix error message

- docker/Dockerfile.cu128.dev
- docker/Dockerfile.cu129.dev
- docker/Dockerfile.cu130
- docker/Dockerfile.cu130.dev
This PR fixes devcontainer docker file cuda version
> bugfix: fix devcontainer docker file cuda version

- tests/gemm/test_cute_dsl_blockscaled_gemm.py
With the latest version of nvidia-cutlass-dsl, `mark_layout_dynamic` may throw errors like
```
>       self._dltensor_wrapper.mark_layout_dynamic(leading_dim)
E       RuntimeError: Expected strides[leading_dim] == 1, but got 7340032.
```
when calling `cutlass.torch.cute_tensor_like` and `l = 1` in gemm problem size. This issue has been reported to [cutlass#2673](https://github.com/nvidia/cutlass/issues/2673).
So this PR marks the cute dsl blockscaled gemm tests where `l = 1`, due to the issue of nvidia-cutlass-dsl.
> xfail the cute dsl tests for `l=1`

- csrc/tgv_gemm.cu
- flashinfer/gemm.py
- flashinfer/jit/gemm/core.py
Add missing nvcc flags to TGV gemm including the one that enables PDL feature.
Also add safe guarding checks to TGV gemm to prevent tensor size being too large for TMA.
> PDL patch for TGV GEMM 
